### ISSUE TITLE
Bert如何得到的向量？

### ISSUE THREAD

**Issue by cdj0311** [BrikerMan/Kashgari#1]
您好！
我有两个疑问，还望您解答。
1. BertEmbedding得到的是句子向量还是词向量？
2. keras_bert代码在哪里呢？
谢谢您！

**Comment by BrikerMan** [comment]
kashgari 中获取 BERT token 方法，如下

```python
from kashgari.embeddings import BERTEmbedding
embedding = BERTEmbedding('bert-base-chinese', sequence_length=30)

# 句子向量，shape 30*768
vector = embedding.embed(['如', '何', '得', '到', '的', '向', '量']) 

# 词向量 [-0.758835, 0.096518, 1.071875, 0.005038, 0.688799, ...]
vector[1]
```

keras-bert 我用了@CyberZHG 的实现 https://github.com/CyberZHG/keras-bert ，直接使用可以用这个的。

**Comment by cdj0311** [comment]
明白了，谢谢！

**Comment by shiwl0329** [comment]
> kashgari 中获取 BERT token 方法，如下
> 
> ```python
> from kashgari.embeddings import BERTEmbedding
> embedding = BERTEmbedding('bert-base-chinese', sequence_length=30)
> 
> # 句子向量，shape 30*768
> vector = embedding.embed(['如', '何', '得', '到', '的', '向', '量']) 
> 
> # 词向量 [-0.758835, 0.096518, 1.071875, 0.005038, 0.688799, ...]
> vector[1]
> ```
> 
> keras-bert 我用了@CyberZHG 的实现 https://github.com/CyberZHG/keras-bert ，直接使用可以用这个的。

大神，我想问一下，句子向量不是768维的么，30*768怎么转换成768维的句向量呢
