### ISSUE TITLE
[BUG] validation in tf.keras validation

### ISSUE THREAD

**Issue by Qian16** [BrikerMan/Kashgari#100]
Hello.  Check the  validation in build_model() in based model. You can update the file! Thx

**Comment by BrikerMan** [comment]
Please be more specific...

**Comment by Qian16** [comment]
Hello. In the the tf.keras version,  base_model file. In build_model() on line 77, you did not include validation_data argument. So if you have validation data, you can use it. Thanks.

**Comment by BrikerMan** [comment]
Got it.
