### ISSUE TITLE
[Question] Can I use it as an NER task in English?

### ISSUE THREAD

**Issue by aguang1201** [BrikerMan/Kashgari#101]
I know that it is used to do the Chinese NER task.Can I use it as an NER task in English?What kind of English corpus is needed?

**Comment by BrikerMan** [comment]
You can use Kashgari for any language, just need to tokenize your data first. For the English language, just need to prepare data like:

```
>>> x_train[0]
['EU', 'rejects', 'German', 'call', 'to', 'boycott', 'British', 'lamb', '.']
>>> y_train[0]
['B-ORG', 'O', 'B-MISC', 'O', 'O', 'O', 'B-MISC', 'O', 'O']
```

**Comment by aguang1201** [comment]
Got it。Thanks。

**Comment by zmd971202** [comment]
But as you mentioned in #136 , we should use BERT tokenizer to tokenize our data. So how should we pre-process our data when we use English ner data such as CoNLL and how to use the representation of the first sub-token as the input to the classifier (mentioned in BERT paper)?

**Comment by BrikerMan** [comment]
You need to tokenize your sentence using BERT tokenizer, then prepare token's labels according to tokenization result. If you using BERT tokenizer, it will add `[CLS]` token by default. BERTEmbedding will also add the `[CLS]` token by default. so if your data already includes the `[CLS]` token, remember to set `bert_embedding.add_bos_eos` property to False.

**Comment by BrikerMan** [comment]
@zmd971202 You need to tokenize your sentence using BERT tokenizer, then prepare token's labels according to tokenization result. If you using BERT tokenizer, it will add `[CLS]` token by default. BERTEmbedding will also add the `[CLS]` token by default. so if your data already includes the `[CLS]` token, remember to set `bert_embedding.add_bos_eos` property to False.

**Comment by zmd971202** [comment]
@BrikerMan Thank you for your reply. So using the representation of the first sub-token as the input to the classifier is not implemented in your code and should be implemented by myself. Right?

**Comment by BrikerMan** [comment]
> @BrikerMan Thank you for your reply. So using the representation of the first sub-token as the input to the classifier is not implemented in your code and should be implemented by myself. Right?

It is implemented for BERT, but you could disable this function by setting `add_bos_eos` property of BERT Embedding to False.

**Comment by zmd971202** [comment]
Ok. Thank you very much!
