### ISSUE TITLE
[Question] 需不需要设置do_lower参数？

### ISSUE THREAD

**Issue by aguang1201** [BrikerMan/Kashgari#105]
如果使用cased的BERT模型，需要设置do_lower=False吗？Kashgari工程会根据cased模型来自动设置do_lower=False吗？

**Comment by HaoyuHu** [comment]
目前没有`do_lower`参数，工程不会自动设置。`cased`或者`uncased`需要用户侧维护和预处理。

**Comment by aguang1201** [comment]
谢谢回答
