### ISSUE TITLE
[Question]请问，我们平时训练用的样本量非常大没办法一次load进来，我自己都是用iteration的对象喂给tf的，那用你这个框架针对这种情况应该如何处理？

### ISSUE THREAD

**Issue by KantKatze** [BrikerMan/Kashgari#11]
A clear and concise description of what you want to know.

**Comment by BrikerMan** [comment]
目前是用 fit-generator 去分批次预处理并且丢给模型，所以其实数据量很大也没关系，但是如果数据实在太大，原始的加载到内存都有问题那我可以提供直接分批读取文件的方法~
