### ISSUE TITLE
[BUG] ImportError: cannot import name 'attention_builder'

### ISSUE THREAD

**Issue by gdh756462786** [BrikerMan/Kashgari#111]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.

## Environment

* OS [e.g. Mac OS, Linux]:
* requirements.txt:
```
[Paste requirements.txt file here]
```

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by gdh756462786** [comment]
为什么导入注意力生成器会失败?

**Comment by BrikerMan** [comment]
麻烦按照 issue 模板重新提交 issue，否则没办法处理。

**Comment by tthtlc** [comment]
I solved the problem:   Notice that keras-transformer can come from a few sources:

https://github.com/CyberZHG/keras-transformer  

or

https://github.com/kpot/keras-transformer

The former has the attention_builder but the latter does not have.

I pip uninstall all existing keras-transformer and build the keras-transformer from CyberZHG and this error goes away.

**Comment by BrikerMan** [comment]
@tthtlc Just uninstall all and install the latest version of Kashgari, kashgari 0.2.6 or kashgari-tf 0.5.0 will solve it all.
