### ISSUE TITLE
[Question]  大佬,我刚才提出那个ImportError问题,怎么删掉了?

### ISSUE THREAD

**Issue by gdh756462786** [BrikerMan/Kashgari#112]
A clear and concise description of what you want to know.

**Comment by BrikerMan** [comment]
麻烦按照 issue 模板重新提交 issue，否则没办法处理。
另外，没有删除，关闭了，不符合规范。

#111

**Comment by gdh756462786** [comment]
我仔细看了一下包的路径,应该是from keras_transformer.transformer import *

**Comment by BrikerMan** [comment]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.

## Environment

* OS [e.g. Mac OS, Linux]:
* requirements.txt:
```
[Paste requirements.txt file here]
```

## Issue Description

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by gdh756462786** [comment]
好吧! 格式是很重要
