### ISSUE TITLE
[BUG] 运行customizer own model时，例子程序报错。

### ISSUE THREAD

**Issue by Ted8000** [BrikerMan/Kashgari#126]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.

## Environment

* OS [e.g. Mac OS, Linux]:
* requirements.txt:
```
[Paste requirements.txt file here]
```

### What

[Tell us about the issue]
![image](https://user-images.githubusercontent.com/32102558/60410498-33d1e100-9bfb-11e9-82b5-9955a8c305ce.png)

![image](https://user-images.githubusercontent.com/32102558/60410487-23216b00-9bfb-11e9-974e-35785bca6772.png)

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
忘了更新文档了，按照刚更新的文档再试试。

**Comment by Ted8000** [comment]
3Q
