### ISSUE TITLE
[BUG] tf-version 版本，  evaluation 出错

### ISSUE THREAD

**Issue by Ted8000** [BrikerMan/Kashgari#127]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.

## Environment

* OS [e.g. Mac OS, Linux]:
* requirements.txt:
```
[Paste requirements.txt file here]
```

## Issue Description
![image](https://user-images.githubusercontent.com/32102558/60490544-533f3b80-9cd9-11e9-9a45-5ea92c6e2dc8.png)

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
请提供完整的信息，什么任务，什么模型？

**Comment by Ted8000** [comment]
tf-version,   labeling任务的evaluation可以用，classification的evaluation不能用，classification的模型evaluate都出错。

**Comment by BrikerMan** [comment]
麻烦运行一下以下代码，提供一下版本号。我用测试用例测试是没问题的。

```python
import kashgari
print(kashgari.__version__)
```

**Comment by Ted8000** [comment]
![image](https://user-images.githubusercontent.com/32102558/60559782-24c86b80-9d80-11e9-81db-993cd6e8d1f7.png)

**Comment by BrikerMan** [comment]
那就终端执行 pip freeze 命令看一下全部依赖列表，怀意是 sklearn 版本不一致的问题。

**Comment by Ted8000** [comment]
![image](https://user-images.githubusercontent.com/32102558/60559934-ad470c00-9d80-11e9-800a-9ff0a6f973f1.png)
![image](https://user-images.githubusercontent.com/32102558/60559939-b2a45680-9d80-11e9-8277-7d683486e81e.png)

**Comment by BrikerMan** [comment]
果然是... 这个我加个限制，需要 scikit-learn==0.21.1。
更新一下 scikit-learn

```
pip install scikit-learn==0.21.1
```

**Comment by Ted8000** [comment]
3Q  非常感谢
