### ISSUE TITLE
Import error of Kashgari in paperspace cloud jupyter notebook

### ISSUE THREAD

**Issue by marcusau** [BrikerMan/Kashgari#129]
Hi all, 

    I am using Gradient jupyer notebook: tensorflow 1.5.0 GPU py3 with Machine type : P5000. 

   I used terminal of the jupyter notebook to install  kashgari, there was very smooth in the installation process.

   The issue showed up when importing the kashgari in Gradient Jupyter notebook, and it showed:

  
![image](https://user-images.githubusercontent.com/31444195/60557826-8933fc80-9d79-11e9-9379-94790232526f.png)

   How to fix it?  Thanks a lot.

Marcus

**Comment by BrikerMan** [comment]
Use Python3.6 + with tensorflow 1.13.0+.

**Comment by BrikerMan** [comment]
Maybe you could try colab.

**Comment by marcusau** [comment]
> Maybe you could try colab.

Colab works well but the speed is too slow

**Comment by BrikerMan** [comment]
Colab provides GPU environment, too. Or you could ask `paperspace` to support py3.6, it is not that hard for them.

**Comment by marcusau** [comment]
> Colab provides GPU environment, too. Or you could ask `paperspace` to support py3.6, it is not that hard for them.

Understood. Thanks
