### ISSUE TITLE
[BUG] Can't import kashgari after successful installation 

### ISSUE THREAD

**Issue by MNCTTY** [BrikerMan/Kashgari#131]
After successful installation 
![image](https://user-images.githubusercontent.com/37251686/60676840-94298280-9e88-11e9-8299-61562df1f197.png)
I'm getting this error and in Jupyter, and in python 3.5 in console.
![image](https://user-images.githubusercontent.com/37251686/60676806-7b20d180-9e88-11e9-92b0-5776ae5aed57.png)
I use Linux Ubuntu 16.04.6

I tried to install version, that I have used some time ago, but it throws the same error
Of course, I didn't change anything in original code

**Comment by BrikerMan** [comment]
Kashgari need to use python 3.6+.

Karina <notifications@github.com>于2019年7月4日 周四23:23写道：

**Comment by MNCTTY** [comment]
Ok, thank you,
sorry for bothering
