### ISSUE TITLE
[Question] in ner: how to save model after the training

### ISSUE THREAD

**Issue by liuzh825** [BrikerMan/Kashgari#132]
`    embedding = BERTEmbedding(BERT_MODEL_PATH, MAX_SENTENCE_LENGTH)
    model = BLSTMCRFModel(embedding)
    model.fit(train_x,
              train_y,
              x_validate=validate_x,
              y_validate=validate_y,
              epochs=1,
              batch_size=10)`

after the training, i want to save the model locally

**Comment by BrikerMan** [comment]
```
# save model
model.save('./some-where-some-where/')
```

**Comment by liuzh825** [comment]
then, how to load model

**Comment by BrikerMan** [comment]
> then, how to load model

```

BLSTMCRFModel.load_model('xxxxxx')
```

**Comment by liuzh825** [comment]
thank you
