### ISSUE TITLE
[Question] 不能使用多GPU训练

### ISSUE THREAD

**Issue by Ted8000** [BrikerMan/Kashgari#133]
A clear and concise description of what you want to know.
您好，最近用kashgari这个模型训练，在服务器上调用多GPU一直出现问题，Google很久没找到答案，想请教一下您，这个因该不是框架的问题，GPU调用问题：
![image](https://user-images.githubusercontent.com/32102558/60753555-cbbe3900-a006-11e9-922b-a39e0042fd71.png)

**Comment by BrikerMan** [comment]
似乎出现问题是因为 `keras.utils.multi_gpu_model` 在拼接设备列表时候使用的代码如下

```
target_devices = ['/cpu:0'] + ['/gpu:%d' % i for i in target_gpu_ids]
```

GPU 设备命名为 `gpu:0` `gpu:1`，但是你的 GPU 设备名名称为 `xla_gpu:0` `xla_gpu:1` 所以没找到设备。

**Comment by BrikerMan** [comment]
你可以试试执行以下代码，看看输出是什么。
```python
import tensorflow as tf
from tensorflow.python.client import device_lib
print(device_lib.list_local_devices())
```

**Comment by Ted8000** [comment]
![image](https://user-images.githubusercontent.com/32102558/60753975-1e9aef00-a00d-11e9-970b-9717203b7384.png)

**Comment by BrikerMan** [comment]
这个还真给不出解决方案，不知道你是在什么环境使用的，如果能获取到 `gpu:0` `gpu:1` 等设备列表应该就没问题了。

**Comment by Ted8000** [comment]
tf版本安装的tensorflow 1.14版本，我的cuda是9,这个是GPU不能运行的原因吗？

**Comment by BrikerMan** [comment]
> tf版本安装的tensorflow 1.14版本，我的cuda是9,这个是GPU不能运行的原因吗？

tf版本就是需要 tf 1.14。你安装的是 gpu 版本应该就没问题的...
