### ISSUE TITLE
[Question] 您好，kashgari可以预训练自己的语料库，然后调用这个embedding吗？

### ISSUE THREAD

**Issue by Ted8000** [BrikerMan/Kashgari#134]
A clear and concise description of what you want to know.
针对您之前的一个回答，想问一下，就是如何训练自己的语料库，调用自己的embedding层，可以提供一个例子吗？
![image](https://user-images.githubusercontent.com/32102558/60798224-4f149180-a1a3-11e9-808c-b9b182694849.png)

**Comment by BrikerMan** [comment]
可以先使用 gensim / fasttext 之类的框架训练自己的词向量，然后用 WordEmbedding 模块加载此词向量作为语言模型。

**Comment by Ted8000** [comment]
如何加载gensim 训练好的词向量呢，这个txt是我训练好的。怎么导入到wordembedding
![image](https://user-images.githubusercontent.com/32102558/60808578-3f08ac00-a1bb-11e9-86b4-6378240416dd.png)

**Comment by BrikerMan** [comment]
你是用 tf.keras 版本吧？tf.keras 版本代码如下
```
import kashgari
from kashgari.embedding import WordEmbedding

# 序列标注
em = WordEmbedding('xxx.txt', task=kashgari.LABELING)
# 分类
em = WordEmbedding('xxx.txt', task=kashgari.CLASSIFICATION)
```

以后麻烦不要用图片，直接分别复制代码和错误。这样方便别人检索。

**Comment by Ted8000** [comment]
加了预训练词向量报错，keyerror,不加能运行。
`from kashgari.tasks.classification import CNN_Model, AVCNN_Model
from kashgari.embeddings import WordEmbedding

em = WordEmbedding('w2v.gz', task=kashgari.CLASSIFICATION)
early_stopping = EarlyStopping(monitor='val_loss', patience=5)

model = AVCNN_Model(em)
model.fit(train_x, train_y, test_x, test_y, epochs=20, batch_size=64, fit_kwargs={'callbacks':[early_stopping]})`

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-113-e53fcdad173b> in <module>()
      4 
      5 model = AVCNN_Model(em)
----> 6 model.fit(train_x, train_y, test_x, test_y, epochs=20, batch_size=64, fit_kwargs={'callbacks':[early_stopping]})

~/anaconda3/lib/python3.6/site-packages/kashgari/tasks/base_model.py in fit(self, x_train, y_train, x_validate, y_validate, batch_size, epochs, callbacks, fit_kwargs)
    220         self.build_model(x_train, y_train)
    221         tensor_x = self.embedding.process_x_dataset(x_train)
--> 222         tensor_y = self.embedding.process_y_dataset(y_train)
    223 
    224         validation_data = None

~/anaconda3/lib/python3.6/site-packages/kashgari/embeddings/base_embedding.py in process_y_dataset(self, data, subset)
    187             vectorized feature tensor
    188         """
--> 189         return self.processor.process_y_dataset(data, self.sequence_length, subset)
    190 
    191     def reverse_numerize_label_sequences(self,

~/anaconda3/lib/python3.6/site-packages/kashgari/processors/classification_processor.py in process_y_dataset(self, data, max_len, subset)
     54             return self.multi_label_binarizer.fit_transform(target)
     55         else:
---> 56             numerized_samples = self.numerize_label_sequences(target)
     57             return to_categorical(numerized_samples, len(self.label2idx))
     58 

~/anaconda3/lib/python3.6/site-packages/kashgari/processors/classification_processor.py in numerize_label_sequences(self, sequences)
     79             label-index sequence, list of int
     80         """
---> 81         return [self.label2idx[label] for label in sequences]
     82 
     83     def reverse_numerize_label_sequences(self, sequences, **kwargs):

~/anaconda3/lib/python3.6/site-packages/kashgari/processors/classification_processor.py in <listcomp>(.0)
     79             label-index sequence, list of int
     80         """
---> 81         return [self.label2idx[label] for label in sequences]
     82 
     83     def reverse_numerize_label_sequences(self, sequences, **kwargs):

KeyError: 'telephone'
