### ISSUE TITLE
Tokenization of input sentences for English

### ISSUE THREAD

**Issue by polars05** [BrikerMan/Kashgari#136]
When feeding in sentences, do we need to pre-process them (e.g. using BPE) beforehand? Or do we just split them into words and let GPT-2 / BERT handle the pre-processing? 

Example: If we want to use BERT embedding, do we have to pre-process "Jim Henson was a puppeteer" into ["jim", "henson", "was", "a", "puppet", "##eer"] using some external BPE library or do we just split the sentence on spaces and feed ["jim", "henson", "was", "a", "puppeteer"] into the model?

**Comment by BrikerMan** [comment]
You need to pre-process (tokenize) your sequence with the proper tool for the best performance. For example, if you are using the BERT embedding, use [BERT Tokenizer](https://github.com/google-research/bert/blob/master/tokenization.py) for pre-processing.

If you just split the sentence with spaces and feed ["jim", "henson", "was", "a", "puppeteer"], It will lose some details. It will run thought, but not good as using BERT Tokenizer.

**Comment by polars05** [comment]
It seems that this part of the code already handles the tokenizing of the input sequence using the vocab.txt: https://github.com/BrikerMan/Kashgari/blob/aeb1d783c9e670357f08959bb5a53ff37a13e792/kashgari/embeddings/bert_embedding.py#L87-L98

Can I assume that we can just split the input sentence into ["jim", "henson", "was", "a", "puppeteer"] instead of ["jim", "henson", "was", "a", "puppet", "##eer"] before fitting it on a classifier built upon kashgari.embeddings.BERTEmbedding?

**Comment by BrikerMan** [comment]
Nope, We read the BERT vocab for token numerize process. It converts tokens to token-index number array. It handles the numerize process, not the tokenize process. 
You can just split sentence by space, but you will get a little bit accurate feature representation when you tokenize it.

**Comment by polars05** [comment]
Ahh, thanks for the clarification! :) Guess would be helpful to state this in the documentation / include the tokenization process as part of the kashgari library

**Comment by BrikerMan** [comment]
Yes, I should add those details. Maybe you could help me with the documents.

**Comment by polars05** [comment]
In the documentation (under "**Quick Start**") for the tf.keras branch, I added an example for pre-processing of text before feeding into BERT for text classification; I noticed kashgari builds off bert-keras so I've crafted the example based on the tokenizer from bert-keras.

I've created a pull request for that; hope the example helps with your documentation!

Side note: not sure if you have to set self.processor.add_bos_eos to False since the tokenizer will already automatically include the [CLS] and [SEP] tokens
https://github.com/BrikerMan/Kashgari/blob/aeb1d783c9e670357f08959bb5a53ff37a13e792/kashgari/embeddings/bert_embedding.py#L80

**Comment by BrikerMan** [comment]
> In the documentation (under "**Quick Start**") for the tf.keras branch, I added an example for pre-processing of text before feeding into BERT for text classification; I noticed kashgari builds off bert-keras so I've crafted the example based on the tokenizer from bert-keras.
> 
> I've created a pull request for that; hope the example helps with your documentation!
> 
> Side note: not sure if you have to set self.processor.add_bos_eos to False since the tokenizer will already automatically include the [CLS] and [SEP] tokens
> https://github.com/BrikerMan/Kashgari/blob/aeb1d783c9e670357f08959bb5a53ff37a13e792/kashgari/embeddings/bert_embedding.py#L80

Yes, if sequence includes the [CLS] and [SEP] tokens, we need to set add_bos_eos to False.

**Comment by BrikerMan** [comment]
@polars05 Added to the new document, check it out. https://kashgari.bmio.net/embeddings/bert-embedding/

**Comment by BrikerMan** [comment]
Added tokenizer property to the BERTEmebdding, simplified the process. Here is the [document](https://kashgari.bmio.net/embeddings/bert-embedding/#example-usage-text-classification)
