### ISSUE TITLE
[BUG] 模型保存，再读取错误。

### ISSUE THREAD

**Issue by Ted8000** [BrikerMan/Kashgari#137]
import kashgari
model_slots = kashgari.utils.load_model('slots.h5')
路径就在此目录。找不到文件

`OSError                                   Traceback (most recent call last)
<ipython-input-5-b2d4d89b49a4> in <module>()
      1 import kashgari
----> 2 model_slots = kashgari.utils.load_model('slots.h5')

~/anaconda3/lib/python3.6/site-packages/kashgari/utils.py in load_model(model_path, load_weights)
     53     model.tf_model = tf.keras.models.model_from_json(model_json_str, custom_objects)
     54     if load_weights:
---> 55         model.tf_model.load_weights(os.path.join(model_path, 'model_weights.h5'))
     56 
     57     embed_info = model_info['embedding']

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py in load_weights(self, filepath, by_name)
    160         raise ValueError('Load weights is not yet supported with TPUStrategy '
    161                          'with steps_per_run greater than 1.')
--> 162     return super(Model, self).load_weights(filepath, by_name)
    163 
    164   @trackable.no_automatic_dependency_tracking

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/network.py in load_weights(self, filepath, by_name)
   1410           'first, then load the weights.')
   1411     self._assert_weights_created()
-> 1412     with h5py.File(filepath, 'r') as f:
   1413       if 'layer_names' not in f.attrs and 'model_weights' in f:
   1414         f = f['model_weights']

~/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py in __init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, **kwds)
    392                 fid = make_fid(name, mode, userblock_size,
    393                                fapl, fcpl=make_fcpl(track_order=track_order),
--> 394                                swmr=swmr)
    395 
    396             if swmr_support:

~/anaconda3/lib/python3.6/site-packages/h5py/_hl/files.py in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    168         if swmr and swmr_support:
    169             flags |= h5f.ACC_SWMR_READ
--> 170         fid = h5f.open(name, flags, fapl=fapl)
    171     elif mode == 'r+':
    172         fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper()

h5py/h5f.pyx in h5py.h5f.open()

OSError: Unable to open file (unable to open file: name = 'slots.h5/model_weights.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)`

**Comment by BrikerMan** [comment]
这个是 tf.keras 版本更新时候修改引起的。把保存好的模型  `model.h5` 更名为 `model_weights.h5` 再读取即可。

**Comment by Ted8000** [comment]
fixed~3Q
