### ISSUE TITLE
Please, add a simple example for sequence labeling

### ISSUE THREAD

**Issue by ehsanasgarian** [BrikerMan/Kashgari#14]
Your description in "../docs/Tutorial_3_Sequence_Labeling.md" isn't enough.

**Comment by wifeofMikeAngelo** [comment]
Although it is in Chinese, the code should be helpful.
https://eliyar.biz/nlp_chinese_bert_ner/

**Comment by BrikerMan** [comment]
Done, [text_labeling_model tutorial](https://kashgari.readthedocs.io/en/latest/md/text_labeling_model.html)
