### ISSUE TITLE
Customize your own model tutorial doesn't work as it released 

### ISSUE THREAD

**Issue by MNCTTY** [BrikerMan/Kashgari#141]
Hi! I try to build my own model following your tutorial https://kashgari.readthedocs.io/en/tf.keras-version/tutorial/sequence_labeling_model.html
and I've met some problems. For example, import problems

![image](https://user-images.githubusercontent.com/37251686/61040802-02ff6200-a3da-11e9-8b95-b7997e5e1e7f.png)

I looked at the source code, and there is actually no L in layers. What did you mean by that?
Plus, I don't understand, why BaseLabelingModel is not importing at all - from any path, and from just tasks, and from tasks.labelling
Can you help me a bit?

**Comment by BrikerMan** [comment]
Yep, this is a version issue. This tutorial is actually for the tf.keras version `kashgari-tf`. I guess you are using the keras version. Just re-install the kashgari.

```bash
pip uninstall kashgari
pip install kashgari-tf
```

**Comment by MNCTTY** [comment]
thank you! it helps
