### ISSUE TITLE
Unknown error that didn't arise before in this code

### ISSUE THREAD

**Issue by MNCTTY** [BrikerMan/Kashgari#142]
Hi
I reinstalled the Kashgari lib, as you said in our previous issue, but! the code, that I didn't rewrite start to fall down with errors. For example:

![image](https://user-images.githubusercontent.com/37251686/61089536-1cd58f00-a444-11e9-812d-07110e9280ac.png)

But the most weird is that:
![image](https://user-images.githubusercontent.com/37251686/61089609-5c03e000-a444-11e9-8d0b-5b7212ad385d.png)

Can you advise me something about that?

**Comment by MNCTTY** [comment]
The same error with standart bert multilingual embedding

**Comment by MNCTTY** [comment]
Also, may be you can help with offtop question. I defined my own class of model by tutorial, but it gives me an error I didn't understand in this context. What should I to change?

Error:
![image](https://user-images.githubusercontent.com/37251686/61090266-9bcbc700-a446-11e9-8aee-d8d0d985a09f.png)


Class:
![image](https://user-images.githubusercontent.com/37251686/61090299-bdc54980-a446-11e9-92a4-e0eebe90dd76.png)

![image](https://user-images.githubusercontent.com/37251686/61090322-cf0e5600-a446-11e9-8fb0-f96ab5fd7520.png)

**Comment by BrikerMan** [comment]
It seems like a bug. Let me check. One me thing. Please paste the code and error info as markdown text instead of the image. It is much readable and will help others when they have same issue.

**Comment by BrikerMan** [comment]
kashgari-tf no longer provide the `init_logger` function. Remove that line and add your own logger for logs will fix this issue.

```python
import logging
logging.basicConfig(level='DEBUG')
```

**Comment by BrikerMan** [comment]
For your second question. It is because there is a small typo at your code.

```python
# here is a comma at the end, this will make layer_lstm a tuple, not a object
layer_lstm = L.LSTM(**config['layer_lstm']),

# change it to will fix
layer_lstm = L.LSTM(**config['layer_lstm'])
```
