### ISSUE TITLE
[Feature request] Getting probabilities of predictions from model

### ISSUE THREAD

**Issue by polars05** [BrikerMan/Kashgari#146]
In tf.keras, running _**model.predict(<test_sentences>)**_ would produce a matrix of [num_sentences x num_classes]; however, in kashgari, **_model.predict(<test_sentences>)_** gives only the most probable class. Is there a way to extract the probabilities of each class?

**Comment by BrikerMan** [comment]
In the current version, you will have to do it manually, but it is a nice idea to return probabilities.

This is how you can do it now.

```python
tensor = model.embedding.process_x_dataset(x_list)
pred = model.tf_model.predict(tensor)
new_results = []
for sample_prob in pred:
    sample_res = zip(model.embedding.processor.label2idx.keys(), sample_prob)
    sample_res = sorted(sample_res, key=lambda k: k[1], reverse=True)
    new_results.append(sample_res)

print(new_results)
```

**Comment by polars05** [comment]
@BrikerMan, that works nicely, thanks!

**Comment by BrikerMan** [comment]
Maybe we should figure out one way to build-in this feature, like return top-k class with probabilities.

**Comment by hwq458362228** [comment]
同问
