### ISSUE TITLE
[Question] TPU support for BERT

### ISSUE THREAD

**Issue by ahmednasserswe** [BrikerMan/Kashgari#15]
Hi there,
I am running a classification problem using BERT embedding on Colab. How can I make Kashgare support TPU?
Thanks!

**Comment by alexwwang** [comment]
You may check if keras with tf as backend support TPU which I think is able to. 
But I am afraid this support has not be considered yet. 
However you are encouraged to make a solution by adding some codes as a configuration. I saw the author has begun some work on this in dev branch.

**Comment by BrikerMan** [comment]
Maybe this will help you out, https://www.dlology.com/blog/how-to-train-keras-model-x20-times-faster-with-tpu-for-free/

**Comment by BrikerMan** [comment]
We are working on a tf.keras version, which supports TPU training. It is at an early stage. Here is a [demo colab notebook](https://colab.research.google.com/drive/1UMa5n28cT8eIiKCHaxG5U4zi8_evAPQK) .
