### ISSUE TITLE
[BUG] AttributeError: 'tuple' object has no attribute 'layer'

### ISSUE THREAD

**Issue by mahdisnapp** [BrikerMan/Kashgari#152]
first of all thanks for your impressive work and effort. I faced a problem when using your package in google colab. while I want to use bert embedding with this command:
bert_embedding = BERTEmbedding(bert_model_path, 
                               task=kashgari.CLASSIFICATION,
                               sequence_length=128)
I got this error:
AttributeError: 'tuple' object has no attribute 'layer'
thanks in advance for your help.

**Comment by BrikerMan** [comment]
Are you working on a multi-label classification task? I might there is a small issue in the documents.

**Comment by BrikerMan** [comment]
Long story short, if you import keras_bert from setting the environment variable, it will cause this issue. You can fix it by importing `Kashgari` at the top or add the two lines at the top. Basicly, remember to import kashgari first.

```python
import os
os.environ['TF_KERAS'] = '1'
```

**Comment by mahdisnapp** [comment]
thanks for response, to answer your question, I am working on multi-class classification not multi-label classification,
base on your suggestion I will import kashgari first then import keras_bert and let you know if it is fixed.
Important note: I want to use tokenizer from keras_bert.
again thanks .

**Comment by BrikerMan** [comment]
I am working on to make it easier to access the keras_bert tokenizer. Will release 5.0.1 today. Check out this commit https://github.com/BrikerMan/Kashgari/commit/22ad76f95d1316d9c433f31b9ead1ee20aa938e9

**Comment by mahdisnapp** [comment]
thanks for your help, problem has been solved. I noticed a note in your tutorial for BERT embeddings, you tokenized sentences with BERT tokenizer but did not pass them into your neural net model, you just feed the raw text as input data.
`tokenizer = Tokenizer(token_dict)
sentences_tokenized = []
for sentence in sentences:
  sentence_tokenized = tokenizer.tokenize(sentence)
  sentences_tokenized.append(sentence_tokenized)`

but then 
`train_x, train_y = sentences[:2], labels[:2]
validate_x, validate_y = sentences[2:], labels[2:]`

**Comment by BrikerMan** [comment]
Fixed the type and released the 0.5.1 version, it is much easier to use BERT tokenizer. Check it out, [document](https://kashgari.bmio.net/embeddings/bert-embedding/#example-usage-text-classification)

**Comment by mahdisnapp** [comment]
dear BrikerMan 
now we have other main error, after update, we got this error
`tokenizer = bert_embed.tokenizer
`
'BERTEmbedding' object has no attribute 'tokenizer'

**Comment by BrikerMan** [comment]
You have updated to 0.5.1 version?

mahdisnapp <notifications@github.com>于2019年7月15日 周一19:42写道：

**Comment by mahdisnapp** [comment]
yes I updated my kashgari just while you informed me.

**Comment by BrikerMan** [comment]
I just tried and it works. Please make sure you have imported the latest version if you started a kernel like jupyter before updating, it will require a kernel restart to import latest version. You can confirm by

```
print(kashgari.__version__)
```

Here is my demo: [colab link](https://colab.research.google.com/drive/1ocGu-dV3YaLBIwzEFyhuF51PFbY6CpdN)

**Comment by mahdisnapp** [comment]
errors have been solved, thank you again.

**Comment by mahdisnapp** [comment]
dear BrikerMan,
your packages worked well and I have developed my models with success until the error occurred today, 
when I tried to fit model I got this error:
`mdel.fit(x_train, y_train, x_validate, y_validate, epochs = 5, batch_size = 32)`  

Keras: operands could not be broadcast together with shapes

**Comment by BrikerMan** [comment]
> dear BrikerMan,
> your packages worked well and I have developed my models with success until the error occurred today,
> when I tried to fit model I got this error:
> `mdel.fit(x_train, y_train, x_validate, y_validate, epochs = 5, batch_size = 32)`
> 
> Keras: operands could not be broadcast together with shapes

I need a little bit more details with this bug. Please provide the model config and data samples.

**Comment by mahdisnapp** [comment]
I used BiLSTM model from **kashgari.tasks.classification**, my input data (x_train and x_validate) are tokenized texts and outpus (y_train, y_validate) are labels,
note : i used BERTEmbedding and it's tokenization method
my training size is 450 and validate size is 50

**Comment by BrikerMan** [comment]
Maybe you could provide the code, how you build the model, and sample data. Or just give me a colab notebook which could reproduce the issue.

**Comment by mahdisnapp** [comment]
ValueError                                Traceback (most recent call last)
<ipython-input-51-c4b348118dd6> in <module>()
----> 1 av_rnn.fit(x_train, y_train, x_test, y_test, epochs = 5, batch_size = 32)

1 frames
/usr/local/lib/python3.6/dist-packages/kashgari/tasks/base_model.py in fit(self, x_train, y_train, x_validate, y_validate, batch_size, epochs, callbacks, fit_kwargs)
    263 
    264         """
--> 265         self.build_model(x_train, y_train, x_validate, y_validate)
    266         train_generator = self.get_data_generator(x_train,
    267                                                   y_train,

/usr/local/lib/python3.6/dist-packages/kashgari/tasks/base_model.py in build_model(self, x_train, y_train, x_validate, y_validate)
    115 
    116         if x_validate is not None and not isinstance(x_validate, tuple):
--> 117             self.embedding.analyze_corpus(x_train + x_validate, y_train + y_validate)
    118         else:
    119             self.embedding.analyze_corpus(x_train, y_train)

ValueError: operands could not be broadcast together with shapes (450,) (50,)

**Comment by BrikerMan** [comment]
It seems the issue with data, please run this code.

```
print(x_train[0])
print(x_validate[0])
print(y_train[0])
print(y_validate[0])
```

**Comment by mahdisnapp** [comment]
there were no problem with shape of training and validation sets, I provide link to my colab
[colab](https://colab.research.google.com/drive/18pfeefvRvUx_J1olh8ZnO3ikNoqwO197)

**Comment by BrikerMan** [comment]
> there were no problem with shape of training and validation sets, I provide link to my colab
> [colab](https://colab.research.google.com/drive/18pfeefvRvUx_J1olh8ZnO3ikNoqwO197)

I might know the issue, try to convert data to list rather than np.array.

```
mdel.fit(list(x_train), list(y_train), list(x_validate),list(y_validate), epochs = 5, batch_size = 32)
```

**Comment by mahdisnapp** [comment]
yes your solution worked, may I ask what is the reason the model did not support numpy array as an input?
again thanks for your patience and kindness to help us.

**Comment by BrikerMan** [comment]
I need to add all your corpus together to build token dict and label dict. So here is one important line https://github.com/BrikerMan/Kashgari/blob/63f0991b0d46599b16a83abe64123b5cc7a5a35e/kashgari/tasks/base_model.py#L117

But when you add to numpy array, they should have to be [able to broadcast](https://docs.scipy.org/doc/numpy-1.10.4/user/basics.broadcasting.html)

I have tried mainly on my build in corpus and haven't tested on numpy array input. So, this is a bug and will fix in the next version by converting `x_train` and `x_validate ` to list before adding them.

**Comment by BrikerMan** [comment]
@mahdisnapp Maybe you guys could help me write some blog about how you use Kashgari~ That means a lot. I hope more people know about this project.

**Comment by mahdisnapp** [comment]
Dear BrikerMan 
your work is very impressive and I want to help you to improve kashgari performance and add new features to it. at the moment I could help with bugs or add other models. if you need help just let me know. and if you want I could mail you for further talks

**Comment by BrikerMan** [comment]
> Dear BrikerMan
> your work is very impressive and I want to help you to improve kashgari performance and add new features to it. at the moment I could help with bugs or add other models. if you need help just let me know. and if you want I could mail you for further talks

Let's start with fixing bugs and documents, also feel free to add new features and create pull request. here is the [contributing guide](https://kashgari.bmio.net/about/contributing/).

**Comment by alexwwang** [comment]
This may be a bug induced by tf.keras. In tf.keras, they haven’t done type
check or explicit conversion from other types to list in some method
implementations.
