### ISSUE TITLE
[Question] Does BERTEmbedding work for a sentence pair as well ?

### ISSUE THREAD

**Issue by armadillowithsunglasses** [BrikerMan/Kashgari#155]
(I apologise incase this question has already been answered before, I was not able to find it anywhere )

I am working with sentence pairs in my dataset. I am trying to calculate their BERTEmbeddings and a few other numerical features to use to StackEmbedding definition to build my model. 

I wanted to know if the BERTEmbeddings function works with a pair of sentences similar to what [Bert-as-service provides [( for sentence pairs [First do it , then do it right] --> bc.encode(['First do it ||| then do it right']) )](https://github.com/hanxiao/bert-as-service#3-use-client-to-get-sentence-encodes)
Also Thank you for making this amazing repo :D

**Comment by BrikerMan** [comment]
You can use the sentence pair, let's assume your input pair is `"First do it" "then do it right"`

Tokenize your sentence using the bert-tokenizer, [here is the example](https://kashgari.bmio.net/embeddings/bert-embedding/#example-usage-text-classification).

Then 

```
sentence1 = ['First', 'do', 'it']
sentence2 = ['then', 'do', 'it', 'right']

sample = sentence1 + ["[SEP]"] + sentence2
# ['First', 'do', 'it', '[SEP]', 'then', 'do', 'it', 'right']

x = [sample]
```

**Comment by armadillowithsunglasses** [comment]
as a follow up question, 

when I tried to implement this using the tokeniser given in the example I got the following output 
`sentence 1: I have a large amount of data `
and `sentence 2: In the end, he reflects on why we need stories so badly.`
gives 
```
['[CLS]', 'i', 'have', 'a', 'large', 'amount', 'of', 'data', '[SEP]', '[SEP]', '[CLS]', 'in', 'the', 'end', ',', 'he', 'reflects', 'on', 'why', 'we', 'need', 'stories', 'so', 'badly', '.', '[SEP]']
```

As the BERT tokeniser by default adds a [SEP] at the end of ever single sentence when used. I think the simple solution to this problem would be to just suggest using 
sample = sentence1 + sentence2   instead ?

**Comment by BrikerMan** [comment]
> as a follow up question,
> 
> when I tried to implement this using the tokeniser given in the example I got the following output
> `sentence 1: I have a large amount of data `
> and `sentence 2: In the end, he reflects on why we need stories so badly.`
> gives
> 
> ```
> ['[CLS]', 'i', 'have', 'a', 'large', 'amount', 'of', 'data', '[SEP]', '[SEP]', '[CLS]', 'in', 'the', 'end', ',', 'he', 'reflects', 'on', 'why', 'we', 'need', 'stories', 'so', 'badly', '.', '[SEP]']
> ```
> 
> As the BERT tokeniser by default adds a [SEP] at the end of ever single sentence when used. I think the simple solution to this problem would be to just suggest using
> sample = sentence1 + sentence2 instead ?

I forgot that BERT tokenizer add `[SEP]` tokens. Maybe you can tokenize first, then

```python
pair = sen1[:-1] + ['[SEP]'] + sen2[1:]
```

Just make sure your final result is, you can do it in your way.

```
['[CLS]', 'i', 'have', 'a', 'large', 'amount', 'of', 'data', '[SEP]', 'in', 'the', 'end', ',', 'he', 'reflects', 'on', 'why', 'we', 'need', 'stories', 'so', 'badly', '.', '[SEP]']
```
