### ISSUE TITLE
[Question] Integrating BERTEmbedding into stackEmbedding

### ISSUE THREAD

**Issue by armadillowithsunglasses** [BrikerMan/Kashgari#157]
I am trying to use BERTEmbedding in place of BareEmbedding while doing StackEmbedding.
Like the example given in the documentation, I am following the same steps in the repo and only replacing the text with tokenised versions of the text and including BERT. 
```
#DATASET

text = [['[CLS]', "'", 'nl', '##p', "'", '[SEP]'], ['[CLS]', "'", 'projects', "'", '[SEP]'], ['[CLS]', "'", 'project', "'", '[SEP]'], ['[CLS]', "'", 'name', "'", '[SEP]'], ['[CLS]', "'", ':', "'", '[SEP]']]
start_of_p = [1, 2, 1, 2, 2]
bold = [1, 1, 1, 1, 2]
center = [1, 1, 2, 2, 2]
label = ['B-Category', 'I-Category', 'B-Project-name', 'I-Project-name', 'I-Project-name']

text_list = [text] * 100
start_of_p_list = [start_of_p] * 100
bold_list = [bold] * 100
center_list = [center] * 100
label_list = [label] * 100

```
but when I do this `print(stack_embedding.embed(x))`

I am getting the following error 
`TypeError: unhashable type: 'list'`

(As I am new to this, the solve for this might be obvious, thank you in advance )

**Comment by BrikerMan** [comment]
Here is the issue, `text_list` should be a list of samples, but in your case `text_list = [text] * 100` makes it a list of sample lists. So you get this error.

Make sure text_list is a 2D array, not 3D.
