### ISSUE TITLE
[Question] Regarding sequence length value for numerical features

### ISSUE THREAD

**Issue by armadillowithsunglasses** [BrikerMan/Kashgari#158]
I am trying to modify the example given in documentation for stacking numerical features. I have a large amount of data and so I am using pandas to read the file before using the code.
(https://kashgari.bmio.net/advance-use/handle-numeric-features/)
here is a few lines of my code (not in sequence)
```
train_df = pd.read_csv(TRAIN_CSV)
train_df.head()

bert_embedding = BERTEmbedding(bert_model_path,
                               task=kashgari.LABELING,
                               sequence_length=10)

tokenizer = bert_embedding.tokenizer
sentences_tokenized = []
for sentence in train_df['text'].values:
    sentence_tokenized = tokenizer.tokenize(sentence)
    sentences_tokenized.append(sentence_tokenized)

tokenized_text_list = sentences_tokenized
start_of_p_list = [list(train_df['start_of_p'])]*1
bold_list = [list(train_df['bold'])]*1
center_list = [list(train_df['center'])]*1
label_list = [list(train_df['label'])]*1
```
I noticed that the sequence length for the numerical features had been set to 100 after creating a list of 100 of each of the features. I wanted to know if there was any specific reason for doing so ? 

The tokenzied text can obviously have a large length like 100 but why isnt the sequence length for numerical features being set to 1 ? moreover i noticed that setting the length to 1 gives the following error `IndexError: index 1 is out of bounds for axis 0 with size 1` when `print(stack_embedding.embed(x))` is run.

I have asked a lot of questions before but I must reiterate how thankful I am for all the help !

**Comment by BrikerMan** [comment]
1. For now, all sequence length must be equal for embedding layers in a stacked embedding, that's because we have to concatenate their output together for classification/labeling task.

https://github.com/BrikerMan/Kashgari/blob/63f0991b0d46599b16a83abe64123b5cc7a5a35e/kashgari/embeddings/stacked_embedding.py#L78

When concatenating tensors, they must share two equal dimensions, we choose the batch_size + sequence_length. So embedding layers must have sequence_length but could have different embedding_size. 

Our data from the embedding layer will be in this shape 

```
[batch_size, sequence_length, embedding_size]
```

When concatenating using current way, your result will be 

```
[batch_size, sequence_length, embedding_size1 + embedding_size2+ embedding_size3]
```

We choose to use sequence length because we need to use those stacked embedding for both labeling and classification. Only in this case, we could keep the original input sequence length for further tasks.

If we use different sequence length, then we have to keep the same output shape for feature embedding layers, and this will change embedded tensor's sequence_length. Which may cause lots of problems.

**Comment by alexwwang** [comment]
Indeed as what @brikerman explained.
Maybe we should allow users to choose the axis on which they want to
concatenate different embedding feature vectors or matrix.

**Comment by alexwwang** [comment]
Update:
Not necessary to do what I suggested above. You may just transfer your
numerical feature matrix, say which shape is (batch_size, feature_size), to
a matrix with 3 dimensions, which shape is (batch_size, sequence _length,
feature_size), just fill (batch_size, sequence _length-1, feature_size) of
it with zero.

**Comment by armadillowithsunglasses** [comment]
Aaah I see . Thank you so much for clarifying 💯 

As a follow up question,  I am now running the code with the same sequence length for all the features and the embedding. My embedding is running while training but I am still getting an index out of bounds with axis error. 

My code looks like this after modifying (these are just the parts with sequence length involved)
```
#SEQUENCE LENGTH 
SEQUENCE_LEN = 100
#BERT MODEL 

bert_model_path= '/Users/ishitagupta/bert/uncased_L-12_H-768_A-12'
bert_embedding = BERTEmbedding(bert_model_path,
                               task=kashgari.LABELING,
                               sequence_length=SEQUENCE_LEN)
tokenizer = bert_embedding.tokenizer

feature1_embedding = NumericFeaturesEmbedding(feature_count=1000,
                                                feature_name='feature1',
                                                sequence_length=SEQUENCE_LEN)

feature2_embedding = NumericFeaturesEmbedding(feature_count=1000,
                                                feature_name='feature2',
                                                sequence_length=SEQUENCE_LEN)

feature3_embedding = NumericFeaturesEmbedding(feature_count=1000,
                                                feature_name='feature3',
                                                sequence_length=SEQUENCE_LEN)
tokenized_text_list_train = sentences_tokenized_train

feature1_list_train = [list(train_df['feature1'])]*SEQUENCE_LEN
feature2_list_train = [list(train_df['feature2'])]*SEQUENCE_LEN
feature3_list_train = [list(train_df['feature3'])]*SEQUENCE_LEN
label_list_train = [list(train_df['label'])]*SEQUENCE_LEN
```

So my understanding is that since I have made the embedding and the features into the same length list, I should not get an index out of bounds with axis error. 
But when I run `print(stack_embedding.embed(train_x))` I am getting the following error 
`IndexError: index 100 is out of bounds for axis 0 with size 100`
