### ISSUE TITLE
[BUG] IndexError: list index out of range on line 197 in tasks.classification.base_model.py

### ISSUE THREAD

**Issue by alexwwang** [BrikerMan/Kashgari#16]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ * ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.

## Environment

* OS [e.g. Mac OS, Linux]: Ubuntu 16.04
* requirements.txt:
```
absl-py==0.7.0
art==3.0
astor==0.7.1
atomicwrites==1.3.0
attrs==18.2.0
boto==2.49.0
boto3==1.9.91
botocore==1.12.91
bz2file==0.98
certifi==2018.1.18
chardet==3.0.4
codecov==2.0.15
colorlog==4.0.2
coverage==4.5.2
docutils==0.14
download==0.3.3
gast==0.2.2
gensim==3.7.1
grpcio==1.18.0
h5py==2.9.0
idna==2.8
jieba==0.39
jmespath==0.9.3
kashgari==0.1.6
Keras==2.2.4
Keras-Applications==1.0.7
keras-bert==0.29.0
keras-embed-sim==0.2.0
keras-layer-normalization==0.9.0
keras-multi-head==0.15.0
keras-pos-embd==0.7.0
keras-position-wise-feed-forward==0.3.0
Keras-Preprocessing==1.0.9
keras-self-attention==0.33.0
keras-transformer==0.17.0
Markdown==3.0.1
more-itertools==6.0.0
numpy==1.16.1
pandas==0.24.1
pluggy==0.8.1
protobuf==3.6.1
py==1.7.0
pycm==1.8
pytest==4.2.1
pytest-cov==2.6.1
python-dateutil==2.8.0
pytz==2018.9
PyYAML==3.13
regex==2019.2.18
requests==2.21.0
s3transfer==0.2.0
scikit-learn==0.20.2
scipy==1.2.1
seqeval==0.0.5
six==1.12.0
sklearn==0.0
smart-open==1.8.0
tensorboard==1.12.2
tensorflow==1.12.0
termcolor==1.1.0
tqdm==4.31.1
urllib3==1.24.1
Werkzeug==0.14.1
xlrd==1.2.0
```

### What
```
  File "$InstalledPath/kashgari/tasks/classification/base_model.py", line 244, in predict
    results.append(self._format_output_dict(words_list[index], res[index]))
  File "$InstalledPath/kashgari/tasks/classification/base_model.py", line 197, in _format_output_dict
    'class': candidates[0],
IndexError: list index out of range
```
After the model is trained, you may want to make some prediction, so in `model.predict` method, if you set the param `output_dict=True` you may get this error occur in private method `_format_output_dict` of class `tasks.classification.base_model`.

### Reproduce

As is described above, if you want to output the prob dict of predicted value, this error occurs.

### Other Comment

Haven't figured out why this may happen yet, but seems the var `candidates` goes wrong.

**Comment by BrikerMan** [comment]
I think this problem caused by the candidate filter logic, I filtered all the class which confidence is lower than 0.1, If all of your classes confidence is lower than 0.1, there will be nothing left in the `candidates` list.
https://github.com/BrikerMan/Kashgari/blob/a94b7ab5e5e0a7b2a0e2b73a5393699013859f61/kashgari/tasks/classification/base_model.py#L190
I will remove the filter to fix this.

**Comment by BrikerMan** [comment]
Please try with this version, if it works fine, I will release it to Pypi later, thanks for your feedback.
```bash
pip install git+https://github.com/BrikerMan/Kashgari.git@develop
```

**Comment by alexwwang** [comment]
> I think this problem caused by the candidate filter logic, I filtered all the class which confidence is lower than 0.1, If all of your classes confidence is lower than 0.1, there will be nothing left in the `candidates` list.
> [Kashgari/kashgari/tasks/classification/base_model.py](https://github.com/BrikerMan/Kashgari/blob/a94b7ab5e5e0a7b2a0e2b73a5393699013859f61/kashgari/tasks/classification/base_model.py#L190)
> 
> Line 190 in [a94b7ab](/BrikerMan/Kashgari/commit/a94b7ab5e5e0a7b2a0e2b73a5393699013859f61)
> 
>  if float(result[1]) > 0.01: 
> 
> I will remove the filter to fix this.

I guess this would happen because you use "sigmoid" as the default activation layer function.
I am trying to use "softmax" as the activation layer function and make the test now.
As for softmax, it would have little chance for the normalized prob to be less than 0.1 with less than and equal to 10 classes.
When I get the result I will feed back.

**Comment by alexwwang** [comment]
> Please try with this version, if it works fine, I will release it to Pypi later, thanks for your feedback.
> 
> ```shell
> pip install git+https://github.com/BrikerMan/Kashgari.git@develop
> ```

Ok. I'll check it first.
Maybe I could hack it directly locally.

**Comment by BrikerMan** [comment]
Thanks, and let me know how you change the `sigmoid` to `softmax`.
One of the main intents of the Kashagri is easy-to-customize. I should provide an effortless and straightforward way to do this.

**Comment by alexwwang** [comment]
It's easy.
I simply add a key-value pair in `_base_hyper_parameters__`  dict with key as `activation_layer` and then pass `**self.hyper_parameters['activation_layer']` to the last `Dense` layer in `build_model` method.
After this modification, I can simply put them in hyper_parameters when initialize the model object as you designed before.

**Comment by alexwwang** [comment]
Indeed, after I changed the type of activation layer of model from `sigmoid` to `softmax`, this error disappeared.

**Comment by BrikerMan** [comment]
Is the develop branch version works with `sigmoid`?

**Comment by alexwwang** [comment]
Haven't try yet. Give me some time please. I only have cpu cores.

**Comment by alexwwang** [comment]
A run-away topic:
During the installation of kashgari dev branch, pip warned me that I have keras-bert 0.29.0 installed, which is incompatible with kashgari 0.1.7, but I checked and assured that keras-bert 0.29.0 was upgraded during the installation of kashgari dev.

**Comment by BrikerMan** [comment]
Take your time, tomorrow is totally fine.
I think I need to update `keras-bert` version end run the tests. I will do finish this tomorrow~

**Comment by alexwwang** [comment]
> Is the develop branch version works with `sigmoid`?

Test passed. It's ok with the dev branch, no error of this kind occurred.

**Comment by alexwwang** [comment]
> Take your time, tomorrow is totally fine.
> `keras-bert` warning is because I specified `keras-bert` version in the requirements.txt file but not in `setup.py` file. Already fixed.

It seems keras-bert 0.29.0 works well with kashgari 0.1.7 dev in my test.
So why keras-bert's version is restricted to 0.25.0?

**Comment by BrikerMan** [comment]
> > Take your time, tomorrow is totally fine.
> > `keras-bert` warning is because I specified `keras-bert` version in the requirements.txt file but not in `setup.py` file. Already fixed.
> 
> It seems keras-bert 0.29.0 works well with kashgari 0.1.7 dev in my test.
> So why keras-bert's version is restricted to 0.25.0?

I restricted to the 0.25.0 because I haven't reviewed and test the changes in `keras-bert`. I will update to the latest version after I checked `keras-bert` changes and test all the models~
