### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'shape' 

### ISSUE THREAD

**Issue by ALittle-Eve** [BrikerMan/Kashgari#163]
跑https://eliyar.biz/nlp_chinese_bert_ner/ 这个里面的代码时候报的错误，去掉bertembedding以后是可以训练的，谢谢

**Comment by BrikerMan** [comment]
应该是先引入了 keras_bert，再引入 kashgari 引起的，最简单的解决方案，把 import kashgari 放在最前面执行，然后再执行后续代码。

**Comment by ALittle-Eve** [comment]
我在我的代码把 import kashgari 放到最前面了似乎还是有问题，是要修改 kashgari 里面的源码么

**Comment by BrikerMan** [comment]
这个是因为 kashgari 用了 tf.keras, 但是你的环境里面先引入了 keras 版本的 BERT。把 `import kashgari` 放在顶部，然后重启 notebook，再开始执行即可。之前执行过代码，再把 `import kashgari`  放到顶部不管用。

**Comment by ALittle-Eve** [comment]
我用的是py直接跑的，不是notebook

**Comment by BrikerMan** [comment]
可以的话提供一下能够重现问题的代码，谢谢。

**Comment by ALittle-Eve** [comment]
![image](https://user-images.githubusercontent.com/6859730/61431737-1aea5f00-a961-11e9-9bcd-03a93621d591.png)
奇怪的是，用CPU跑就可以正常。谢谢

**Comment by BrikerMan** [comment]
这个文件有引用别的文件么，还是直接从这个开始？

**Comment by ALittle-Eve** [comment]
直接从这里开始的，就是跑了一下博客里面的demo，后面还有两句：model = BiLSTM_CRF_Model(embedding)
model.fit(train_x,
          train_y,
          x_validate=valid_x,
          y_validate=valid_y,
          epochs=20,
          batch_size=512)

**Comment by BrikerMan** [comment]
奇怪了，我在 colab GPU 环境调用 BERT Embedding 没问题。之前我自己遇到过这个问题，是因为我先引入了 keras_bert, 然后 keras_bert 基于 keras 初始化了，如果先用引入 kashgari，会设定环境 TF_KERAS=1，就不会出现这个问题。 

[colab demo](https://colab.research.google.com/drive/1-10xuIk-IZiqtxALgvxDFwKM4w42gTmW)

**Comment by ALittle-Eve** [comment]
谢谢啦，我自己再看看好了。

**Comment by echo-ray** [comment]
Hi~ @ALittle-Eve @BrikerMan 
如果使用的是1.12版本的话
可能跟[`tensorflow/python/keras/engine/training_generator.py` 中的第165-170行](https://github.com/tensorflow/tensorflow/blob/r1.12/tensorflow/python/keras/engine/training_generator.py#L165) 和 [kashgari/embeddings/bert_embedding.py的第190行](https://github.com/BrikerMan/Kashgari/blob/ab9970ecf6c0164416bfbbec1378c690b0f00d76/kashgari/embeddings/bert_embedding.py#L190) 有关    
`tensorflow 1.12` 那部分代码没有考虑到 tuple 的情况     
因此把 `bert_embedding.py`中的`return x0, x1` 改为 `return [x0, x1]` 似乎可以解决这个报错
如果您遇到的是其它情况，请忽略这个反馈哈

**Comment by BrikerMan** [comment]
嗯，我测试都是 tensorflow 1.14，建议更新一下吧。
