### ISSUE TITLE
How to acquire confidence (ie. score) in classification task,

### ISSUE THREAD

**Issue by BinNong** [BrikerMan/Kashgari#165]
It's a great library for NLP application. In classification task, when i use "model.predict" , what confuse me is how to acquire confidence(ie. score) along with Label.

**Comment by BrikerMan** [comment]
You could use the [predict_top_k_class](https://kashgari.bmio.net/api/tasks.classification/#predict95top95k95class) api to get label with score.

**Comment by BinNong** [comment]
thanks

**Comment by enjuichang** [comment]
Is predict_top_k_class still working in the package?
