### ISSUE TITLE
model error in web service using Flask

### ISSUE THREAD

**Issue by BinNong** [BrikerMan/Kashgari#167]
## Check List

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [Linux ubuntu 16.04]:

### What

When I deploy _kashgari.tasks.classification_   model  on the web service using Flask, I encounter an error showing below:
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Tensor Input-Token:0, specified in either feed_devices or fetch_devices was not found in the Graph**

and source code:
```
@app.route('/api/deep_classify/multi', methods=['GET', 'POST'])
def deep_classify_all():
      text = unquote(request.values.get("text"))
      categories = kashgari.tasks.classification.BiGRU_Model.predict_top_k_class([segment(text)])
        
        return categories

```

### Other Comment
After research a while, I think the reason may be this：
[]https://kobkrit.com/tensor-something-is-not-an-element-of-this-graph-error-in-keras-on-flask-web-server-4173a8fe15e1

**Comment by BrikerMan** [comment]
Try to add predict one sample during the API start. Like this,

```python
# Add one line here to init network during api start
model.predict([x])

@app.route('/api/deep_classify/multi', methods=['GET', 'POST'])
def deep_classify_all():

```

**Comment by BinNong** [comment]
I have added the initial line according to your suggestion. After debugging, I found that  it can run successfully pass the first line below.
```
model.predict([x])
@app.route('/api/deep_classify/multi', methods=['GET', 'POST'])
def deep_classify_all():
```
But as soon as diving into the functionn` deep_classify_all()`, it failed.
And the error message like this shown up:
**tensorflow.python.framework.errors_impl.InvalidArgumentError: Tensor Input-Token:0, specified in either feed_devices or fetch_devices was not found in the Graph**

**Comment by BrikerMan** [comment]
Your API code is like this, right?

```python
@app.route('/api/deep_classify/multi', methods=['GET', 'POST'])
def deep_classify_all():
      text = unquote(request.values.get("text"))
      categories = model.predict_top_k_class([segment(text)])
      
      return categories
```

**Comment by BinNong** [comment]
yeah, that's it!

**Comment by BinNong** [comment]
> Your API code is like this, right?
> 
> ```python
> @app.route('/api/deep_classify/multi', methods=['GET', 'POST'])
> def deep_classify_all():
>       text = unquote(request.values.get("text"))
>       categories = model.predict_top_k_class([segment(text)])
>       
>       return categories
> ```
yeah, that's it!

**Comment by BinNong** [comment]
> I have tried flask and reproduced the issue. I will try to fix it. But it might not be easy. Maybe you could try the tensorflow-serving. Here is the [example](https://kashgari.bmio.net/advance-use/tensorflow-serving/)

ok，thanks！

**Comment by alexwwang** [comment]
> I have tried flask and reproduced the issue. I will try to fix it. But it might not be easy. Maybe you could try the tensorflow-serving. Here is the [example](https://kashgari.bmio.net/advance-use/tensorflow-serving/)

This is an upstream problem  while calling tensorflow calculating graph before it is initialized. One should initialize the graph explicitly in this situation.

No need to fix anything but use tf.server to provide api server and let flask manage and forward requests, which is the best practice.

**Comment by Kircheis17** [comment]
I also encountered this error using flask. The way that solved this problem in my case is keeping the graph & session to be the same for loading the model and doing the prediction, like this:
```python
graph = tf.Graph()
with graph.as_default():
    session = tf.Session()
    with session.as_default():
        # load the model

...

def deep_classify_all():
      text = unquote(request.values.get("text"))
      with graph.as_default():
          with session.as_default():
              categories = model.predict_top_k_class([segment(text)])
      
      return categories
```
It can't possibly be the best way. But it works for me. @alexwwang 's point sounds quite convincing, I think that's why specifying the graph & session helps.

**Comment by hhxx2015** [comment]
init = tf.global_variables_initializer()
graph = tf.get_default_graph()
# with graph.as_default():
session = tf.Session()
session.run(init)
set_session(session)


def predict_prob(self, corpus):
       x = [tokenize(i) for i in corpus]
       logger.info(x)

       global kmodel
       global graph
       global session
       with graph.as_default():
            set_session(session)
            with session.as_default():
                pre = kmodel.predict_top_k_class(x, batch_size=1)
                prelabel = [p["label"] for p in pre]
                return prelabel
