### ISSUE TITLE
[Question] After updating to 0.5.1 multi-gpu support have not been working

### ISSUE THREAD

**Issue by sld** [BrikerMan/Kashgari#170]
Hi! Thank you for the great lib!

After updating from 0.2.4 to 0.5.1 only one gpu out of two is used.
The code almost the same:
```
hyper_parameters = BLSTMModel.get_default_hyper_parameters()
hyper_parameters['layer_bi_lstm']['units'] = 1024

model = BLSTMModel(embedding, hyper_parameters=hyper_parameters)
model.build_model(X_train, y_train)
model.build_multi_gpu_model(gpus=2, x_train=X_train, y_train=y_train, x_validate=X_valid, y_validate=y_valid)
model.fit(X_train, y_train, epochs=15, batch_size=512, x_validate=X_valid, y_validate=y_valid, callbacks=[tf_board_callback, checkpoint_callback])
```

NVtop and nvidia-smi showing that only one gpu is working.
In the previous version I have both of my gpus been used.

**Comment by BrikerMan** [comment]
@HaoyuHu Maybe you could help me out, I don't have multi-gpu environment.

**Comment by jeshuren** [comment]
I am also facing the same issue. Would be great if someone could help.

**Comment by HaoyuHu** [comment]
Could you please provide a runnable code to reproduce this problem, thx!

**Comment by BrikerMan** [comment]
@jeshuren So if fixed by not calling the `build_model ` function?

**Comment by jeshuren** [comment]
> @jeshuren So if fixed by not calling the `build_model` function?

Yes @BrikerMan

**Comment by BrikerMan** [comment]
@sld Maybe you can try it without calling `build_model` function.

**Comment by sld** [comment]
Thanks! This https://github.com/BrikerMan/Kashgari/issues/170#issuecomment-513875786 worked!
