### ISSUE TITLE
[Question] Finetuning of BERT and GPT-2

### ISSUE THREAD

**Issue by polars05** [BrikerMan/Kashgari#171]
Is it possible to finetune BERT and GPT-2 on my own corpus? Thanks!

**Comment by BrikerMan** [comment]
- BERT, you could fine-tune by setting trainable True, [API Document](https://kashgari.bmio.net/embeddings/bert-embedding/)
- GP2 can't finetune for now, maybe will add finetune feature later.

**Comment by polars05** [comment]
For BERT, is it possible to do unsupervised language model fine-tuning? For example, pre-training BERT on medical documents

**Comment by BrikerMan** [comment]
> For BERT, is it possible to do unsupervised language model fine-tuning? For example, pre-training BERT on medical documents

If you want to train BERT, just use the [keras-bert](https://github.com/CyberZHG/keras-bert#train--use). After training language model with keras-bert, load pre-trained language model in kashgari for training classification/labeling model.

For medical documents, here is a pre-trained model called BioBERT, maybe you can use this.

- [BioBERT: a pre-trained biomedical language representation model for biomedical text mining](https://github.com/dmis-lab/biobert)
