### ISSUE TITLE
[Question] ImportError: cannot import name 'custom_objects'

### ISSUE THREAD

**Issue by techflag** [BrikerMan/Kashgari#176]
Python 3.6.6
tf '1.14.0'
执行如下代码出错：
from kashgari.corpus import ChineseDailyNerCorpus

train_x, train_y = ChineseDailyNerCorpus.load_data('train')
valid_x, valid_y = ChineseDailyNerCorpus.load_data('validate')
test_x, test_y  = ChineseDailyNerCorpus.load_data('test')

print(f"train data count: {len(train_x)}")
print(f"validate data count: {len(valid_x)}")
print(f"test data count: {len(test_x)}")

错误内容：
ImportError: cannot import name 'custom_objects'

<img width="654" alt="111" src="https://user-images.githubusercontent.com/939362/61786357-1382f400-ae40-11e9-8088-f7649bcc2925.png">

**Comment by BrikerMan** [comment]
kashgari 版本呢?

**Comment by techflag** [comment]
> kashgari 版本呢?

__version__ = '0.5.1'

是直接使用pip install kashgari-tf 方式安装

**Comment by BrikerMan** [comment]
是不是之前安装过 `kashgari` 然后安装了 `kashgari-tf`。先都卸载了，然后重装一下 `kashgari-tf`.

```bash
pip uninstall kashgari
pip uninstall kashgari-tf
pip install kashgari
```

**Comment by techflag** [comment]
果然是这个情况，谢谢
