### ISSUE TITLE
[Question] Bert tokenizer for sequence labeling task

### ISSUE THREAD

**Issue by ThibaudReal** [BrikerMan/Kashgari#183]
Hello, 
I am trying to implement Bert embedding for sequence labeling task. 
However, when I tokenize my sentences with Bert tokenizer, the number of words is changing but not the number of labels:

`['only', 'france', 'and', 'britain', 'backed', 'fischler', "'s", 'proposal', '.'] # length=9`
`['O', 'B-LOC', 'O', 'B-LOC', 'O', 'B-PER', 'O', 'O', 'O'] # length=9`

becomes after tokenization :
`[ 'only', 'france', 'and', 'britain', 'backed', 'fis', '##ch', '##ler', "'", 's', 'proposal', '.'] # length=12`
`['O', 'B-LOC', 'O', 'B-LOC', 'O', 'B-PER', 'O', 'O', 'O'] # length=9`

(I removed BOS/EOS so I can set bert_embedding.processor.add_bos_eos = True)

How should I change the labels ?

**Comment by BrikerMan** [comment]
You need to change the labels to, this is a really annoying process. Here is the way which I do, maybe not the best way, but at least it works.

```python
x_data = [
   ['britain', 'backed', "fischler's", 'man', 'proposal']
]

y_data = [
   ['B-LOC', 'O', 'B-PER', 'I-PER', 'O']
]

new_x_data = []
new_y_data = []

for sample_index, sample in enumerate(x_data):
    new_sample_x = []
    new_sample_y = []
    for token_index, token in enumerate(sample):
        new_tokens = tokenize(token)
        label = y_data[sample_index][token_index]
        label_rows = label.split('-')
        if label.startswith('B-'):
            new_labels = [label] + [label.replace('B-', 'I-') for _ in range(len(new_tokens)-1)]
        else:
            new_labels = [label for _ in range(len(new_tokens))]
        new_sample_x += new_tokens
        new_sample_y += new_labels
    new_x_data.append(new_sample_x)
    new_y_data.append(new_sample_y)

print(new_x_data)
print(new_y_data)

# [['britain', 'backed', 'fischler', 's', 'man', 'proposal']]
# [['B-LOC', 'O', 'B-PER', 'I-PER', 'I-PER', 'O']]
```
