### ISSUE TITLE
TensorArray has size zero, but element shape [?,128] is not fully defined

### ISSUE THREAD

**Issue by techflag** [BrikerMan/Kashgari#188]
我们自己自定义数据集
<img width="1000" alt="WX20190806-154211@2x" src="https://user-images.githubusercontent.com/939362/62520750-cac83380-b860-11e9-8503-7b71ed153e3f.png">

**Comment by BrikerMan** [comment]
应该是 TensorFlow 版本问题，麻烦按照 issue 模板，提供完整的信息。
