### ISSUE TITLE
TensorArray has size zero, but element shape [?,128] is not fully defined[BUG] 

### ISSUE THREAD

**Issue by techflag** [BrikerMan/Kashgari#189]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment
**python3.6
tf : '1.14.0'
kashgari ：0.5.1
keras：2.2.4
使用的模型是BiLSTM_CRF_Model**

- OS [e.g. Mac OS, Linux]:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```
**训练代码**
<img width="575" alt="1" src="https://user-images.githubusercontent.com/939362/62521353-13ccb780-b862-11e9-909f-c887e0d76e28.png">

## Issue Description
<img width="1000" alt="WX20190806-154211@2x" src="https://user-images.githubusercontent.com/939362/62521319-00215100-b862-11e9-8dd5-0806612d63bb.png">
TensorArray has size zero, but element shape [?,128] is not fully defined
### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
1. GPU环境么？
2. 请问数据集用的你的数据集还是人民日报数据集？

**Comment by techflag** [comment]
CPU环境
数据集是我自己弄的
现在尝试一下BiLSTM_Model看看

**Comment by BrikerMan** [comment]
> CPU环境
> 数据集是我自己弄的
> 现在尝试一下BiLSTM_Model看看

还有检查一下数据集里面存不存在序列为空的情况。

**Comment by BrikerMan** [comment]
请问这个问题解决了么？
