### ISSUE TITLE
[Question] Can't load a model after training

### ISSUE THREAD

**Issue by MNCTTY** [BrikerMan/Kashgari#190]
Hi! Long time didn't see :)
I faced some issue:
I used custom model for classification task and trained it, saved weights as h5. And now I can't to load it to test.
 Try this:
`model.load_weights("model_weights.h5")`

and gets:

`AttributeError: 'LSTM_Dropout_Dense_Model' object has no attribute 'load_weights'`

`class LSTM_Dropout_Dense_Model(BaseClassificationModel):
`   
is based on BaseClassificationModel
I found in other issues here to use something like `loaded_model.model.load_weights(''')`
but I get 
`AttributeError: 'LSTM_Dropout_Dense_Model' object has no attribute 'model'`

What can I do?

**Comment by BrikerMan** [comment]
This model here is Kashgari-Model object, you need to call it's tf_model object to use load_weights function.
```
model.tf_model.load_weights("model_weights.h5")
```

**Comment by BrikerMan** [comment]
We hare renamed `model.model` to `model.tf_model` for readability.
All kashgari model object has a property called `tf_model`, which is a tf.keras model, and you can use all function of tf.keras model here.

**Comment by MNCTTY** [comment]
hmm
I tried, but it said 
`AttributeError: 'NoneType' object has no attribute 'load_weights'`

what i did wrong?

**Comment by MNCTTY** [comment]
if I run:
`type(model)`
I get:
`__main__.LSTM_Dropout_Dense_Model`

**Comment by BrikerMan** [comment]
Got it. You need to build a model first to get the tf_model object, try this, 

```python
# save the trained model
model.save('model_path')

# load model
# This includes model struct and model wights
new_model = kashgari.utils.load_model('model_path')
# You can reload model weights now
new_model.tf_model.load_weights('xx.h5')
```

**Comment by MNCTTY** [comment]
and what kind of objects will be in 'model_path' after saving? I mean, ckpt or what? I used keras callbacks to save the model, and I have plenty of hdf5 objects (I think, they were created at the end of each epoch) and only one pair of .h5 and .json

**Comment by MNCTTY** [comment]
ah! I think it worked. So, a pair of .h5 and .json are created by command from this library model.save('model_path'), and it's easy to be loaded, ok

and hdf5 objects are created by keras callbacks. any ideas what we should use to load them?
or it's better to use model.save('model_path') to save model.
but then every new saving is rewriting previous one, so we can't roll back in some cases. how can I use this command to give every pair new name?

**Comment by BrikerMan** [comment]
I think you can do this, save after fit one epoch. Then use callbacks to save hdf5 objects. By doing this, you have a JSON file, a saved_weigths by save function and lots of hdf5 files by callbacks. Then you can load model struct by `load_model(model_folder, load_weights = False)`, Then you can load any-weights you want. Of course, you can original weights then rewrite by load_weights function. Up to you.

https://github.com/BrikerMan/Kashgari/blob/2b6fafe0b1d4ff5ce8c42d3456abc6068b751bb8/kashgari/utils.py#L45

Or, you can rewrite a saved model callback by your-self, then call the `model.save` function after every epoch. Customizing callbacks are very easy.

**Comment by BrikerMan** [comment]
```python
from tensorflow.python import keras
from kashgari.tasks.base_model import BaseModel

class SaveModelCallBack(keras.callbacks.Callback):

    def __init__(self, kash_model: BaseModel, step=2):
        """
        SaveModel callback, calculate precision, recall and f1
        Args:
            kash_model: the kashgari model to evaluate
            step: step, default 2
        """
        super(SaveModelCallBack, self).__init__()
        self.kash_model = kash_model
        self.text_format = 'model_epoch_{epoch}'

    def on_epoch_end(self, epoch, logs=None):
        if (epoch + 1) % self.step == 0:
            self.kash_model.save(self.text_format.format(epoch=epoch))
```

**Comment by MNCTTY** [comment]
ah cool! thank you 
p.s. model that i loaded and expected it to be correcting word spelling do it so crazy (－‸ლ)

**Comment by BrikerMan** [comment]
Maybe you can write medium blogs about Kashgari~

**Comment by MNCTTY** [comment]
I've never done it before, but a bit more experience and I'll try!
I try sometimes to accumulate my exp in small texts in my telegram blog, but it's really rare and only for me and 2-3 people doing +- same tasks. Creating longreads very challenging for me! Never done it in english especially
but I'll try, in September, right after entry exams in the phd program
because you develop really convenient, useful project -- and it deserves to be more popular

**Comment by Ariunbileg0626** [comment]
model_path = os.path.join("results", parameters.model_name) + ".h5"
model.load_weights(model_path)
Exception has occurred: OSError
Unable to open file (unable to open file:
