### ISSUE TITLE
Use of BERT embedding

### ISSUE THREAD

**Issue by Qian16** [BrikerMan/Kashgari#191]
Hello. I am doing the classification task using BERT embedding like this:

bert_embedding = BERTEmbedding('bert-base-uncased',sequence_length=30)                    
model = CNNLSTMModel(bert_embedding)

However, I get the following error: 

File "/site-packages/kashgari/embeddings/bert_embedding.py", line 73, in __init__
    from_saved_model=from_saved_model)
  File "/site-packages/kashgari/embeddings/base_embedding.py", line 77, in __init__
    raise ValueError()
ValueError

Thanks for the help.

**Comment by BrikerMan** [comment]
Please open issue using the issue template, which includes your system info, pypi info.
