### ISSUE TITLE
[BUG] 好像是文本序列太长了，报string index out of range

### ISSUE THREAD

**Issue by captain2017** [BrikerMan/Kashgari#192]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment
linux
- OS [e.g. Mac OS, Linux]:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Issue Description
![image](https://user-images.githubusercontent.com/27909557/62613337-db99a780-b93b-11e9-9318-84d619815be3.png)
会不会是我的文本序列太长了
### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
麻烦按照 Issue 规范填写信息，且代码和代码错误请用 markdown 格式粘贴一下。便于其他人检索参考。
