### ISSUE TITLE
string index out of range[BUG] 

### ISSUE THREAD

**Issue by captain2017** [BrikerMan/Kashgari#193]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

linux
```txt
[Paste requirements.txt file here]
```

## Issue Description

好像是文本序列太长了，报string index out of range

![image](https://user-images.githubusercontent.com/27909557/62621359-3dfba380-b94e-11e9-9bd4-7ac5968daa8b.png)

### Reproduce
model.evaluate(train_x[10:150], train_y[10:150])
### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
这个是我使用 seqeval 框架不支持你的标签格式。请问你的标签是如何打的？

**Comment by captain2017** [comment]
伴 B-DEVICE
热 I-DEVICE
电 B-DEVICE
缆 I-DEVICE
未 B-STATUS
进 I-STATUS
行 I-STATUS
有 I-STATUS
效 I-STATUS
固 I-STATUS
定 I-STATUS
， O
可 O
能 O
跌 O
落 O
下 O
来 O
缠 B-DANGER
绕 I-DANGER
在 I-DANGER
旋 I-DANGER
转 I-DANGER
的 I-DANGER
气 I-DANGER
浮 I-DANGER
选 I-DANGER
泵 I-DANGER
上 I-DANGER

**Comment by captain2017** [comment]
但是我能训练

**Comment by captain2017** [comment]
就是test的时候不行，如果test_x[:20],test_y[:20]却可以，如果全部就不行。

**Comment by BrikerMan** [comment]
> 就是test的时候不行，如果test_x[:20],test_y[:20]却可以，如果全部就不行。

目前是 evaluate 的时候某个输出结果不符合 seqeval 框架的输入。麻烦这么测试一下。先用 model.predict 方法预测出结果，然后再自己用不同的序列调用它的 evaluate 方法。来确认一下是那个字符串输出导致了这个问题。麻烦了。

**Comment by captain2017** [comment]
['J', 'Z', '9', '_', '3', '油', '田', 'C', 'E', 'P', 'D', '平', '台', '应', '急', '开', '关', '间', '空', '调', '室', '外', '机', '漏', '制', '冷', '剂'] ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'B-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'B-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS']

**Comment by captain2017** [comment]
这个就识别不出来

**Comment by BrikerMan** [comment]
奇怪了，估计这个需要给 seqeval 作者提 bug。我这几天休假在外，有空了看看。 你也可以先给他提 bug 沟通一下。

captain2017 <notifications@github.com>于2019年8月8日 周四11:50写道：

**Comment by BrikerMan** [comment]
> ['J', 'Z', '9', '_', '3', '油', '田', 'C', 'E', 'P', 'D', '平', '台', '应', '急', '开', '关', '间', '空', '调', '室', '外', '机', '漏', '制', '冷', '剂'] ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'B-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'B-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS']

不对呀，我测试了以下，以下代码能够正常跑。

```python
from seqeval.metrics.sequence_labeling import get_entities
label = ['O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'B-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'I-DEVICE', 'B-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS']
get_entities(label)
```

**Comment by captain2017** [comment]
['J', 'Z', '2', '5', '_', '1', 'S', '', 'I', 'I', '', 'W', 'H', 'P', 'E', '中', '二', '甲', '板', '主', '开', '关', '间', '门', '外', '消', '防', '内', '干', '粉', '灭', '火', '器', '压', '力', '低', '于', '正', '常', '范', '围', '内'] ['O', 'O', 'O', 'O', 'O', 'O', 'O', '', 'O', 'O', '', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'O', 'B-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS', 'I-STATUS']

**Comment by captain2017** [comment]
好像太长就不行了

**Comment by BrikerMan** [comment]
> 好像太长就不行了

嗯嗯，暂时只能不用这个 evaluate 方法了。我看你已经提 bug 了。等修复吧。

**Comment by captain2017** [comment]
已经修复了
