### ISSUE TITLE
embedding时不能选择任务种类

### ISSUE THREAD

**Issue by yangzh9106** [BrikerMan/Kashgari#194]
A clear and concise description of what you want to know.
import kashgari
from kashgari.embeddings import BERTEmbedding
embedding = BERTEmbedding('D:/DeepLearningCode_Projects/Bert_multi_classification/model_test/kashgari/pretrained/chinese_L-12_H-768_A-12/',task=kashgari.LABELING,sequence_length=128)
运行报错

embedding = BERTEmbedding('D:/DeepLearningCode_Projects/Bert_multi_classification/model_test/kashgari/pretrained/chinese_L-12_H-768_A-12/',task=kashgari.LABELING,sequence_length=128)
Traceback (most recent call last):

  File "<ipython-input-21-755a91fbed0a>", line 1, in <module>
    embedding = BERTEmbedding('D:/DeepLearningCode_Projects/Bert_multi_classification/model_test/kashgari/pretrained/chinese_L-12_H-768_A-12/',task=kashgari.LABELING,sequence_length=128)

AttributeError: module 'kashgari' has no attribute 'LABELING'

如果没有task=kashgari.LABELING 这段代码则可以运行，另一个任务CLASSIFICATION也不行，请问这是什么原因呢

**Comment by BrikerMan** [comment]
这个是因为你安装的遗留版本 kashgari，请 `pip uninstall kashgari && pip install kashgari-tf`

**Comment by yangzh9106** [comment]
已经按此操作，但是还是不行，仍然报同样的错误

**Comment by yangzh9106** [comment]
抱歉，重启一下spider就可以了
