### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by techflag** [BrikerMan/Kashgari#195]
A clear and concise description of what you want to know.
ChineseDailyNerCorpus.load_data('train')
如何加载自己的数据集
我看默认是在.Kashgari中的，我如何加载我指定位置的数据
谢谢

**Comment by BrikerMan** [comment]
弄成内置数据集一样的格式即可，传入即可。

**Comment by techflag** [comment]
传入的是文件地址吗？如/opt/datasets/example.train

**Comment by BrikerMan** [comment]
不是，自己读取，tokenize，弄成二维数组传到 model.fit 方法。

**Comment by BrikerMan** [comment]
https://kashgari-zh.bmio.net/tutorial/text-classification/#_3
