### ISSUE TITLE
[BUG] 分类文档bug

### ISSUE THREAD

**Issue by captain2017** [BrikerMan/Kashgari#197]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Issue Description
![image](https://user-images.githubusercontent.com/27909557/62776321-d3c53900-badc-11e9-8f71-07766649afbe.png)

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
不知道你要表达什么，麻烦看一下别人如何提问题，学习一下如何提 bug。谢谢。
