### ISSUE TITLE
实体识别中，系统自带的数据集的train的len和我自己的数据集len算出来的长度差不多，我们的数量远超系统自带的数据

### ISSUE THREAD

**Issue by techflag** [BrikerMan/Kashgari#201]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- Linux:
- Python 3.6:
- Kashgari0.53:
-tf 1.14。0
```txt
[Paste requirements.txt file here]
```

## Question
实体识别中，系统自带的数据集的train的len和我自己的数据集len算出来的长度差不多，我们的数量远超系统自带的数据。这个会是什么原因。或者有什么限制。
[A clear and concise description of what you want to know.]

系统自带数据len：

![image](https://user-images.githubusercontent.com/939362/63146660-49299000-c02e-11e9-851f-5ae7535bf179.png)

我们数据集len：

![image](https://user-images.githubusercontent.com/939362/63146998-6579fc80-c02f-11e9-9fe7-871669aab899.png)

**Comment by BrikerMan** [comment]
没看明白... 是说加载自己的数据集失败了？
