### ISSUE TITLE
[Question] 请问作者大佬，有没有针对BERT的BIO文本标注开源工具？

### ISSUE THREAD

**Issue by zhucz-kali** [BrikerMan/Kashgari#203]
请问作者大佬，有没有针对BERT的BIO文本标注开源工具？

**Comment by BrikerMan** [comment]
没看懂。BIO 文本标注工具是指的？

**Comment by zhucz-kali** [comment]
> 没看懂。BIO 文本标注工具是指的？

我是有一批自己的数据集，我自己标注的话太慢，想要找别人一起帮我实体标注，想找一个开源的好用一点的文本标注工具，标注出来的数据格式，最好能够符合BERT与训练模型的格式，请大佬帮我推荐下子~~~

**Comment by BrikerMan** [comment]
基本所有的标注软件标注出来的都不能直接用，但是用很简单的一个脚本转换一下即可。所以你就找个方便好用的标注，然后再转换一下用就好了。

zhucz-kali <notifications@github.com>于2019年8月20日 周二09:29写道：

**Comment by BrikerMan** [comment]
不需要针对 BRRT，BERT 和 非 BERT 使用的标注都是一样的，都是 BIO 标注法。

Eliyar Eziz <eliyar917@gmail.com>于2019年8月20日 周二09:35写道：
