### ISSUE TITLE
[Question] 用bert embedding训练好的classification模型部署到tf serving时报错TypeError: can only concatenate list (not "str") to list 

### ISSUE THREAD

**Issue by captain2017** [BrikerMan/Kashgari#207]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- linux
- Python Version:3.7
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question
model = BiLSTM_Model(bert_embed)
model.build_multi_gpu_model(gpus=2,cpu_merge= False,cpu_relocation=False,x_train=train_x,y_train=train_y)
model.fit(train_x, train_y, valid_x, valid_y,epochs=200,batch_size=512)

用bert embedding训练好的classification模型报错TypeError: can only concatenate list (not "str") to list 
而用
model = BiLSTM_Model()
model.build_multi_gpu_model(gpus=2,cpu_merge= False,cpu_relocation=False,x_train=train_x,y_train=train_y)
model.fit(train_x, train_y, valid_x, valid_y,epochs=200,batch_size=512)
就没有问题
from kashgari.tasks.classification import BiLSTM_Model
from kashgari.embeddings import BERTEmbedding
from kashgari.processors import ClassificationProcessor
import kashgari
import logging
logging.basicConfig(level='DEBUG')

bert_embed = BERTEmbedding('./chinese_L-12_H-768_A-12',
                           task=kashgari.CLASSIFICATION,
                           sequence_length=100)

**Comment by captain2017** [comment]
我解决了

**Comment by echan00** [comment]
@captain2017  你怎么解决的？
