### ISSUE TITLE
[Question] importError: cannot import name 'BLSTMModel',为何import总是失败啊

### ISSUE THREAD

**Issue by xueyongfu** [BrikerMan/Kashgari#209]

**Comment by xmy7216** [comment]
你试试BiLSTM_Model

**Comment by xueyongfu** [comment]
谢谢,看了下源码,明白了

from kashgari.tasks.labeling.models import CNN_LSTM_Model

from kashgari.tasks.labeling.models import BiLSTM_Model
from kashgari.tasks.labeling.models import BiLSTM_CRF_Model

from kashgari.tasks.labeling.models import BiGRU_Model
from kashgari.tasks.labeling.models import BiGRU_CRF_Model
