### ISSUE TITLE
[Question] why is dense size = Classification category +1？ （in classification task）

### ISSUE THREAD

**Issue by melansediao** [BrikerMan/Kashgari#21]
why is dense size = Classification category +1？ （in classification task）
These two pictures below are from your blog：
https://eliyar.biz/nlp_chinese_text_classification_in_15mins/?nsukey=O%2BczPW172RmhIMqZT%2BfUlcATr6%2Ba8SX%2BJOwFmeqO7sK%2FDXKSkt%2BembEWvsivT76TbO5z7Dh02n%2BDux3v7PQgBZJl9fdsUl7aFAeUOQis%2BI0D6lpYW%2B9nAVUiSaAvf6mCvwDLx2a6%2Be5p4Up5QuSJ9UiCKek51b5HXyjbOPnZJMM%3D

![image](https://user-images.githubusercontent.com/23566123/53239436-fc947600-36d6-11e9-89bd-33f9237e17f6.png)
![image](https://user-images.githubusercontent.com/23566123/53239451-07e7a180-36d7-11e9-9fd8-dc3b0f7f4832.png)

**Comment by BrikerMan** [comment]
Because I added `"PAD": 0` to label2idx dict by default on both classification and labeling tasks, I think I should remove this feature from classification task. Then dense size will equel to classification category.

**Comment by melansediao** [comment]
这个不影响训练吗？

**Comment by BrikerMan** [comment]
不影响，只是多了一个没有数据对应的分类。
