### ISSUE TITLE
how to train another model based on a trained model?[Question] 

### ISSUE THREAD

**Issue by koestlerWang** [BrikerMan/Kashgari#210]
## Environment

- OS :windows10
- Python Version:3.6
- requirements.txt:

```txt
When i use:
    model = load_model('Model1')
    model.fit(word_set, label_set, epochs=10)
    model.save('Model2')
This will give back:AttributeError: 'NoneType' object has no attribute '_load_saved_instance'

```

## Question

How to generate another model based on a model which only owns .json&.h5 file?
I can generate another model based a pretrained model such as 'chinese_L-12_H-768_A-12' which owns vocab.txt/bert_config.json/bert_model.ckpt.**  and so on.

**Comment by BrikerMan** [comment]
Which `load_model` function is this?

**Comment by koestlerWang** [comment]
> Which `load_model` function is this?

from kashgari.utils import load_model

**Comment by BrikerMan** [comment]
Please list the fines in `Model1` folder.

**Comment by koestlerWang** [comment]
> Please list the fines in `Model1` folder.

model_info.json
model_weights.h5

**Comment by BrikerMan** [comment]
I have tested, you can load and train model like this for now. `model_info.json` file includes all the token dics and config from the pre-trained model. So you only need `model_info.json` and `model_weights.h5`

```python
new_model_1 = kashgari.utils.load_model('model1')
new_model_1.compile_model()
new_model_1.fit(test_x, test_y, epochs=1)
```

Here is the [example notebook](https://colab.research.google.com/drive/106Z_faaZpZD83FqV98Oik7obdwrt2cs6)

**Comment by koestlerWang** [comment]
Thank U so much! It does solve my problem!
Maybe it can be written into the readme.md.
