### ISSUE TITLE
[Question] 请问如何设置pad后句子的固定长度

### ISSUE THREAD

**Issue by xueyongfu** [BrikerMan/Kashgari#211]

**Comment by BrikerMan** [comment]
自定义初始化一个 Embedding 层。如果原来代码没有初始化 Embedding 层，其实代码会自动初始化一个 [BareEmbedding](https://kashgari.bmio.net/embeddings/bare-embedding/) 层作为语言模型。所有的 Embedding 层都有一个参数叫作 `sequence_length`， 这个就是 padding 长度。然后使用这个 Embedding 初始化模型。

比如 Bert 的 padding 长度设置为 300，代码如下

```python
import kashgari
from kashgari.embeddings import BERTEmbedding

# need to spesify task for the downstream task,
# if use embedding for feature extraction, just set `task=kashgari.CLASSIFICATION`
bert = BERTEmbedding('<BERT_MODEL_FOLDER>',
                     task=kashgari.CLASSIFICATION,
                     sequence_length=300)

model = XXModel(bert)
```

文档链接：
- [Embedding](https://kashgari.bmio.net/embeddings/)
