### ISSUE TITLE
[BUG] When I use word2vec model, there is an UnicodeDecodeError

### ISSUE THREAD

**Issue by duwf2003** [BrikerMan/Kashgari#212]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Linux
- Python Version: 3.7
- requirements.txt:

```txt
[Paste requirements.txt file here]
```
Classification Model

### What

[Tell us about the issue]

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]
from gensim.models import Word2Vec
vec_model = Word2Vec(x_list, size=100, window=5, min_count=1, workers=4)
vec_model.save("Model/word2vec.model")

from kashgari.tasks.classification import CNNModel
from kashgari.embeddings import WordEmbeddings
embedding = WordEmbeddings('Model/word2vec.model', sequence_length=100)

'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
Save w2c model as word2vec format

```python
vec_model.wv.save_word2vec_format("Model/word2vec.txt")
embedding = WordEmbeddings('Model/word2vec.txt', sequence_length=100)
```

**Comment by duwf2003** [comment]
Work! Thank you.
