### ISSUE TITLE
[Question] 有人遇到过这个问题吗Valueerror

### ISSUE THREAD

**Issue by someon3wh** [BrikerMan/Kashgari#215]
## Environment

- OS [e.g. Mac OS, Linux]:Linux
- Python Version:3.6
- requirements.txt:

## Question

`from kashgari.embeddings import BERTEmbedding`
`embedding = BERTEmbedding('bert-base-chinese', sequence_length = 200)`

报错：
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-fd5e9cdfaa07> in <module>
----> 1 embedding_= BERTEmbedding('/home/wanghong/文档/chinese_L-12_H-768_A-12',200)

~/anaconda3/envs/tensorflow_gpu/lib/python3.6/site-packages/kashgari/embeddings/bert_embedding.py in __init__(self, model_folder, layer_nums, trainable, task, sequence_length, processor, from_saved_model)
     71                                             embedding_size=0,
     72                                             processor=processor,
---> 73                                             from_saved_model=from_saved_model)
     74 
     75         self.processor.token_pad = '[PAD]'

~/anaconda3/envs/tensorflow_gpu/lib/python3.6/site-packages/kashgari/embeddings/base_embedding.py in __init__(self, task, sequence_length, embedding_size, processor, from_saved_model)
     75                 self.processor = LabelingProcessor()
     76             else:
---> 77                 raise ValueError()
     78         else:
     79             self.processor = processor

ValueError:

**Comment by BrikerMan** [comment]
请按照文档的初始化方式，提供 task 参数。
```
bert_embedding = BERTEmbedding(bert_model_path,
                               task=kashgari.CLASSIFICATION,
                               sequence_length=128
```
