### ISSUE TITLE
dev accuracy在96%之后迅速降到0.15[BUG] 

### ISSUE THREAD

**Issue by YankeeMarco** [BrikerMan/Kashgari#217]
I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2019-08-23 13:07:25.426820: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2000160000 Hz
2019-08-23 13:07:25.427451: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ec77e57640 executing computations on platform Host. Devices:
2019-08-23 13:07:25.427483: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-08-23 13:07:25.429154: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2019-08-23 13:07:25.977217: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:07:25.977590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:00:04.0
2019-08-23 13:07:25.978065: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-23 13:07:25.979698: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-23 13:07:25.981263: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-23 13:07:25.981663: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-23 13:07:25.983654: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-23 13:07:25.985227: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-23 13:07:26.884364: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-23 13:07:26.884644: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:07:26.885169: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:07:26.886239: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-23 13:07:26.886315: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-23 13:07:26.986960: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-23 13:07:26.987002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-23 13:07:26.987010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-23 13:07:26.987346: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:07:26.987762: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:07:26.988115: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:07:26.988457: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/device:GPU:0 with 14927 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:04.0, compute capability: 7.0)
2019-08-23 13:07:26.991114: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ec78b39160 executing computations on platform CUDA. Devices:
2019-08-23 13:07:26.991146: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Tesla V100-SXM2-16GB, Compute Capability 7.0
WARNING: Logging before flag parsing goes to stderr.
W0823 13:07:26.991763 140498434520448 macros.py:34] CUDA GPU available, you can set `kashgari.config.use_cudnn_cell = True` to use CuDNNCell. This will speed up the training, but will make model incompatible with CPU device.
W0823 13:07:36.791338 140498434520448 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0823 13:08:00.481124 140498434520448 deprecation.py:506] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/python/keras/initializers.py:119: calling RandomUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0823 13:08:01.015745 140498434520448 deprecation.py:506] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1288: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-08-23 13:08:10.522327: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:08:10.522881: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1640] Found device 0 with properties: 
name: Tesla V100-SXM2-16GB major: 7 minor: 0 memoryClockRate(GHz): 1.53
pciBusID: 0000:00:04.0
2019-08-23 13:08:10.522984: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudart.so.10.0
2019-08-23 13:08:10.523023: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0
2019-08-23 13:08:10.523047: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcufft.so.10.0
2019-08-23 13:08:10.523078: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcurand.so.10.0
2019-08-23 13:08:10.523101: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusolver.so.10.0
2019-08-23 13:08:10.523129: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcusparse.so.10.0
2019-08-23 13:08:10.523157: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcudnn.so.7
2019-08-23 13:08:10.523272: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:08:10.523777: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:08:10.524163: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1763] Adding visible gpu devices: 0
2019-08-23 13:08:10.524230: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1181] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-08-23 13:08:10.524250: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1187]      0 
2019-08-23 13:08:10.524282: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1200] 0:   N 
2019-08-23 13:08:10.524619: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:08:10.525065: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1005] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-08-23 13:08:10.526022: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1326] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 14927 MB memory) -> physical GPU (device: 0, name: Tesla V100-SXM2-16GB, pci bus id: 0000:00:04.0, compute capability: 7.0)
W0823 13:08:34.244042 140498434520448 bert_embedding.py:126] seq_len: 100
W0823 13:08:36.718978 140498434520448 deprecation.py:506] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:97: calling GlorotUniform.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0823 13:08:36.719411 140498434520448 deprecation.py:506] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:97: calling Orthogonal.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0823 13:08:36.719591 140498434520448 deprecation.py:506] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:97: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
W0823 13:08:37.342919 140498434520448 deprecation.py:323] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/contrib/crf/python/ops/crf.py:567: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
W0823 13:08:37.402626 140498434520448 deprecation.py:323] From /home/dev/.conda/envs/kashgari/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py:244: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
Model: "model_4"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
Input-Token (InputLayer)        [(None, 100)]        0                                            
__________________________________________________________________________________________________
Input-Segment (InputLayer)      [(None, 100)]        0                                            
__________________________________________________________________________________________________
Embedding-Token (TokenEmbedding [(None, 100, 768), ( 91812096    Input-Token[0][0]                
__________________________________________________________________________________________________
Embedding-Segment (Embedding)   (None, 100, 768)     1536        Input-Segment[0][0]              
__________________________________________________________________________________________________
Embedding-Token-Segment (Add)   (None, 100, 768)     0           Embedding-Token[0][0]            
                                                                 Embedding-Segment[0][0]          
__________________________________________________________________________________________________
Embedding-Position (PositionEmb (None, 100, 768)     76800       Embedding-Token-Segment[0][0]    
__________________________________________________________________________________________________
Embedding-Dropout (Dropout)     (None, 100, 768)     0           Embedding-Position[0][0]         
__________________________________________________________________________________________________
Embedding-Norm (LayerNormalizat (None, 100, 768)     1536        Embedding-Dropout[0][0]          
__________________________________________________________________________________________________
Encoder-1-MultiHeadSelfAttentio (None, 100, 768)     2362368     Embedding-Norm[0][0]             
__________________________________________________________________________________________________
Encoder-1-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-1-MultiHeadSelfAttention[
__________________________________________________________________________________________________
Encoder-1-MultiHeadSelfAttentio (None, 100, 768)     0           Embedding-Norm[0][0]             
                                                                 Encoder-1-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-1-MultiHeadSelfAttentio (None, 100, 768)     1536        Encoder-1-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-1-FeedForward (FeedForw (None, 100, 768)     4722432     Encoder-1-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-1-FeedForward-Dropout ( (None, 100, 768)     0           Encoder-1-FeedForward[0][0]      
__________________________________________________________________________________________________
Encoder-1-FeedForward-Add (Add) (None, 100, 768)     0           Encoder-1-MultiHeadSelfAttention-
                                                                 Encoder-1-FeedForward-Dropout[0][
__________________________________________________________________________________________________
Encoder-1-FeedForward-Norm (Lay (None, 100, 768)     1536        Encoder-1-FeedForward-Add[0][0]  
Encoder-2-MultiHeadSelfAttentio (None, 100, 768)     2362368     Encoder-1-FeedForward-Norm[0][0] 
__________________________________________________________________________________________________
Encoder-2-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-2-MultiHeadSelfAttention[
__________________________________________________________________________________________________
Encoder-2-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-1-FeedForward-Norm[0][0] 
                                                                 Encoder-2-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-2-MultiHeadSelfAttentio (None, 100, 768)     1536        Encoder-2-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-2-FeedForward (FeedForw (None, 100, 768)     4722432     Encoder-2-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-2-FeedForward-Dropout ( (None, 100, 768)     0           Encoder-2-FeedForward[0][0]      
__________________________________________________________________________________________________
Encoder-2-FeedForward-Add (Add) (None, 100, 768)     0           Encoder-2-MultiHeadSelfAttention-
                                                                 Encoder-2-FeedForward-Dropout[0][
__________________________________________________________________________________________________
Encoder-2-FeedForward-Norm (Lay (None, 100, 768)     1536        Encoder-2-FeedForward-Add[0][0]  
__________________________________________________________________________________________________
Encoder-3-MultiHeadSelfAttentio (None, 100, 768)     2362368     Encoder-2-FeedForward-Norm[0][0] 
__________________________________________________________________________________________________
Encoder-3-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-3-MultiHeadSelfAttention[
__________________________________________________________________________________________________
Encoder-3-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-2-FeedForward-Norm[0][0] 
                                                                 Encoder-3-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-3-MultiHeadSelfAttentio (None, 100, 768)     1536        Encoder-3-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-3-FeedForward (FeedForw (None, 100, 768)     4722432     Encoder-3-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-3-FeedForward-Dropout ( (None, 100, 768)     0           Encoder-3-FeedForward[0][0]      
__________________________________________________________________________________________________
Encoder-3-FeedForward-Add (Add) (None, 100, 768)     0           Encoder-3-MultiHeadSelfAttention-
                                                                 Encoder-3-FeedForward-Dropout[0][
__________________________________________________________________________________________________
Encoder-3-FeedForward-Norm (Lay (None, 100, 768)     1536        Encoder-3-FeedForward-Add[0][0]  
__________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttentio (None, 100, 768)     2362368     Encoder-3-FeedForward-Norm[0][0] 
__________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-4-MultiHeadSelfAttention[
__________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-3-FeedForward-Norm[0][0] 
                                                                 Encoder-4-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-4-MultiHeadSelfAttentio (None, 100, 768)     1536        Encoder-4-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-4-FeedForward (FeedForw (None, 100, 768)     4722432     Encoder-4-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-4-FeedForward-Dropout ( (None, 100, 768)     0           Encoder-4-FeedForward[0][0]      
__________________________________________________________________________________________________
Encoder-4-FeedForward-Add (Add) (None, 100, 768)     0           Encoder-4-MultiHeadSelfAttention-
                                                                 Encoder-4-FeedForward-Dropout[0][
__________________________________________________________________________________________________
Encoder-4-FeedForward-Norm (Lay (None, 100, 768)     1536        Encoder-4-FeedForward-Add[0][0]  
__________________________________________________________________________________________________
Encoder-5-MultiHeadSelfAttentio (None, 100, 768)     2362368     Encoder-4-FeedForward-Norm[0][0] 
__________________________________________________________________________________________________
Encoder-5-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-5-MultiHeadSelfAttention[
__________________________________________________________________________________________________
Encoder-5-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-4-FeedForward-Norm[0][0] 
                                                                 Encoder-5-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-5-MultiHeadSelfAttentio (None, 100, 768)     1536        Encoder-5-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-5-FeedForward (FeedForw (None, 100, 768)     4722432     Encoder-5-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-5-FeedForward-Dropout ( (None, 100, 768)     0           Encoder-5-FeedForward[0][0]      
__________________________________________________________________________________________________
Encoder-5-FeedForward-Add (Add) (None, 100, 768)     0           Encoder-5-MultiHeadSelfAttention-
                                                                 Encoder-5-FeedForward-Dropout[0][
__________________________________________________________________________________________________
Encoder-5-FeedForward-Norm (Lay (None, 100, 768)     1536        Encoder-5-FeedForward-Add[0][0]  
__________________________________________________________________________________________________
Encoder-6-MultiHeadSelfAttentio (None, 100, 768)     2362368     Encoder-5-FeedForward-Norm[0][0] 
__________________________________________________________________________________________________
Encoder-6-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-6-MultiHeadSelfAttention[
__________________________________________________________________________________________________
Encoder-6-MultiHeadSelfAttentio (None, 100, 768)     0           Encoder-5-FeedForward-Norm[0][0] 
                                                                 Encoder-6-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-6-MultiHeadSelfAttentio (None, 100, 768)     1536        Encoder-6-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-6-FeedForward (FeedForw (None, 100, 768)     4722432     Encoder-6-MultiHeadSelfAttention-
__________________________________________________________________________________________________
Encoder-6-FeedForward-Dropout ( (None, 100, 768)     0           Encoder-6-FeedForward[0][0]      
__________________________________________________________________________________________________
Encoder-6-FeedForward-Add (Add) (None, 100, 768)     0           Encoder-6-MultiHeadSelfAttention-
                                                                 Encoder-6-FeedForward-Dropout[0][
__________________________________________________________________________________________________
Encoder-6-FeedForward-Norm (Lay (None, 100, 768)     1536        Encoder-6-FeedForward-Add[0][0]  
__________________________________________________________________________________________________
Encoder-7-MultiHeadSelfAttentio (None, 100, 768)     2362368     Encoder-6-FeedForward-Norm[0][0] 
.....
.....
.....
Encoder-12-MultiHeadSelfAttenti (None, 100, 768)     1536        Encoder-12-MultiHeadSelfAttention
__________________________________________________________________________________________________
Encoder-12-FeedForward (FeedFor (None, 100, 768)     4722432     Encoder-12-MultiHeadSelfAttention
__________________________________________________________________________________________________
Encoder-12-FeedForward-Dropout  (None, 100, 768)     0           Encoder-12-FeedForward[0][0]     
__________________________________________________________________________________________________
Encoder-12-FeedForward-Add (Add (None, 100, 768)     0           Encoder-12-MultiHeadSelfAttention
                                                                 Encoder-12-FeedForward-Dropout[0]
__________________________________________________________________________________________________
Encoder-12-FeedForward-Norm (La (None, 100, 768)     1536        Encoder-12-FeedForward-Add[0][0] 
__________________________________________________________________________________________________
Encoder-Output (Concatenate)    (None, 100, 3072)    0           Encoder-9-FeedForward-Norm[0][0] 
                                                                 Encoder-10-FeedForward-Norm[0][0]
                                                                 Encoder-11-FeedForward-Norm[0][0]
                                                                 Encoder-12-FeedForward-Norm[0][0]
__________________________________________________________________________________________________
non_masking_layer (NonMaskingLa (None, 100, 3072)    0           Encoder-Output[0][0]             
__________________________________________________________________________________________________
layer_bgru (Bidirectional)      (None, 100, 256)     2458368     non_masking_layer[0][0]          
__________________________________________________________________________________________________
layer_dense (Dense)             (None, 100, 64)      16448       layer_bgru[0][0]                 
__________________________________________________________________________________________________
layer_crf_dense (Dense)         (None, 100, 3)       195         layer_dense[0][0]                
__________________________________________________________________________________________________2019-08-23 13:08:44.736105: W tensorflow/compiler/jit/mark_for_compilation_pass.cc:1412] (One-time warning): Not using XLA:CPU for cluster because envvar TF_XLA_FLAGS=--tf_xla_cpu_global_jit was not set.  If you want XLA:CPU, either set that envvar, or use experimental_jit_scope to enable XLA:CPU.  To confirm that XLA is active, pass --vmodule=xla_compilation_cache=1 (as a proper command-line flag, not via TF_XLA_FLAGS) or set the envvar XLA_FLAGS=--xla_hlo_profile.
2019-08-23 13:08:44.998029: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcublas.so.10.0

layer_crf (CRF)                 (None, 100, 3)       9           layer_crf_dense[0][0]            
==================================================================================================
Total params: 179,421,452
Trainable params: 2,475,020
Non-trainable params: 176,946,432
__________________________________________________________________________________________________
Epoch 1/40
9028/9028 [==============================] - 5587s 619ms/step - loss: 5.7222 - accuracy: 0.9720 - val_loss: 43.9536 - val_accuracy: 0.9654
Epoch 2/40
9028/9028 [==============================] - 5603s 621ms/step - loss: 5.4869 - accuracy: 0.9730 - val_loss: 41.2249 - val_accuracy: 0.9658
Epoch 3/40
9028/9028 [==============================] - 5601s 620ms/step - loss: 5.4393 - accuracy: 0.9732 - val_loss: 42.0592 - val_accuracy: 0.9661
Epoch 4/40
9028/9028 [==============================] - 5536s 613ms/step - loss: 5.4174 - accuracy: 0.9733 - val_loss: 43.3301 - val_accuracy: 0.9661
Epoch 5/40
9028/9028 [==============================] - 5544s 614ms/step - loss: 5.3972 - accuracy: 0.9734 - val_loss: 40.5632 - val_accuracy: 0.9660
Epoch 6/40
9028/9028 [==============================] - 5591s 619ms/step - loss: 5.3798 - accuracy: 0.9735 - val_loss: 40.8309 - val_accuracy: 0.9663
Epoch 7/40
9028/9028 [==============================] - 5538s 613ms/step - loss: 5.3672 - accuracy: 0.9735 - val_loss: 42.6909 - val_accuracy: 0.9661
Epoch 8/40
9028/9028 [==============================] - 5539s 614ms/step - loss: 5.3552 - accuracy: 0.9736 - val_loss: 43.3322 - val_accuracy: 0.9661
Epoch 9/40
9028/9028 [==============================] - 5547s 614ms/step - loss: 5.3504 - accuracy: 0.9736 - val_loss: 40.7088 - val_accuracy: 0.9663
Epoch 10/40
9028/9028 [==============================] - 5399s 598ms/step - loss: 5.3395 - accuracy: 0.9737 - val_loss: 39.9875 - val_accuracy: 0.9664
Epoch 11/40
9028/9028 [==============================] - 5345s 592ms/step - loss: 5.3318 - accuracy: 0.9737 - val_loss: 38.4357 - val_accuracy: 0.9665
Epoch 12/40
9028/9028 [==============================] - 5298s 587ms/step - loss: 5.3278 - accuracy: 0.9738 - val_loss: 39.0018 - val_accuracy: 0.9664
Epoch 13/40
9028/9028 [==============================] - 5296s 587ms/step - loss: 5.3227 - accuracy: 0.9738 - val_loss: 40.4030 - val_accuracy: 0.9668
Epoch 14/40
9028/9028 [==============================] - 5306s 588ms/step - loss: 5.3143 - accuracy: 0.9738 - val_loss: 44.9503 - val_accuracy: 0.9662
Epoch 15/40
9028/9028 [==============================] - 5301s 587ms/step - loss: 5.3103 - accuracy: 0.9738 - val_loss: 47.9397 - val_accuracy: 0.9666
Epoch 16/40
9028/9028 [==============================] - 5295s 586ms/step - loss: 5.3056 - accuracy: 0.9739 - val_loss: 47.2758 - val_accuracy: 0.9660
Epoch 17/40
9028/9028 [==============================] - 5271s 584ms/step - loss: 5.3031 - accuracy: 0.9739 - val_loss: 55.0248 - val_accuracy: 0.9663
Epoch 18/40
9028/9028 [==============================] - 5270s 584ms/step - loss: 5.2981 - accuracy: 0.9739 - val_loss: 52.7320 - val_accuracy: 0.9663
Epoch 19/40
9028/9028 [==============================] - 5267s 583ms/step - loss: 5.3010 - accuracy: 0.9739 - val_loss: 48.5265 - val_accuracy: 0.9664
Epoch 20/40
9028/9028 [==============================] - 5286s 586ms/step - loss: 5.2968 - accuracy: 0.9739 - val_loss: 50.2645 - val_accuracy: 0.9664
Epoch 21/40
9028/9028 [==============================] - 5289s 586ms/step - loss: 5.2932 - accuracy: 0.9739 - val_loss: 51.4474 - val_accuracy: 0.9663
Epoch 22/40
9028/9028 [==============================] - 5283s 585ms/step - loss: 5.2878 - accuracy: 0.9740 - val_loss: 49.7987 - val_accuracy: 0.9664
Epoch 23/40
9028/9028 [==============================] - 5317s 589ms/step - loss: 5.2820 - accuracy: 0.9740 - val_loss: 49.5317 - val_accuracy: 0.9664
Epoch 24/40
9028/9028 [==============================] - 5322s 589ms/step - loss: 5.2815 - accuracy: 0.9740 - val_loss: 50.8262 - val_accuracy: 0.9661
Epoch 25/40
9028/9028 [==============================] - 5300s 587ms/step - loss: 5.2802 - accuracy: 0.9740 - val_loss: 56.4925 - val_accuracy: 0.9666
Epoch 26/40
9028/9028 [==============================] - 5286s 586ms/step - loss: 5.2766 - accuracy: 0.9740 - val_loss: 65.0910 - val_accuracy: 0.9665
Epoch 27/40
9028/9028 [==============================] - 5287s 586ms/step - loss: 5.2719 - accuracy: 0.9740 - val_loss: 71.8072 - val_accuracy: 0.1687
Epoch 28/40
9028/9028 [==============================] - 5291s 586ms/step - loss: 5.2726 - accuracy: 0.9741 - val_loss: 75.8402 - val_accuracy: 0.1694
Epoch 29/40
9028/9028 [==============================] - 5282s 585ms/step - loss: 5.2706 - accuracy: 0.9741 - val_loss: 73.2453 - val_accuracy: 0.1688
Epoch 30/40
9028/9028 [==============================] - 5290s 586ms/step - loss: 5.2682 - accuracy: 0.9741 - val_loss: 72.7192 - val_accuracy: 0.1592
Epoch 31/40
9028/9028 [==============================] - 5278s 585ms/step - loss: 5.2672 - accuracy: 0.9741 - val_loss: 70.5973 - val_accuracy: 0.1594
Epoch 32/40
9028/9028 [==============================] - 5271s 584ms/step - loss: 5.2646 - accuracy: 0.9741 - val_loss: 73.7140 - val_accuracy: 0.1691
Epoch 33/40
9028/9028 [==============================] - 5262s 583ms/step - loss: 5.2644 - accuracy: 0.9741 - val_loss: 74.9497 - val_accuracy: 0.1595
Epoch 34/40
9028/9028 [==============================] - 5311s 588ms/step - loss: 5.2606 - accuracy: 0.9741 - val_loss: 76.6094 - val_accuracy: 0.1588
Epoch 35/40
9028/9028 [==============================] - 5416s 600ms/step - loss: 5.2594 - accuracy: 0.9741 - val_loss: 82.7406 - val_accuracy: 0.1593
Epoch 36/40
9028/9028 [==============================] - 5360s 594ms/step - loss: 5.2581 - accuracy: 0.9741 - val_loss: 83.6362 - val_accuracy: 0.1593
Epoch 37/40
9028/9028 [==============================] - 5394s 597ms/step - loss: 5.2578 - accuracy: 0.9741 - val_loss: 80.2973 - val_accuracy: 0.1591
Epoch 38/40
9028/9028 [==============================] - 5345s 592ms/step - loss: 5.2538 - accuracy: 0.9742 - val_loss: 78.8290 - val_accuracy: 0.1592
Epoch 39/40
9028/9028 [==============================] - 5266s 583ms/step - loss: 5.2524 - accuracy: 0.9742 - val_loss: 77.1734 - val_accuracy: 0.1595
Epoch 40/40
9028/9028 [==============================] - 5264s 583ms/step - loss: 5.2516 - accuracy: 0.9742 - val_loss: 89.0208 - val_accuracy: 0.1591

**Comment by YankeeMarco** [comment]
以上是标准输出，layer 信息有部分省略了。

**Comment by BrikerMan** [comment]
可以使用 evaluate 函数测试一下，目前感觉是 crf 层的 loss 计算有问题。

**Comment by echan00** [comment]
我这边也遇到同样的问题，val_accuracy从0.6064速降到0.2148。模型是BiLSTM_CRF
