### ISSUE TITLE
[Question] unknown opcode

### ISSUE THREAD

**Issue by captain2017** [BrikerMan/Kashgari#219]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:linux
- Python Version:3.7
- requirements.txt:

tf1.14,kashgari=0.53

## Question
用之前训练出来的模型，在你给的cloab上跑，
![image](https://user-images.githubusercontent.com/27909557/63754240-1f525200-c8e7-11e9-98b8-8ca268b56ffd.png)
https://colab.research.google.com/drive/106Z_faaZpZD83FqV98Oik7obdwrt2cs6

**Comment by BrikerMan** [comment]
麻烦按照规范编辑一下 issue，补全信息。否则作为无效 issue 处理。此外，如果提到外部资源如 colab，麻烦带一下链接。
