### ISSUE TITLE
[BUG] Evaluate function for Stacked Embeddings

### ISSUE THREAD

**Issue by echan00** [BrikerMan/Kashgari#222]
I'm get the error `TypeError: 'int' object is not subscriptable` when trying to evaluate my stacked embedding sequence labeling model.  Is it supported?

Tensorflow 1.14.0
kashgari-tf 0.5.1

```
test_final_x = (test_x, test_x1)
test_final_y = test_y

model = kashgari.utils.load_model('BiGRU_Model2_10')
model.evaluate(test_final_x, test_final_y)

Traceback (most recent call last):
  File "process2-1.py", line 315, in <module>
    model.evaluate(test_final_x, test_final_y)
  File "/usr/local/lib/python3.6/dist-packages/kashgari/tasks/labeling/base_model.py", line 104, in evaluate
    report = classification_report(y_true, y_pred, digits=digits)
  File "/usr/local/lib/python3.6/dist-packages/seqeval/metrics/sequence_labeling.py", line 313, in classification_report
    true_entities = set(get_entities(y_true, suffix))
  File "/usr/local/lib/python3.6/dist-packages/seqeval/metrics/sequence_labeling.py", line 43, in get_entities
    tag = chunk[0]
TypeError: 'int' object is not subscriptable
```

**Comment by echan00** [comment]
It looks like the issue is related to numeric embeddings. The `classification_report` function of the `seqeval` library only takes strings, not integers

I converted the prediction arrays into strings in my fork of the evaluation function: https://github.com/echan00/Kashgari/blob/master/kashgari/tasks/labeling/base_model.py

```
temp_y_pred = self.predict(x_data, batch_size=batch_size)
temp_y_true = [seq[:len(y_pred[index])] for index, seq in enumerate(y_data)]
        
y_pred, y_true = [], []
for x in temp_y_pred:
        y_pred.append([str(i) for i in x])
for x in temp_y_true:
        y_true.append([str(i) for i in x])
```

**Comment by BrikerMan** [comment]
Is this issue fixed? @echan00

**Comment by echan00** [comment]
Sorry, this is my first time doing a pull request, I believe this will fix it:

https://github.com/BrikerMan/Kashgari/pull/232

**Comment by BrikerMan** [comment]
That cool, no worries. I will handle this request next week, come back to you then. Thanks for your contribution.
