### ISSUE TITLE
[模型评估使用ROC曲线和PR曲线] 

### ISSUE THREAD

**Issue by Xiao-da-1** [BrikerMan/Kashgari#223]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:Win 10
- Python Version:3.7
- requirements.txt: None

## Question

[做二分类任务时，使用Kashgari的model.predict(）得到的结果是字符串‘1.0’or'0.0'。但是，我现在需要做ROC曲线和PR曲线，如何使得predict(）结果是分类的概率已适合作图呢？求教！谢谢您！]

**Comment by BrikerMan** [comment]
使用这个 API 获取每个分类的概率即可 https://kashgari.bmio.net/api/tasks.classification/#predict95top95k95class

**Comment by BrikerMan** [comment]
请问问题解决了么？
