### ISSUE TITLE
Model configuration changed after saving and loading

### ISSUE THREAD

**Issue by kl0211** [BrikerMan/Kashgari#224]
I'm looking to build a multi-label model that can be loaded for other data. As a warm-up, I executed the code here:
https://kashgari.bmio.net/tutorial/text-classification/#multi-label-classification

And tried doing a predict on the sentences, like so:
>>> model.predict(x)
[('A', 'B'), ('A', 'B'), ('B',), ()]

I then used `model.save()` and `kashgari.utils.load_model()` and tried to predict the same data:
>>> loaded_model.predict(x)
['A', 'A', 'B', 'B']

After running model.info() and loaded_model.info(), I noticed two differences:
model has the configuration `'layer_dense': {'activation': 'sigmoid'}` and `'multi_label': True`

loaded_model has `'layer_dense': {'activation': 'softmax'}` and `'multi_label': False`

**Comment by BrikerMan** [comment]
Seems we forgot to save the multi_label property, which caused this issue. Thanks for pointing out.

**Comment by allhelllooz** [comment]
@BrikerMan also it doesn't save `task` property.

I am saving in following way
    `model.save(model_location)`

Loading and using
```
model = load_model(model_location)
model.embedding.task = "labeling"
model.compile_model()
```

If I don't set `model.embedding.task` ... in eval phase I get Multilabel error as there is a if-else condition for `labeling` task and currently `None` is getting passed. 

Its working with above code but saving model should be saving the task info as well.

**Comment by BrikerMan** [comment]
> info

Yep, will fix on 0.5.4 version.

**Comment by kl0211** [comment]
@BrikerMan, I tested saving and loading on v0.5.4. The multi-label property does persist after loading, but the layer_dense activation property still changes from sigmoid to softmax.

**Comment by BrikerMan** [comment]
> @BrikerMan, I tested saving and loading on v0.5.4. The multi-label property does persist after loading, but the layer_dense activation property still changes from sigmoid to softmax.

@lsgrep, please check out this issue.
