### ISSUE TITLE
[Feature request] 建议添加XLNet模型支持

### ISSUE THREAD

**Issue by yaleimeng** [BrikerMan/Kashgari#225]
XLNet公布也有几个月了。近期第三方预训练的中文模型也已放出。希望能添加对于这一模型的支持。
以便大家检验和比较不同模型之间的差异，丰富从业者的选择。

**Comment by tengteng-Lin** [comment]
请问解决了吗？我也有相同的问题

**Comment by yaleimeng** [comment]
@tengteng-Lin 不知道怎么摸索的解决了，我对框架源码做过细微的修改。
你可以试着将测试集数据的前几句预测结果y0 = model.predict(text_x[:5])打印出来看一下。
如果能正常执行评估，应该是可以正常预测每个字的label。
