### ISSUE TITLE
[Question] 中文句子中NER 实体识别问题  空格问题

### ISSUE THREAD

**Issue by cronousbaby** [BrikerMan/Kashgari#229]
您好，如果句子中出现空格  比如 “项目总称：项目A   项目B”  我在构造BIO 训练语料时 不忽略空格进行训练 【O,O,O,O,O,B-a,I-a,I-a,这个是空格O,B-b,I-b,I-b】 使用Bert预训练会报错误，是不是Bert 会根据空格进行分割句子的，如果我想保留这句话中间的空格特征 如何处理呢

**Comment by BrikerMan** [comment]
BERT 有很多没有使用的 Token，比如 unused1 unused20。可以把全局空格替换成这种特殊 token 再训练~

**Comment by cronousbaby** [comment]
在kashgrai中 如何实现呢 ， 替换令牌    项目A 空格  项目B 能不能给个具体的用例呢 大神

**Comment by BrikerMan** [comment]
这个需要在数据丢到 Kashgari 之前自己批量替换一下，然后在使用 Kashgari 处理。

**Comment by cronousbaby** [comment]
您好 我重写了 bert_embedding下的 初始化tokenizer的部分     
def _build_token2idx_from_bert(self):
        dict_path = os.path.join(self.model_folder, 'vocab.txt')


        token2idx = {}
        with codecs.open(dict_path, 'r', 'utf8') as reader:
            for line in reader:
                token = line.strip()
                token2idx[token] = len(token2idx)


        self.bert_token2idx = token2idx


        #self._tokenizer = keras_bert.Tokenizer(token2idx)
        self._tokenizer = SpaceTokenizer(token2idx)
        self.processor.token2idx = self.bert_token2idx
        self.processor.idx2token = dict([(value, key) for key, value in token2idx.items()])



重写了 在这个 SpaceTokenizer 里面的 _tokenize
对空格字符进行了 unused1的替换 
但是 在训练的时候 无法跳进_tokenize方法里面的 断点 是什么原因呢 
------------------ 原始邮件 ------------------
发件人: "Eliyar Eziz"<notifications@github.com>;
发送时间: 2019年9月5日(星期四) 下午5:36
收件人: "BrikerMan/Kashgari"<Kashgari@noreply.github.com>;
抄送: "蘑菇小象"<626827378@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [BrikerMan/Kashgari] [Question] 中文句子中NER 实体识别问题  空格问题 (#229)




这个需要在数据丢到 Kashgari 之前自己批量替换一下，然后在使用 Kashgari 处理。
