### ISSUE TITLE
[Feature request] how to plot a model using keras plot_model api

### ISSUE THREAD

**Issue by w5688414** [BrikerMan/Kashgari#230]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
I want to use plot_model to output ner model, how do I write this code

**Comment by BrikerMan** [comment]
You can access the tf.keras model by the property `model.tf_model`. Then you can plot it. Remember to import plot function from tf.keras, not keras.
