### ISSUE TITLE
[Question] Multi-output model

### ISSUE THREAD

**Issue by habolivier** [BrikerMan/Kashgari#233]
Hello Dear @BrikerMan .  Thanks for creating Kashgari! I tried the example in mutli-output link (https://kashgari.bmio.net/advance-use/multi-output-model/)  but it raises an error.  
Thanks.

kashgari/processors/classification_processor.py", line 35, in _build_label_dict
    label_set = set(labels)
TypeError: unhashable type: 'list'

**Comment by habolivier** [comment]
@BrikerMan you can change line 35 in classification processor to the following. (https://stackoverflow.com/questions/57763803/convert-a-list-of-lists-into-a-set-of-lists-in-python-3)

label_set = set()
            for array in label_set:
                label_set.add(tuple(array))

**Comment by BrikerMan** [comment]
Hi, When you using the multi-output model. You need to customize your own processor, too. Just subclass the classification processor and change it.

**Comment by 5118Python** [comment]
@BrikerMan thx
