### ISSUE TITLE
build_multi_gpu_model InvalidArgumentError

### ISSUE THREAD

**Issue by 5118Python** [BrikerMan/Kashgari#234]
error:
![image](https://user-images.githubusercontent.com/14151451/64495383-cd88cf00-d2cb-11e9-9a2b-1c696b0c204e.png)

code:
![image](https://user-images.githubusercontent.com/14151451/64495424-70414d80-d2cc-11e9-92b5-168c6fe3067f.png)

**Comment by 5118Python** [comment]
CRF not support multi gpu?
#174

**Comment by BrikerMan** [comment]
> CRF not support multi gpu?
> #174

Yep, need to implement multi-GPU version.

**Comment by 5118Python** [comment]
@BrikerMan thx

**Comment by allhelllooz** [comment]
<img width="1437" alt="Screenshot 2019-11-20 at 3 10 21 PM" src="https://user-images.githubusercontent.com/54931618/69227498-e5bc7a80-0ba7-11ea-909c-71a708393039.png">

Got the same issue ... is this resolved ?? CRF with multi-gpu ??
