### ISSUE TITLE
[Question] 和flask一起使用的时候报错

### ISSUE THREAD

**Issue by BinNong** [BrikerMan/Kashgari#24]
报错：ValueError: Fetch argument <tf.Variable 'Embedding-Token/embeddings:0' shape=(21128, 768) dtype=float32_ref> cannot be interpreted as a Tensor. (Tensor Tensor("Embedding-Token/embeddings:0", shape=(21128, 768), dtype=float32_ref) is not an element of this graph.)
报错的地方：
bert_embedding = BERTEmbedding('bert-base-chinese', sequence_length=512)

**Comment by BrikerMan** [comment]
模型加载后先调用一次 `predict` 方法，然后在调用 `app.run` 启动 flask 即可。

**Comment by BrikerMan** [comment]
@BinNong 请问问题解决了么？

**Comment by BinNong** [comment]
> @BinNong 请问问题解决了么？

现在是可以predict，但是通过http接口调用重新训练的时候还是出问题

**Comment by BrikerMan** [comment]
没太明白，你的需求是通过请求控制什么时候开始训练？ 可以提供 demo 代码和具体的错误么？

**Comment by BinNong** [comment]
> 没太明白，你的需求是通过请求控制什么时候开始训练？ 可以提供 demo 代码和具体的错误么？

        bert_embedding = BERTEmbedding('bert-base-chinese', sequence_length=512)
        classifier = CNNLSTMModel(bert_embedding)
        classifier.fit(texts, labels, epochs=2)
报错的地方是Fetch argument <tf.Variable 'Embedding-Token/embeddings:0' shape=(21128, 768) dtype=float32_ref> cannot be interpreted as a Tensor. (Tensor Tensor("Embedding-Token/embeddings:0", shape=(21128, 768), dtype=float32_ref) is not an element of this graph.)

**Comment by BrikerMan** [comment]
麻烦贴一下 flask 的代码

**Comment by BinNong** [comment]
> 麻烦贴一下 flask 的代码
在flask里面设置路由
 @app.route('/manage/model/rebuild')
    def model_rebuild():
          ...
          build() （这里会起一个新的线程，执行代码是上面那一段classifier）
          ....
app启动后，第一次调用rebuild是可以训练的，但是第二次调用的时候就错出了，是不是session的问题呢

**Comment by BrikerMan** [comment]
可能是，没有做过类似的需求，如果可以提供个小 demo，然后我们一起解决看看。
