### ISSUE TITLE
[Question] Connecting classification layer to BERT

### ISSUE THREAD

**Issue by Qian16** [BrikerMan/Kashgari#242]
Hello @BrikerMan .  I implemented my model based on Kashagri BERT embedding.  Thus, I want to compare its performance with BERT.  So, I will fine-tune the embeddings and build the BERT based on Kashgari as follows.

```python
build_model(self):
    embed_model = self.embedding.embed_model
    chanel1_x_sent=embed_model.output

    layer_output_2 = L.Dense(2, activation='sigmoid', name='classif')
    classi=layer_output_2(chanel1_x_sent)
    self.tf_model = tf.keras.Model(embed_model.inputs, classi)
```

My question:
1) Am I  right to implement BERT like this?
Thank you.

**Comment by BrikerMan** [comment]
Yep, this is the correct way to do it. This should work.

One more thing, please check out how to use markdown currectly before next issue. Here is the document: https://guides.github.com/features/mastering-markdown/
