### ISSUE TITLE
[Question] 关于BERT中的layer_nums对模型性能的影响

### ISSUE THREAD

**Issue by aguang1201** [BrikerMan/Kashgari#243]
非常感谢up主分享的框架,很好用.我使用BERTEmbedding做了一些文本2分类的实验,发现BERTEmbedding中的layer_nums参数越大,准确率越高.layer_nums代表了,BERT的输入层,这个越大代表输出的特征表达越好,所以准确率升高,这么理解对吗?

**Comment by BrikerMan** [comment]
理解对的，layer_nums 表示要取 BERT 最后的基层的特征作为这个输入的特征。根据论文使用 4 层的效果和 fine-tune 差不多，所以默认用了 4 层。
层数越多，特征越全越准，但是特征维度 = layer_nums * 768。所以数字越大，维度越大，运算越慢。这个就需要根据需求权衡了。

**Comment by aguang1201** [comment]
@BrikerMan 感谢大神的指教啊，还想再问一下，那最多能指定到多少呢？

**Comment by BrikerMan** [comment]
> @BrikerMan 感谢大神的指教啊，还想再问一下，那最多能指定到多少呢？

这个我还没测试过... 不过，最多 4 层就差不多了，也没必要一味增加呀。原始论文建议也是 4 层。
> 论文倒数第二段： The numbers in the left part of the table represent the probabilities of the specific strategies used during MLM pre-training (BERT uses 80%, 10%, 10%). The right part of the paper represents the Dev set results. For the feature-based approach, we concatenate the last 4 layers of BERT as the features, which was shown to be the best approach in Section 5.3.

**Comment by aguang1201** [comment]
@BrikerMan 谢谢。我测试的时候都已经加到10层了，性能还是有提升的，不知道是不是巧合，另外我发现trainable设置乘false，性能更容易提升，设置成true反而性能越训越低。是不是对BERT的finetuning不是那么容易训啊

**Comment by BrikerMan** [comment]
fine-tuning 时候学习率需要非常小，否则会破坏原先学到的知识。一般情况，直接 feature-extraction 即可。

**Comment by aguang1201** [comment]
@BrikerMan 嗯嗯，是的。我的lr已经设置的蛮小了0.0001.感谢你的耐心回复。
