### ISSUE TITLE
[Question] Better code completion for loaded model

### ISSUE THREAD

**Issue by wxy521131418** [BrikerMan/Kashgari#248]
大神您好，在做多分类预测的时候，我看您封装的predict只能输出最大概率对应的那个类别，但是不能输出最大概率值是多少

**Comment by BrikerMan** [comment]
Just use `predict_top_k_class` instead of `predict`. Here is the docs: https://kashgari.bmio.net/api/tasks.classification/#predict95top95k95class

**Comment by wxy521131418** [comment]
我在建立模型是可以用这个predict_top_k_class方法的，
但是在使用kashgari.utils.load_model加载模型的时候就没有predict_top_k_class这个方法了

**Comment by BrikerMan** [comment]
额，不应该啊，加载的模型是没有代码提示还是调用了会报错？

**Comment by wxy521131418** [comment]
![图片](https://user-images.githubusercontent.com/32291786/65404175-0ebfc980-de0a-11e9-829b-d2466e23319c.png)

**Comment by BrikerMan** [comment]
哦哦，这个是加载的模型类型被判断为其基类导致的，其实有的。你可以直接使用，代码补全我看看有没有什么办法解决。

**Comment by wxy521131418** [comment]
嗯嗯，直接用是可以的，谢谢大神~太方便了
