### ISSUE TITLE
[Question] bertembedding层的细节问题

### ISSUE THREAD

**Issue by buptzcW** [BrikerMan/Kashgari#249]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:linux
- Python Version:3.6
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question
我想在BiLSTM中使用bertembedding，然后想问一下在model.fit中输入x_input仅需要basicTokenize一下就可以了吗？我想自己写一个data_generator，所以我的generator的输出形式应该时什么样子的？另外，如果我想在bertembedding中使用上下文，应该怎么设置呢，谢谢
[A clear and concise description of what you want to know.]

**Comment by BrikerMan** [comment]
1. 使用 BERTEmbedding().tokenizer，这个根据你是用的模型的词表生成的 Tokenizer. 输入 tokenize 后的 x 到 fit 方法即可。
2. 自己用 generator 可能比较麻烦一些，因为你还需要考虑你的 x,y 转对应的张量等操作。具体可以看 `model.fit` 方法的实现。其实本来就是使用 generator 去训练，所以直接 fit 就够了。
3. 上下文没太明白...

**Comment by buptzcW** [comment]
@BrikerMan 谢谢回复。因为您的generator中对数据进行了shuffle，而这个参数没有暴露在fit的接口上，所以我不好对shuffle进行False设置。然后，今天我又遇到一个问题就是：您的bertembedding层有一个参数variable并不能使用……，所以没有办法实现每个batch的长度按照batch中最大的长度来padding，想问一下这要怎么办呢

**Comment by BrikerMan** [comment]
1. shuffle 0.5.4 版本增加一下，作为可配置参数。目前可以自己重写迭代器实现。
2. variable 这个是实验性功能，其实不太建议使用。因为实际测试发现由于你的 batch 里面的补全和你实际与测试后的补全不一致导致结果准确度没有统一补全时候好。

**Comment by buptzcW** [comment]
@BrikerMan 谢谢指导。如果我非要尝试这种方法的话，我重写class BERTEmbedding，然后将图中代码的sequence_length设置为None是不是就行了？
![image](https://user-images.githubusercontent.com/33115565/65491759-4306b900-dee2-11e9-9953-83f8edd62635.png)

**Comment by BrikerMan** [comment]
是的

**Comment by buptzcW** [comment]
@BrikerMan thanks alot

**Comment by buptzcW** [comment]
@BrikerMan 大佬，这里又出来了一个新问题，就是在model.compile阶段，我给compile传递自己的优化器和metrics就会报错:
  
 
![1569421039(1)](https://user-images.githubusercontent.com/33115565/65609462-644ece80-dfe2-11e9-9373-132c69fc9302.jpg)

**Comment by buptzcW** [comment]
~/.conda/envs/py3.6/lib/python3.6/site-packages/tensorflow/python/keras/backend.py in set_value(x, value)
   3022           (of the same shape).
   3023   """
-> 3024   value = np.asarray(value, dtype=dtype(x))
   3025   if ops.executing_eagerly_outside_functions():
   3026     x.assign(value)

~/.conda/envs/py3.6/lib/python3.6/site-packages/numpy/core/numeric.py in asarray(a, dtype, order)
    536 
    537     """
--> 538     return array(a, dtype, copy=False, order=order)
    539 
    540 

ValueError: setting an array element with a sequence.

**Comment by BrikerMan** [comment]
复现代码呢？

**Comment by buptzcW** [comment]
@BrikerMan 我想采取的策略是使用分层设置学习率和RAdam优化器，采取了keras版本的[https://github.com/CyberZHG/keras-lr-multiplier](url)[https://github.com/CyberZHG/keras-radam](url)就报错了，代码如下：
layer_lr = {'bidirectional':100.0,'dense':100.0}

optimizer = LRMultiplier(RAdam(learning_rate = 1e-4,
                               total_steps = total_steps,
                               warmup_proportion = 0.1,
                               min_lr = 1e-5
                              ),layer_lr)

model.build_model(train_x,train_y,valid_x,valid_y)
model.compile_model(**params)

**Comment by buptzcW** [comment]
@BrikerMan 抱歉写漏了一一些信息，params就是metrics和optimizer的字典，demo就是[https://eliyar.biz/nlp_train_and_deploy_bert_text_classification/](url)

**Comment by BrikerMan** [comment]
这里需要注意一下一个细节，我们使用的是 `tf.keras`，所以在引入 Keras RAdam 之前设定需要 [环境变量](https://github.com/CyberZHG/keras-radam#use-tfkeras-or-tf-20) 或者先引入 kashgari 再引入别的 optimizer。应该就可以解决。

**Comment by buptzcW** [comment]
@BrikerMan 感谢大佬指点，修改环境变量可以解决radam的兼容问题，但是分层学习率keras_lr_multiplier加上去之后还是会提示相同的错误，

**Comment by BrikerMan** [comment]
这个就得看看原仓库是否支持 tf.keras 了。┓( ´∀` )┏

**Comment by buptzcW** [comment]
从这个优化器的backend.py来看，应该是支持的，😭
import os

__all__ = [
    'keras', 'utils', 'activations', 'applications', 'backend', 'datasets', 'engine',
    'layers', 'preprocessing', 'wrappers', 'callbacks', 'constraints', 'initializers',
    'metrics', 'models', 'losses', 'optimizers', 'regularizers', 'TF_KERAS', 'EAGER_MODE'
]

TF_KERAS = False
EAGER_MODE = False

if 'TF_KERAS' in os.environ and os.environ['TF_KERAS'] != '0':
    import tensorflow as tf
    from tensorflow.python import keras
    TF_KERAS = True
    if 'TF_EAGER' in os.environ and os.environ['TF_EAGER'] != '0':
        if int(tf.version.VERSION.split('.')[0]) < 2:
            import tensorflow as tf
            tf.enable_eager_execution()
        EAGER_MODE = True
else:
    import keras
