### ISSUE TITLE
大佬 微信群进不去了，得需要别人拉进去

### ISSUE THREAD

**Issue by zxyza** [BrikerMan/Kashgari#251]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[A clear and concise description of what you want to know.]

**Comment by BrikerMan** [comment]
<img width="659" alt="WeChatbd1b7d22dbff90adcc5a842167b784af" src="https://user-images.githubusercontent.com/9368907/65664554-21d1d400-e06c-11e9-93ff-21d20a44d6a4.png">

加群管理员入群~
