### ISSUE TITLE
Can't run model.predict with bert embedding

### ISSUE THREAD

**Issue by MattHuntebrinker** [BrikerMan/Kashgari#260]
- [x ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Mac OS
- Python Version: 3.6

### What

I've looked through the docs and issues, and can't seem to find the fix for bert specific prediction. 

Model is trained and i'm trying to predict. 

`text = "can the model predict me"
text = text.split(' ')
tensor = model.embedding.process_x_dataset([text})
`
and I get the error 

> ufunc 'add' did not contain loop with signature matching type dtype ('U11') ('U11') ('U11')

I've tried to run 
`tensor = [{ "Input-Token:0" : i.tolist(), "Input-Segment:0" : np.zeros(i.shape).tolist() } for i in tensor]
 `
but it's saying the model.predict(text) doesn't like dict, only list.

### Reproduce

running model.predict(tensor) with the input tensor above will reproduct the code. 

### Other Comment

If there is anything else I can help with, please let me know. Thank you for all your work on this project!

**Comment by BrikerMan** [comment]
Could you provide a shared colab to reproduce this issue?

**Comment by MattHuntebrinker** [comment]
https://colab.research.google.com/drive/1yRDY-OHMVpab3bS-DrXi5ftlktGHLQ_0

**Comment by MattHuntebrinker** [comment]
After working on this issue today, I was able to tokenize the string, and process the text, but with a sigmoid activation function, the highest confidence was .0022, with test and validation accuracy during training reaching over .998
