### ISSUE TITLE
[Question] Using it with glove?

### ISSUE THREAD

**Issue by vprelovac** [BrikerMan/Kashgari#267]
## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

- [X ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [X ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- Google Collab

## Question

I love the ease of use of Kashgari, and were able to run it with Bert Embeddings successfully.

I would like to use glove.6B.100d embeddings but from the documentation it is not clear how to:
- load these embeddings
- preprocess text properly

**Comment by BrikerMan** [comment]
You need to convert glove model to gensim model, then you can use it with Kashgari. Then save the gensim model with `model.wv.save_word2vec_format` function.

Here is the document about convert: https://radimrehurek.com/gensim/scripts/glove2word2vec.html

**Comment by vprelovac** [comment]
@BrikerMan And how to properly process sentences?

Would you consider adding this to documentation the same like you have for Bert? https://kashgari.bmio.net/embeddings/bert-embedding/

**Comment by BrikerMan** [comment]
> https://kashgari.bmio.net/embeddings/bert-embedding/

You need to tokenize sentences to match the Embedding you are using. Since there are many kinds of Word Embeddings with different tokenize policy, you need to figure this out. Sorry.
