### ISSUE TITLE
bert_embed = BERTEmbedding('<PRE_TRAINED_BERT_MODEL_FOLDER>',task=kashgari.LABELING,sequence_length=100） 执行报错

### ISSUE THREAD

**Issue by xiaonian0430** [BrikerMan/Kashgari#268]
WARNING: Entity <bound method FeedForward.call of <keras_position_wise_feed_forward.feed_forward.FeedForward object at 0x7fb93d5bb668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method FeedForward.call of <keras_position_wise_feed_forward.feed_forward.FeedForward object at 0x7fb93d5bb668>>: AssertionError: Bad argument number for Name: 3, expecting 4

**Comment by xiaonian0430** [comment]
请问，这是什么原因？

**Comment by BrikerMan** [comment]
请按照 issue 模板提问~

**Comment by candystar** [comment]
请问怎么解决的？我也遇到这个问题

**Comment by mike-sino** [comment]
我也遇到这个问题了，只要加载bert 就出这个问题
