### ISSUE TITLE
[Question]多标签文本分类，模型保存后，重新加载预测出的数据为单标签的

### ISSUE THREAD

**Issue by caizp91** [BrikerMan/Kashgari#270]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [ Linux]:
- Python Version:3.6.2
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

多标签文本分类，模型保存后，重新加载预测出的数据为单标签的，训练时，设置了multi_label=True，模型保存重新加载后 model.embedding.processor.multi_label =False ;
下面这个是我的加载模型方式:
model = kashgari.utils.load_model(self.model_dir)
请帮我解决下困惑，谢谢

**Comment by BrikerMan** [comment]
更新一下版本~ 已修复这个问题

**Comment by caizp91** [comment]
0.5.4版本吗？今天我更新了下，好像也是一样的，预测出来的也是单标签
