### ISSUE TITLE
[Question] 加载模型报错：ValueError: Unknown layer: BiLSTM_CRF_Model

### ISSUE THREAD

**Issue by harry771** [BrikerMan/Kashgari#274]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS :Linux
- Python Version :3.6
- requirements.txt:

```txt
Kashgari
```

## Question

[A clear and concise description of what you want to know.]
请问如何加载保存的模型文件？fine-tune完的模型save成功之后，我使用这小段代码把模型加载进来
`from tensorflow import keras
from tensorflow.keras import layers 

with open('bert_blstm_crf.h5/model_info.json') as json_file:
    json_config = json_file.read()
new_model = keras.models.model_from_json(json_config)
new_model.load_weights('bert_blstm_crf.h5/model_weights.h5')`
其中，bert_blstm_crf.h5是我的保存路径，但载入时报了这个错误：
ValueError: Unknown layer: BiLSTM_CRF_Model
好像tf.keras对这个layer并不能识别。

**Comment by lsgrep** [comment]
Hi, 你用的Kashgari版本是什么？

**Comment by harry771** [comment]
我使用的是1.0.0版本，但如果我使用这段代码则是可以加载的
`import kashgari

model = kashgari.utils.load_model('bert_blstm_crf.h5')`
我发现在这个教程里说了保存方法：https://eliyar.biz/nlp_train_and_deploy_bert_text_classification/
  @lsgrep 还有一个问题是这个模型是否可以直接转为pb文件用于线上部署呢，我们现在的线上环境和教程里面提的差别比较大。

**Comment by BrikerMan** [comment]
需要使用内置方法加载，如果需要自定义加载方法，可以查看源代码进行修改。

支持使用 TF Serving 部署，请看文档 https://kashgari.bmio.net/advance-use/tensorflow-serving/

**Comment by harry771** [comment]
ok,@BrikerMan谢谢答复，请问有打算增加对albert的支持吗？

**Comment by BrikerMan** [comment]
坐等 keras-bert 支持 albert 呢，可以在这里跟进进度 https://github.com/CyberZHG/keras-bert/issues/159

**Comment by harry771** [comment]
我记得有一个版本的keras倒是支持了https://github.com/bojone/bert4keras，加油Briker，期待更好的kashgari。
