### ISSUE TITLE
How to specify the bert model path? What is it expecting?

### ISSUE THREAD

**Issue by urvishp80** [BrikerMan/Kashgari#277]
I am trying to use this library for my personal project. Here is what I am doing in the code

```from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.labeling import BiGRU_Model
from kashgari.corpus import ChineseDailyNerCorpus
import kashgari

import os
cwd = os.getcwd()

print(os.path.join(cwd, 'uncased_L-12_H-768_A-12'))

bert_embedding = BERTEmbedding(os.path.join(cwd, 'uncased_L-12_H-768_A-12/'), sequence_length=30)
model = BiGRU_Model(bert_embedding)

train_x, train_y = ChineseDailyNerCorpus.load_data()
model.fit(train_x, train_y)
```
It is giving error all the time like this 

```WARNING:root:CUDA GPU available, you can set `kashgari.config.use_cudnn_cell = True` to use CuDNNCell. This will speed up the training but will make model incompatible with CPU device.
WARNING:root:CuDNN enabled, this will speed up the training, but will make model incompatible with CPU device.
D:\Pirimid\bert_exp\uncased_L-12_H-768_A-12
Traceback (most recent call last):
  File "bert_kashgari.py", line 11, in <module>
    bert_embedding = BERTEmbedding(os.path.join(cwd, 'uncased_L-12_H-768_A-12/'), sequence_length=30)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\embeddings\bert_embedding.py", line 73, in __init__
    from_saved_model=from_saved_model)
  File "C:\Users\Urvish\Envs\tf_1_14\lib\site-packages\kashgari\embeddings\base_embedding.py", line 78, in __init__
    raise ValueError()
ValueError```

What I am doing wrong here? Please, help.

**Comment by BrikerMan** [comment]
You need to add task param to BERTEmbedding init function. [Here is the doc](https://kashgari.bmio.net/embeddings/bert-embedding/).
