### ISSUE TITLE
[Question]  Can I Use Kashgari text labelling feature in hierarchical text classification

### ISSUE THREAD

**Issue by sld** [BrikerMan/Kashgari#279]
Hi, thanks for the great lib!

I have a sentence with hierarchical labels, e.g. 
- sentence: "I am living on Planet Earth"
- labels: ["category1", "subcategory1", "subsubcategory1"].

So the labels has hierarchical structure ("category1" => "subcategory1" => "subsubcategory1").

Is it possible to use sentence labelling Kashgari BLSTM + CRF model for such hierarchical text classification task?

**Comment by BrikerMan** [comment]
No, so far you can't label hierarchical structure using kashgari. Sorry.
