### ISSUE TITLE
[Question] 如何使用自己的数据集来做NER

### ISSUE THREAD

**Issue by LightingFx** [BrikerMan/Kashgari#28]
我的数据集和ChinaPeoplesDailyNerCorpus中的人民日报数据格式是一样的，但实体类别不同（15种），用get_sequence_tagging_data处理完自己的数据直接用于输入就可以了吗？需要自己添加tag字典嘛？
我用我的数据集在原始的BERT模型上跑的acc只有0.67，昨天用您的BLSTMCRF模型crf_acc能达到0.91，该如何判断是我那儿出错呢，还是BLSTMCRF模型效果确实好呢？

**Comment by BrikerMan** [comment]
直接把输入替换掉即可，不需要做任何多余的操作。crf_acc 如果觉得过高，可以训练完成后调用 `model.evaluate` 方法在测试集上看测试集上具体的表现。

**Comment by LightingFx** [comment]
> 直接把输入替换掉即可，不需要做任何多余的操作。crf_acc 如果觉得过高，可以训练完成后调用 `model.evaluate` 方法在测试集上看测试集上具体的表现。

由于测试集数据比较零散，准确率只有0.3，我用model.evaluate试了一下验证集的数据，结果F1只有0.62，但在训练时val_crf_acc能有0.92.，所以实际效果应该是不太好？有什么方法可以优化一下？

**Comment by BrikerMan** [comment]
这个其实我也没有更好的建议，我觉得第一步使用你的代码跑一边 ChinaPeoplesDailyNerCorpus，看看能不能达到 https://eliyar.biz/nlp_chinese_bert_ner/ 这篇文章的效果。然后如果 BERT 的效果在你的数据集上并不够足够好，那可以考虑使用词向量 + 词级别分词输入看看效果如何。

**Comment by LightingFx** [comment]
> 这个其实我也没有更好的建议，我觉得第一步使用你的代码跑一边 ChinaPeoplesDailyNerCorpus，看看能不能达到 https://eliyar.biz/nlp_chinese_bert_ner/ 这篇文章的效果。然后如果 BERT 的效果在你的数据集上并不够足够好，那可以考虑使用词向量 + 词级别分词输入看看效果如何。

ChinaPeoplesDailyNerCorpus的数据集效果不错，可能BERT在我数据集上的表现不佳，我试试其他方法，感谢您的回复。

**Comment by BrikerMan** [comment]
哦哦，那估计是，那就尝试一下基于词的标注吧，不过这个需要先分词。我们目前生产环境序列标注也是 jieba 分词后再进行序列标注。

**Comment by yuyunfeng666** [comment]
请问一下，
`from kashgari.tasks.labeling import BiLSTM_Model
from kashgari.embeddings import BertEmbedding
from kashgari.corpus import ChineseDailyNerCorpus

train_x, train_y = ChineseDailyNerCorpus.load_data('train')
valid_x, valid_y = ChineseDailyNerCorpus.load_data('valid')
test_x, test_y = ChineseDailyNerCorpus.load_data('test')
print(train_y[0])


bert_embed = BertEmbedding('Kashgari/bert-base-chinese')
model = BiLSTM_Model(bert_embed, sequence_length=100)

# model.fit(train_x, train_y, valid_x, valid_y)
model.evaluate(test_x, test_y)`
报错为‘KeyError: '[PAD]'’
这是为啥呀
