### ISSUE TITLE
多标签文本分类，metrics应该怎么设置

### ISSUE THREAD

**Issue by wangdong1992** [BrikerMan/Kashgari#280]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[A clear and concise description of what you want to know.]
你好，我在使用keras进行多标签文本分类时，查看了许多文档都说，最后的dense层使用sigmoid激活函数，loss使用binary_crossentropy，但是metrics使用'accuracy'时，准确率会虚高，因为keras默认的accuracy计算方式造成的，请问Kashgari对于多标签分类是如何处理的？谢谢

**Comment by BrikerMan** [comment]
使用了默认 accuracy 方法，可能存在同样的问题~
