### ISSUE TITLE
[BUG] 序列标注任务加载BERTEmbedding遇到问题

### ISSUE THREAD

**Issue by candystar** [BrikerMan/Kashgari#283]
WARNING: Entity <bound method TokenEmbedding.call of <keras_bert.layers.embedding.TokenEmbedding object at 0x7f686bcdf940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method TokenEmbedding.call of <keras_bert.layers.embedding.TokenEmbedding object at 0x7f686bcdf940>>: AssertionError: Bad argument number for Name: 3, expecting 4

**Comment by mike-sino** [comment]
只要加载bert就出这个错误，和上边一模一样，请问是什么原因啊，谢谢🙏

**Comment by mike-sino** [comment]
Uninstalled gast and pip install gast==0.2.2 works for me !
