### ISSUE TITLE
[Feature request] 模型保存和模型导入的效率问题

### ISSUE THREAD

**Issue by WEN-MIN** [BrikerMan/Kashgari#285]
你好，感谢发布这个方便使用的库，我在使用中遇到模型导入效率低和占用资源高的问题。
具体的是：docker镜像导入一个训练好的模型是比较正常的，导入完成时间在一分钟以内，但是，若同时在一个镜像里面导入7个训练好的模型，模型加载的时间变得很长，接近30分钟左右，并且，CPU和内存的占有率很高，请问有什么比较高效的方法同时快速导入多个模型，并且CPU的占有率不是那么的高？

**Comment by BrikerMan** [comment]
没明白如何导入？
