### ISSUE TITLE
事先训练好命名实体模型后，通过tensorflow-server 接口响应的结果比较慢（平均需要800~900ms），有什么解决办法吗？

### ISSUE THREAD

**Issue by xiaonian0430** [BrikerMan/Kashgari#290]
r = requests.post("http://localhost:8501/v1/models/bgru:predict", json={"instances": tensor.tolist()})
preds = r.json()['predictions']

**Comment by sevenold** [comment]
maybe you can try the grpc channel

**Comment by BrikerMan** [comment]
请问使用什么配置的机器做推断？

**Comment by xiaonian0430** [comment]
> 请问使用什么配置的机器做推断？

我使用的环境配置如下：
## Environment

- Centos 系统
- 2核CPU
- 4G内存
- 无GPU

**Comment by BrikerMan** [comment]
目前我能想到的办法就是可以在 CentOS 上编译 tf-serving 来提速，可以参考 https://hackernoon.com/how-we-improved-tensorflow-serving-performance-by-over-70-f21b5dad2d98
