### ISSUE TITLE
BERT fine tuning only last 'n' layers

### ISSUE THREAD

**Issue by rhamnett** [BrikerMan/Kashgari#291]
Hi, thanks for a wonderful library. I am using the BERT embeddings and I noticed there is a setting when initialising the BERTembedding  - trainable=True (ref https://kashgari.bmio.net/embeddings/bert-embedding/).

However when I set this the model makes all 300m parameters get trained.

There is a Keras implementation of BertLayer ( see https://gist.github.com/rhamnett/493cda4e35800fce650bbf127b099701 ) where you can set n_fine_tune layers which simply allows the last few layers - this is then much faster and you get the benefit from the frozen upper layers.

Can someone kindly explain how I can achieve this within Kashgari.

**Comment by rhamnett** [comment]
@BrikerMan would you be so kind as to advise? thanks

**Comment by urvishp80** [comment]
Any update on this as I want to do the same and could not find any better way. @rhamnett @BrikerMan

**Comment by rhamnett** [comment]
I will see if i can get time to implement something next week.

**Comment by sandeshbhatjr** [comment]
Can I implement this part?

**Comment by BrikerMan** [comment]
> Can I implement this part?

sure thing～

**Comment by rhamnett** [comment]
@sandeshbhatjr have you implemented this? If so can you provide a pull request?

**Comment by rhamnett** [comment]
@BrikerMan any ideas on this?
