### ISSUE TITLE
[Question] why i  can't install !pip install 'kashgari>=2.0.0' in kaggle kernel

### ISSUE THREAD

**Issue by Klauszhao** [BrikerMan/Kashgari#293]
## Check List
i haved search the quention but i can't fix it 

## Environment

- OS [e.g. Mac OS, Linux]: netebook
- Python Version: 3.6
- requirements.txt:

## Question

the error info:

[A clear and concise description of what you want to know.]
ERROR: Could not find a version that satisfies the requirement kashgari>=2.0.0 (from versions: 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.4, 0.2.6, 1.0.0)
ERROR: No matching distribution found for kashgari>=2.0.0

but i can !pip install 'kashgari>=1.0.0' ，the tf .version = 2.0.0

**Comment by BrikerMan** [comment]
Because we have not released 2.0.0 yet. You can use 1.0.0 with TF 1.14

**Comment by Klauszhao** [comment]
> Because we have not released 2.0.0 yet. You can use 1.0.0 with TF 1.14

ok , maybe i  could do something for that, hah
