### ISSUE TITLE
Can not use exported model by creating custom API for loading frozen graph.

### ISSUE THREAD

**Issue by urvishp80** [BrikerMan/Kashgari#296]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**
- [x ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Windows 10
- Python Version: 3.7
- GPU: Nvidia 2060 RTx
- requirements.txt: 

```
numpy==1.16.2
tqdm==4.31.1
pandas==0.24.2
kashgari==1.0.0
scikit_learn==0.21.3
tensorflow_gpu==1.14
protobuf==3.10.0
```

## Question
I used the `utility` function `convert_to_saved_model` to export the model for serving using `tensorflow` using my local machine. I am loading the graph using following code and I am getting error while doing it. The code for loading the graph is this 

```
def openGraph():
        graph = tf.Graph()
        graphDef = tf.GraphDef()
        with open(model_path, "rb") as graphFile:
            graphDef.ParseFromString(graphFile.read())

        with graph.as_default():
            tf.import_graph_def(graphDef)

        return graph
```
I am providing the model path as `data/BERT/1/saved_model.pb` and getting following error

```
WARNING:tensorflow:From D:\Pirimid\mail-parsing\models_parser\text_predictor.py:35: FastGFile.__init__ (from tensorflow.python.platform.gfile) is deprecated and will be removed
in a future version.
Instructions for updating:
Use tf.gfile.GFile.
WARNING:tensorflow:From D:\Pirimid\mail-parsing\models_parser\text_predictor.py:36: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

Traceback (most recent call last):
  File "main.py", line 13, in <module>
    predictor = TextPredictor('data/BERT/1/saved_model.pb')
  File "D:\Pirimid\mail-parsing\models_parser\text_predictor.py", line 15, in __init__
    self.__model = self.__load_model()
  File "D:\Pirimid\mail-parsing\models_parser\text_predictor.py", line 37, in __load_model
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message
```
I found out few issues related to this on Tensorflow githiub page but none of them was able to provide the solution to it. I think the issues is in the saved model itself or the version of `protobuf` has something wrong. How can I load the graph using the above function that I have created? Do you think there can be version conflict?

**Comment by BrikerMan** [comment]
Maybe try to use tensorflow-serving with a docker image to check out the pd file?

**Comment by urvishp80** [comment]
@BrikerMan I am not able to run with the docker. I do not know how to do it actually, I tried a few online tutorials but after cloning the docker image I am not able to do anything. I tried some command like this 
```
docker run -p 8501:8501 --mount type=bind,source=absolute_path_to_model_directory,target=model_directory_bert_1 \
  -e MODEL_NAME=my_model -t TensorFlow/serving
```
What do you think is wrong with this? also, can you provide some good resource to run tf-serving with docker?

**Comment by BrikerMan** [comment]
If you are not familiar with docker, maybe you can try the load model on [Colab](https://colab.research.google.com/) or Linux Environments. Windows always have some wired environment issues. I don't know how to help too.

**Comment by urvishp80** [comment]
`https://drive.google.com/drive/folders/1LmtT926EOinNMgtYT0QvfKdglLcroPU1?usp=sharing` Here is the model. I ave uploaded on the drive. I am trying the colab meanwhile if you can run this using the docker then it will be good as I have to serve it at ay cost. Thanks.

**Comment by urvishp80** [comment]
Hello, @BrikerMan have you got any luck with this? I created the colab but actually it is the same code I posted above without any change, also the model I gave is the same so no change in that as well. Let me know if you have any updates? On my side, I tried different things like changing the version of the protobuf but that did not work at all.

**Comment by urvishp80** [comment]
I was able to solve the issue with the following code for loading the model 
```
with tf.Session(graph=tf.Graph()) as sess:
        tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], "data/bert/4/")
        graph = tf.get_default_graph()
return graph
```

The thing is the function in `utils` uses `tf.saved_model.save` function to save the model for serving hence to load the model we have to use the `tf.saved_model.loader.laod` method and not the method with the ` graphDef.ParseFromString(graphFile.read())`. This can be changed into the `util` module too so that there can be a simple API for loading the model for inferencing. What do you think of this @BrikerMan ? Should I create such function into utils to do inferencing directly using the exported model? It can be there in `tf 2.0` as well to help people do the inferencing directly without use of serving.

**Comment by BrikerMan** [comment]
@urvishp80 In tensorflow2.0, SavedModel is the default model format. So you can use it for inferencing. You can use SavedModel on 1.x version by calling `tf.saved_model.loader.laod` right? If so, no need to change.

**Comment by urvishp80** [comment]
@BrikerMan yeah, you are right. I was able to use `tf.saved_model.loader.laod` to load the model. Closing the issue now.
