### ISSUE TITLE
[Question] 使用keras的callbacks csvlogger没有打印出来结果，是不能使用callbacks吗？

### ISSUE THREAD

**Issue by Juntai** [BrikerMan/Kashgari#30]
使用了BERTEmbedding+BLSTMCRFModel

csv_logger = CSVLogger('/export/public/gongjuntai/bert_ft/csv/csv_logger.csv', separator=',', append=True)
model.fit(x_train = x_train, y_train = y_train,
          x_validate = x_validate,
          y_validate = y_validate,
          batch_size = 64,
          epochs = 2,
          labels_weight = None,
          default_labels_weight = 50.0,
          callbacks = [csv_logger])

**Comment by BrikerMan** [comment]
use

```python
model = CNNModel()
model.fit(x_train = x_train, y_train = y_train,
    x_validate = x_validate,
    y_validate = y_validate,
    batch_size = 64,
    epochs = 2,
    labels_weight = None,
    default_labels_weight = 50.0,
    fit_kwargs={'callbacks': [csv_logger]})
```

**Comment by Juntai** [comment]
谢谢！我试一下
