### ISSUE TITLE
[Feature Request] Add regression task. 

### ISSUE THREAD

**Issue by urvishp80** [BrikerMan/Kashgari#301]
**Is your feature request related to a problem? Please describe.**
There are many problems in NLP which require the model to predict the floating-point number just like regression. For example, sentiment analysis, or predicting some score like how much the text data is good. Another example is [this competition on kaggle](https://www.kaggle.com/c/google-quest-challenge/submissions) where we have to predict the score between 0 to 1 using text data.
This will make the framework more production and research-oriented where we can play with anything. 

**Describe the solution you'd like**
A clear solution would be adding one more task jut like `Labelling` and `Classification`. It can be the 3rd task Kashgari that Kashgari supports. 

**Describe alternatives you've considered**
An alternative could be adding new head on the existing model and defining the new loss with the optimizer to make the predictions using linear activation. It would be easy to do if someone is good with defining custom models and architecture. But, someone new will struggle.

**Comment by BrikerMan** [comment]
Check the new Scoring task, I think it will solve the issue.

**Comment by urvishp80** [comment]
Sure. I will. Does it included in the release or will be there in 2.0?

**Comment by BrikerMan** [comment]
> Sure. I will. Does it included in the release or will be there in 2.0?

This task will release in 1.1.0 version.
