### ISSUE TITLE
[Question] Load model on CPU

### ISSUE THREAD

**Issue by 4kssoft** [BrikerMan/Kashgari#302]
I trained BiLSTM_CRF_Model on GPU (colab) and save it. I possible to load this model on device without GPU?
I have an error on loading:
`No OpKernel was registered to support Op 'CudnnRNNV2' used by node layer_blstm/forward_cu_dnnlstm_1/CudnnRNNV2`

**Comment by BrikerMan** [comment]
Update to the latest version `kashgari==1.0.0` and set `kashgari.config.use_cudnn_cell = False` (False is the default value). Then you can predict on CPU.

**Comment by 4kssoft** [comment]
Thanks. It works. I just had to re-train the model with this setting
