### ISSUE TITLE
使用kashgari.utils.load_model 加载模型进行标签预测会报错[BUG] 

### ISSUE THREAD

**Issue by Gjh9508** [BrikerMan/Kashgari#304]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [y ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [y ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:  Centos(云服务器环境)
- Python Version: 3.6
- requirements.txt:  
- 运行环境：tf1.14，kashgari 1.0.0

```txt
import pandas as pd
import numpy as np
import kashgari
from kashgari.tasks.classification import BiLSTM_Model
from kashgari.processors import ClassificationProcessor
from kashgari.embeddings import BareEmbedding
import logging
```

### What
```
model.save('/output/xxx')
kashgari.utils.load_model 
loaded_model.predict(valid_x[:40])
```
模型在save之前可以正常使用，但是重新加载模型进行标签预测，会报错。报错信息如下：
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-10-8ca42a11a04b> in <module>
----> 1 loaded_model.predict(valid_x[:40])

/usr/local/lib/python3.6/dist-packages/kashgari/tasks/classification/base_model.py in predict(self, x_data, batch_size, multi_label_threshold, debug_info, predict_kwargs)
     78                 pred = pred.argmax(-1)
     79 
---> 80             res = self.embedding.reverse_numerize_label_sequences(pred)
     81             if debug_info:
     82                 logging.info('input: {}'.format(tensor))

/usr/local/lib/python3.6/dist-packages/kashgari/embeddings/base_embedding.py in reverse_numerize_label_sequences(self, sequences, lengths)
    215                                          sequences,
    216                                          lengths=None):
--> 217         return self.processor.reverse_numerize_label_sequences(sequences, lengths=lengths)
    218 
    219     def __repr__(self):

/usr/local/lib/python3.6/dist-packages/kashgari/processors/classification_processor.py in reverse_numerize_label_sequences(self, sequences, **kwargs)
     82     def reverse_numerize_label_sequences(self, sequences, **kwargs):
     83         if self.multi_label:
---> 84             return self.multi_label_binarizer.inverse_transform(sequences)
     85         else:
     86             return [self.idx2label[label] for label in sequences]

AttributeError: 'NoneType' object has no attribute 'inverse_transform'
```

### Reproduce

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by BrikerMan** [comment]
谢谢反馈问题，已修复。
可以按照以下方案安装修复分支测试一下，这个分支过两天作为下一版本发布。
麻烦测试完反馈一下结果。

```bash
pip uninstall -y kashgari
pip install git+https://github.com/BrikerMan/Kashgari@fix/multi_label_classification_loading
```

**Comment by Gjh9508** [comment]
问题已经解决，谢谢！

**Comment by sly123197811** [comment]
您好，我又遇到了相同问题，请问还没有作为最终版本修复吗，2020年5月14日11:22:18

**Comment by sly123197811** [comment]
> 谢谢反馈问题，已修复。
> 可以按照以下方案安装修复分支测试一下，这个分支过两天作为下一版本发布。
> 麻烦测试完反馈一下结果。
> 
> ```shell
> pip uninstall -y kashgari
> pip install git+https://github.com/BrikerMan/Kashgari@fix/multi_label_classification_loading
> ```

您好，我最近clone的kashgari人仍然存在相同的问题，您不是说作为最终版本修复了吗？

**Comment by BrikerMan** [comment]
@sly123197811 请提供版本号信息和最小复现代码。

**Comment by sly123197811** [comment]
> @sly123197811 请提供版本号信息和最小复现代码。

Python Version: 3.6
运行环境：tf1.14，kashgari-tf 0.5.5，windows10

复现代码：
modelpath = 'models/'
load_model = kashgari.utils.load_model(modelpath)
sample = list(jieba.cut(testdata))
y = load_model.predict([sample])
print(y[0])

问题跟楼主的一样

**Comment by BrikerMan** [comment]
执行以下命令更新到最新版本。

```bash
pip uninstall -y kashgari-tf
pip install kashgari
```

更新日志：https://kashgari.readthedocs.io/about/release-notes.html
