### ISSUE TITLE
[Question] 我在tf2.0下遇到了lstm-crf的loss为负的问题

### ISSUE THREAD

**Issue by Gosicfly** [BrikerMan/Kashgari#310]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:mac
- Python Version:3.7
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[A clear and concise description of what you want to know.]
你好，我是循着另一个issue过来的。我在tf2.0下遇到了lstm-crf的loss为负的问题，请问你知道是什么原因导致的吗？怎么fix呢？

**Comment by BrikerMan** [comment]
请问是 Kashgari 的 crf 么？ 还有根据那个 issue？
我之前用的 CRF 实现确实会出现负数情况，现在简单粗暴的取了绝对值... 还没真正解决这个问题。

**Comment by Gosicfly** [comment]
> 请问是 Kashgari 的 crf 么？ 还有根据那个 issue？
> 我之前用的 CRF 实现确实会出现负数情况，现在简单粗暴的取了绝对值... 还没真正解决这个问题。

我是在pure tf2.0下遇到的这个问题。目前初步解决，根据实验结果猜测是因为tf.keras.layers.Bidirectional的问题，和padding和mask有关，具体关系到unroll这个参数。

biLSTM如果这么定义就会出现loss为负的问题：
`
self.biLSTM = layers.Bidirectional(
            layer=layers.LSTM(hidden_size, return_sequences=True),
            merge_mode='concat'
        )
`
改成如下方式后可修复
`
self.biLSTM = layers.Bidirectional(
            layer=layers.LSTM(hidden_size, return_sequences=True, unroll=True),
            backward_layer=layers.LSTM(hidden_size, return_sequences=True, unroll=False, go_backwards=True),
            merge_mode='concat'
        )
`
