### ISSUE TITLE
[Question] 请问下，如何让该模型的服务稳定运行？

### ISSUE THREAD

**Issue by siyu828** [BrikerMan/Kashgari#319]
## Environment

- OS [CentOS7.3]:
- Python Version: 3.6.2
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

目前使用Kashgari的1.0.0版本提供NER的服务，但是该服务在GPU上运行一段时间后就出现OOM问题挂掉（具体时长取决于并发访问量，在低访问量的情况下没有问题，但是高并发访问的情况下大概率出现）。
请问有没有什么方法可以避免或者解决呢？ 尝试了在CPU的docker环境下去限制资源，在超过资源限制（内存4G）后重启，但是发现实际上并不会触发模型重启，而是在高并发量访问后出现访问延迟剧增的情况（从正常时的2-3s 到2-3分钟，而CPU和内存资源并没有明显变化）。

**Comment by BrikerMan** [comment]
感觉是内存泄漏，请问是直接使用 Kashgari 提供的服务还是使用 TF-serving?

**Comment by siyu828** [comment]
是直接使用Kashgari 提供的Flask服务

**Comment by BrikerMan** [comment]
@siyu828 那么可能就会存在这个问题，建议使用 tf-serving 提供服务。
