### ISSUE TITLE
How to save and load best model? [Question] 

### ISSUE THREAD

**Issue by sylvite** [BrikerMan/Kashgari#331]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Windows
- Python Version: 3.7.2
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

I think this should be a simple question to answer. When running one of your models - BiLSTM - I want to run a few epochs and save the best model, then use the best model to evaluate and make prediction in the test set. When I try to load the best_model, I get a "NotaDirectory" error.

from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model

from kashgari.tasks.classification import BiLSTM_Model

callbacks = [ModelCheckpoint(filepath='best_model.h5',
                             monitor='val_acc', mode='max',
                             save_best_only=True)]

model = BiLSTM_Model()

history = model.fit(X_train, y_train, X_val, y_val,
          epochs=4,
          callbacks=callbacks,
          batch_size = 500)

best_model = kashgari.utils.load_model('best_model.h5')

**NotADirectoryError: [Errno 20] Not a directory: 'best_model.h5/model_info.json'**

However, if I try to save the best_model, it has already been saved, apparently by the callback as I expected.

model.save('best_model.h5')

**FileExistsError: [Errno 17] File exists: 'best_model.h5'**

So is there a way to save the best model and then load it so that I can make predictions from it?

**Comment by sylvite** [comment]
A follow-up question:

I tried to just use the Keras load_model() method to retrieve the best model:

**best_model = load_model('best_model.h5')**


But then when I tried to predict using the best model, it returned an error:

**y_test_predict = best_model.predict(X_test)**


**ValueError: Error when checking input: expected input to have shape (15,) but got array with shape (1,)**

It looks like the best model is expecting the output of the input layer as input, instead of the X_test vector, as if the the input layer is missing from the best model.

This was the structure of the original model I ran. It seems like the best model does not have the InputLayer at the top and is expecting an input of (15,) instead of (1,), which is what I have,

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
================================================================
input (InputLayer)           [(None, 15)]              0         
_________________________________________________________________
layer_embedding (Embedding)  (None, 15, 100)           4941000   
_________________________________________________________________
bidirectional (Bidirectional (None, 256)               234496    
_________________________________________________________________
dense (Dense)                (None, 2)                 514       
================================================================

**Comment by adlinex** [comment]
model_path = os.path.join('model_saved', 'test_classification_checkpoint')
        checkpoint = callbacks.KashgariModelCheckpoint(model_path,
                                                       verbose=1,
                                                       save_best_only=True,
                                                       save_weights_only=False,
                                                       kash_model=model)
        model.fit(train_x, train_y, test_x, test_y, epochs=2, callbacks=[checkpoint])
        model.evaluate(train_x, train_y, 64)

        # load and predict
        from kashgari import utils
        new_model = utils.load_model(model_path)
        print(new_model.predict(train_x[:10]))

this is an example to use the best model
