### ISSUE TITLE
[Question] 序列标注任务怎样获取每个字对应某个label的概率

### ISSUE THREAD

**Issue by yaleimeng** [BrikerMan/Kashgari#332]
## Check List

I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Ubuntu 18.04
- Python Version: 3.6
- requirements.txt:

## Question

我在实体识别任务中使用了BERT接BiLSTM+CRF的方案，但模型简单低predict只能预测出每个字对应的概率最大的标签。
我想获取每个字对应各个label的概率，参考了 #146 ，但是获取的概率都是0或者1。类似这样:
[PAD]	1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
O	0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 
B-Que	0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 0.000 0.000 
I-Que	0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 1.000 
B-Per	0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
I-Per	0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
E-Per	0.000 1.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 
这样是否太极端了? 怎样才能获取浮点数的预测概率呢?

**Comment by BrikerMan** [comment]
这个就是浮点结果，可能任务太简单导致很容易有 100 置信度，你可以用测试语料泡个模型看看就知道了~

**Comment by yaleimeng** [comment]
多谢回复，我后续再用其他语料和模型试试。
