### ISSUE TITLE
Consider adding fine tuning BERT for sequence tagging?

### ISSUE THREAD

**Issue by Das-Boot** [BrikerMan/Kashgari#35]
Currently Kashgari only supports feature-based transfer learning from BERT (Am I right ?). Any plan on adding fine-tuning based module in near future?

**Comment by BrikerMan** [comment]
Yes, Kashgari only supports feature-based transfer learning from BERT. I think it works just fine so far. So I don't have plans to add the fine-tuning based model unless it has some advantage compare to feature-based transfer learning.
