### ISSUE TITLE
[Question] 使用 bert_embedding_v2时，没法设置Trainable=False

### ISSUE THREAD

**Issue by yaleimeng** [BrikerMan/Kashgari#354]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Linux
- Python Version: 3.6.8
- requirements.txt: None

## Question
使用 bert_embedding_v2 载入预训练模型做下游任务时，似乎没法设置Trainable=False。这样会有很多参数参与训练，大大延长询练时间。不知道哪里能不能改一改？

**Comment by BrikerMan** [comment]
已推送到 master 分支，可以安装这个试试
```
pip uninstall -y kashgari && pip install git+https://github.com/BrikerMan/Kashgari
```

**Comment by yaleimeng** [comment]
多谢，问题已解决。

**Comment by BrikerMan** [comment]
已发布 1.1.4 版本~
