### ISSUE TITLE
Cannot import name 'get_file' when use kashgari

### ISSUE THREAD

**Issue by TechSang** [BrikerMan/Kashgari#355]
When I use kashgari on colab building some NER models, I found this problem recently.   
When using ,it reported:
```
----> import kashgari
```
```
      6 from kashgari import macros as k
      7 from typing import Tuple, List
----> 8 from tensorflow.python.keras.utils import get_file
      9 from kashgari import utils
ImportError: cannot import name 'get_file'
```
It was able to be used it normally a few weeks ago

**Comment by BrikerMan** [comment]
Checkout the kashgari and tensorflow versions.

**Comment by TechSang** [comment]
Thank you, I did not notice that colab auto updated the TensorFlow to v2.x.

**Comment by usmaann** [comment]
Hi I m having same issue

I am using below versions 

!pip install kashgari==1.0.0
!pip install tensorflow==1.14 

Still getting the same get_file error

pls advise

**Comment by BrikerMan** [comment]
> Hi I m having same issue
> 
> I am using below versions
> 
> !pip install kashgari==1.0.0
> !pip install tensorflow==1.14
> 
> Still getting the same get_file error
> 
> pls advise

Update to the 1.1.5 version by `pip install kashgari==1.1.5`.

**Comment by usmaann** [comment]
> > Hi I m having same issue
> > I am using below versions
> > !pip install kashgari==1.0.0
> > !pip install tensorflow==1.14
> > Still getting the same get_file error
> > pls advise
> 
> Update to the 1.1.5 version by `pip install kashgari==1.1.5`.

Thanks for your quick reply....

I was able to fix it by using tf=1.15.0 and Kashgari 1.1.5 but getting below error

![image](https://user-images.githubusercontent.com/38275359/88756419-f0072d80-d1a6-11ea-948e-05e7fa5cd594.png)



ImportError: cannot import name 'BertEmbedding' from 'kashgari.embeddings' (/opt/conda/lib/python3.7/site-packages/kashgari/embeddings/__init__.py)

**Comment by bclee232** [comment]
Try BERTEmbedding instead of BertEmbedding

**Comment by Jefffish09** [comment]
Hi @BrikerMan ,
I also get the error "ImportError: cannot import name 'get_file' from 'tensorflow.python.keras.utils'" 
![image](https://user-images.githubusercontent.com/44800122/90731258-0e6ecd80-e2fc-11ea-8c7a-cb1ea2e06ce0.png)

My environment:
tensorflow == 2.3.0
keras == 2.4.3
kashgari == 1.15

How to solve?

**Comment by BrikerMan** [comment]
> Hi @BrikerMan ,
> I also get the error "ImportError: cannot import name 'get_file' from 'tensorflow.python.keras.utils'"
> ![image](https://user-images.githubusercontent.com/44800122/90731258-0e6ecd80-e2fc-11ea-8c7a-cb1ea2e06ce0.png)
> 
> My environment:
> tensorflow == 2.3.0
> keras == 2.4.3
> kashgari == 1.15
> 
> How to solve?

You need to install kashgari 2.x for tf 2.x. Or install Kashgari 1.x with tf 1.12+.
