### ISSUE TITLE
 使用CNNModel报错

### ISSUE THREAD

**Issue by morestart** [BrikerMan/Kashgari#357]
#45  Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Colab
- Python Version: 3.7
- requirements.txt:

## Question

我看博客中结果是这样的
```python
model.save('./model')

new_model = CNNModel.load_model('./model')
news = """「DeepMind 击败人类职业玩家的方式与他们声称的 AI 使命，以及所声称的『正确』方式完全相反。」
DeepMind 的人工智能 AlphaStar 一战成名，击败两名人类职业选手。掌声和欢呼之余，它也引起了一些质疑。在前天 DeepMind 举办的 AMA 中，AlphaStar 项目领导者 Oriol Vinyals 和 David Silver、职业玩家 LiquidTLO 与 LiquidMaNa 回答了一些疑问。不过困惑依然存在……
"""
x = list(jieba.cut(news))
new_model.predict(x)
'游戏'
```

```Python
import kashgari
from kashgari.tasks.classification import CNNModel
loaded_model = CNNModel.load_model('/content/model/')


news = """「DeepMind 击败人类职业玩家的方式与他们声称的 AI 使命，以及所声称的『正确』方式完全相反。」
DeepMind 的人工智能 AlphaStar 一战成名，击败两名人类职业选手。掌声和欢呼之余，它也引起了一些质疑。在前天 DeepMind 举办的 AMA 中，AlphaStar 项目领导者 Oriol Vinyals 和 David Silver、职业玩家 LiquidTLO 与 LiquidMaNa 回答了一些疑问。不过困惑依然存在……
"""
x = list(jieba.cut(news))
loaded_model.predict(x)
```

AttributeError: type object 'CNN_Model' has no attribute 'load_model'

**Comment by BrikerMan** [comment]
Please checkout the latest document https://kashgari.readthedocs.io/

**Comment by yaleimeng** [comment]
有些博客是早期写的。接口在版本迭代中发生了变化。确实应该看文档。
目前如果加载训练好的模型来预测，写法是：
loaded_model = kashgari.utils.load_model('saved_classification_model')
loaded_model.predict(test_x[:10])

**Comment by morestart** [comment]
> 有些博客是早期写的。接口在版本迭代中发生了变化。确实应该看文档。
> 目前如果加载训练好的模型来预测，写法是：
> loaded_model = kashgari.utils.load_model('saved_classification_model')
> loaded_model.predict(test_x[:10])

使用相同代码
```python
import jieba
import kashgari
from kashgari.tasks.classification import CNNModel


news = """「DeepMind 击败人类职业玩家的方式与他们声称的 AI 使命，以及所声称的『正确』方式完全相反。」
DeepMind 的人工智能 AlphaStar 一战成名，击败两名人类职业选手。掌声和欢呼之余，它也引起了一些质疑。在前天 DeepMind 举办的 AMA 中，AlphaStar 项目领导者 Oriol Vinyals 和 David Silver、职业玩家 LiquidTLO 与 LiquidMaNa 回答了一些疑问。不过困惑依然存在……
"""
x = list(jieba.cut(news))

loaded_model = kashgari.utils.load_model('model')
print(loaded_model.predict(x[:10]))
```
结果却是`['家居', '时尚', '家居', '家居', '家居', '家居', '家居', '家居', '家居', '家居']`
训练时的准确率已经到了99了，这个是因为什么，按照blog中预测这应该是游戏类呀

**Comment by yaleimeng** [comment]
我提醒你看文档是看加载模型的接口，并不意味着你的代码写的没问题。
案例中可能是你提供的数据形式有问题。分类模型在预测的时候，一句话/段落 是一个单位。例子中predict(x[ :10] 是取测试集（可能有千万条）的前面10条数据进行预测。而你这里只有一个样本。
就这个例子来说，news是一条样本。那么预测代码应写成
print(loaded_model.predict( [x, ]))  # 预测的对象是一组样本，如果只有一个，需要构造一个列表。
当然了，你采用jieba分词切分的粒度是词，用bert模型处理是有些问题的。
