### ISSUE TITLE
文本对输入中输入格式的要求是否正确

### ISSUE THREAD

**Issue by sceneline** [BrikerMan/Kashgari#366]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in all existing issues but did not find the same one.
- [ ] I have read the [documents](https://kashgari-zh.bmio.net/embeddings/bert-embedding/)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

查看了大佬关于bert embedding的分类文档以及文本对输入分类的文档，关于输入格式的要求有点疑惑，在分类文档中描述说文本tokenize后的格式为：
[
    ['[CLS]', 'jim', 'henson', 'was', 'a', 'puppet', '##eer', '.', '[SEP]'],
    ['[CLS]', 'this', 'here', "'", 's', 'an', 'example', 'of', 'using', 'the', 'bert', 'token', '##izer', '.', '[SEP]'],
    ['[CLS]', 'why', 'did', 'the', 'chicken', 'cross', 'the', 'road', '?', '[SEP]']
]
也就是句前和句后加了['CLS']和['SEP']标识；
但是在文本对输入中，输入要求变成了：
['First', 'do', 'it', '[SEP]', 'then', 'do', 'it', 'right']，也就是只在中间有一个['SEP']标识，用来告诉模型此输入为文本对输入。
但是实际上这两者都是文本做分类任务输入，为何文本对输入中不需要句前的['CLS']以及结尾的['SEP']标记？或者是因为文档没有正确的描述？
我自己的文本对输入中按照文档的描述输入以后，训练准确度很快升到98%附近，然后测试集一塌糊涂。然后测试使用['[CLS]', 'jim', 'henson', 'was'['SEP']'a', 'puppet', '##eer', '.', '[SEP]'],这种格式，模型似乎正在学习数据。
所以需要明确的是文本对输入中输入格式的要求是否正确。

**Comment by BrikerMan** [comment]
BERT 训练过程中是有加了 CLS 和 SEP Token，对于分类任务，加不加意义不大。但是对于序列标注，序列生成任务最好需要加上。Kashgari V1 中我记得 embedding 会自动添加。

其实这个也是个比较矛盾的点，我也没想好到底是 Kashgari 内部处理的帮大家加上去还是用户自己处理。目前是框架有处理。
