### ISSUE TITLE
[Question] 如何自定义参数和优化器

### ISSUE THREAD

**Issue by jianwei-song** [BrikerMan/Kashgari#369]
请问一下默认模型使用的优化器、学习率，dropout是多少呢，如果想在自己的小数据集10万字左右上面做实验，在哪里可以调整这三个参数呢

**Comment by BrikerMan** [comment]
- [调整超参数](https://kashgari.readthedocs.io/en/v1.1.5/tutorial/text-classification.html#use-custom-optimizer)
- [修改优化器](https://kashgari.readthedocs.io/en/v1.1.5/tutorial/text-classification.html#use-custom-optimizer)
- [自定义模型](https://kashgari.readthedocs.io/en/v1.1.5/tutorial/text-classification.html#use-custom-optimizer)

**Comment by jianwei-song** [comment]
我今天尝试了一下，可以更改dropout，但是没有看到更改学习率的，请问下面我写的这个是更改dropout的吧？请教一下学习率应该如何更改，在文档里面没有看到示例
hyper = BiLSTM_CRF_Model.get_default_hyper_parameters()
print(hyper)
hyper['layer_blstm']['rate'] = 0.5
model = BiLSTM_CRF_Model(hyper_parameters=hyper)

**Comment by BrikerMan** [comment]
- [修改优化器](https://kashgari.readthedocs.io/en/v1.1.5/tutorial/text-classification.html#use-custom-optimizer)
