### ISSUE TITLE
Unbalanced text classification 

### ISSUE THREAD

**Issue by akablar** [BrikerMan/Kashgari#371]
Are there any guidelines or documentation for using this library for unbalanced classification datasets?

**Comment by BrikerMan** [comment]
Try `class_weight` params of `model.fit` function. Example:

```python
model = BiLSTM_Model()
model.build_model(X_train, Y_train)
# Get label's indexs
print(model.label2idx)
# Setup a dict with label's id and it's weight.
class_weight = {
   0: 1.,
   1: 50.,
   2: 2.
}

fit_kwargs = {
    "class_weight":class_weight
}
model.fit(X_train, Y_train, nb_epoch=5, batch_size=32, fit_kwargs=fit_kwargs)
```

- details: https://datascience.stackexchange.com/questions/13490/how-to-set-class-weights-for-imbalanced-classes-in-keras
