### ISSUE TITLE
[Question] 请问下停用词如何加载，特殊符号是否需要过滤

### ISSUE THREAD

**Issue by guoweibo** [BrikerMan/Kashgari#372]
请问下停用词如何加载，特殊符号，数字，是否需要过滤？谢谢了

**Comment by guoweibo** [comment]
我用的是这个demo NLP - 15 分钟搭建中文文本分类模型https://eliyar.biz/nlp_chinese_text_classification_in_15mins/

**Comment by yaleimeng** [comment]
示例当中没有进行类似的处理。就是直接送进去train一波就完了。

**Comment by BrikerMan** [comment]
一般情况可以不处理，如果认为不处理会影响效果，那么可以在 fit 之前先处理数据，清理好 samples，然后再 fit。
