### ISSUE TITLE
如何使用aibert_tiny,文本分类,多谢了

### ISSUE THREAD

**Issue by guoweibo** [BrikerMan/Kashgari#375]
我是从https://github.com/brightmart/albert_zh
下载的tiny的版本,https://storage.googleapis.com/albert_zh/albert_tiny_489k.zip
,下载的文件都进行修改了,但是依然爆出    'provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (21128, 312) not compatible with provided weight shape (21128, 128)
{
  "attention_probs_dropout_prob": 0.0,
  "directionality": "bidi",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.0,
  "hidden_size": 312,
  "embedding_size": 128,
  "initializer_range": 0.02,
  "intermediate_size": 1248 ,
  "max_position_embeddings": 512,
  "num_attention_heads": 12,
  "num_hidden_layers": 4,

  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "type_vocab_size": 2,
  "vocab_size": 21128,
   "ln_type":"postln"

}

**Comment by BrikerMan** [comment]
可以提供示例代码，版本号等信息么？
请按照模板提 issue。
