### ISSUE TITLE
[Question] How to correctly use embed and embed_one method?

### ISSUE THREAD

**Issue by hqsiswiliam** [BrikerMan/Kashgari#376]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Linux, Ubuntu 18
- Python Version: 3.6.9
- requirements.txt:

```txt
absl-py==0.9.0
astor==0.8.1
bert4keras==0.6.5
boto==2.49.0
boto3==1.13.19
botocore==1.16.19
cachetools==4.1.0
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
cycler==0.10.0
dataclasses==0.7
docutils==0.15.2
filelock==3.0.12
gast==0.2.2
gensim==3.8.3
google-auth==1.16.0
google-auth-oauthlib==0.4.1
google-pasta==0.2.0
grpcio==1.29.0
h5py==2.10.0
idna==2.9
importlib-metadata==1.6.0
jmespath==0.10.0
joblib==0.15.1
kashgari==1.1.5
kashgari-tf==0.5.5
Keras==2.3.1
Keras-Applications==1.0.8
keras-bert==0.81.0
keras-embed-sim==0.7.0
keras-gpt-2==0.14.0
keras-layer-normalization==0.14.0
keras-multi-head==0.24.0
keras-pos-embd==0.11.0
keras-position-wise-feed-forward==0.6.0
Keras-Preprocessing==1.1.2
keras-self-attention==0.41.0
keras-transformer==0.33.0
kiwisolver==1.2.0
Markdown==3.2.2
matplotlib==3.2.1
numpy==1.16.4
oauthlib==3.1.0
opt-einsum==3.2.1
pandas==0.25.3
protobuf==3.12.2
py-dotenv==0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybind11==2.4.3
pyparsing==2.4.7
python-dateutil==2.8.1
python-dotenv==0.13.0
pytz==2019.3
PyYAML==5.3.1
regex==2020.5.14
requests==2.23.0
requests-oauthlib==1.3.0
rsa==4.0
s3transfer==0.3.3
sacremoses==0.0.43
scikit-learn==0.23.1
scipy==1.4.1
sentencepiece==0.1.91
seqeval==0.0.10
six==1.14.0
smart-open==2.0.0
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0
termcolor==1.1.0
Theano==1.0.4
threadpoolctl==2.1.0
tokenizers==0.7.0
tqdm==4.46.0
urllib3==1.25.9
Werkzeug==1.0.1
wrapt==1.12.1
zipp==3.1.0

```

## Question

Hi, I am confused about the input sequences to `embed` and `embed_one` method for `GPT-2` model. Do I need to train a sentence piece model to convert my text into sub-string lists/ sub-string-id list or all I need to do is to use the plain text as the input?

**Comment by hqsiswiliam** [comment]
Here is my code for embedding, correct my if I am wrong.
```python
import kashgari
from dotenv import load_dotenv
import sentencepiece as spm
import os
from tqdm import tqdm
from load_train_file import texts
load_dotenv()
kashgari.config.use_cudnn_cell = True
gpt2_embedding = kashgari.embeddings.GPT2Embedding(os.getenv('GPT2_PATH'),
                                                   task=kashgari.CLASSIFICATION,
                                                   sequence_length='variable')
sp = spm.SentencePieceProcessor()
sp.Load(os.getenv('SPM_MODEL_PATH'))
inputs = texts
encoded = [sp.encode_as_ids(input) for input in tqdm(inputs)]
result = gpt2_embedding.embed(encoded)
```

**Comment by BrikerMan** [comment]
You need to tokenize the plan text, then call the embed function. Like this,

```python
x = ["this", "is", "one", "sentence"]
result = gpt2_embedding.embed([x])
```

**Comment by hqsiswiliam** [comment]
> You need to tokenize the plan text, then call the embed function. Like this,
> 
> ```python
> x = ["this", "is", "one", "sentence"]
> result = gpt2_embedding.embed([x])
> ```

Hi, thanks for your reply. By the way, one thing I am not so sure is about the tokenizer. Do I need to use the plain tokenizer like the one provided by `nltk` or a sentence piece model trained by myself?

**Comment by BrikerMan** [comment]
When you are using pre-trained models like GPT-2, you need to use some tokenizer which they used for GPT-2. Otherwise, you will have lots of 'UNK' tokens, and it will lost lots of contexts.

**Comment by hqsiswiliam** [comment]
Alright, I got it. Where I can find the tokenizer for GPT-2 in your project, so I can use it to tokenize my text?

**Comment by hqsiswiliam** [comment]
Hey, I just found a tokenizer from `keras_gpt_2` that is the one of dependencies this repo owns. The `keras_gpt_2` has a function called `get_bpe_from_files`, which I think should be the proper tokenizer for pre-trained GPT-2?
