### ISSUE TITLE
[Question] Is any way to train NER model by train_x as word vectors?

### ISSUE THREAD

**Issue by ybdesire** [BrikerMan/Kashgari#380]
Currently train_x is word list, such as `train_x=['未', '名', '湖']`
I must translate the words to vectors, such as `train_xv=[[1,2,3], [2,1,3], [1,2,1]]` in specific way.
How to train the NER model here by my `train_xv` ?

**Comment by ybdesire** [comment]
@BrikerMan Would you share some suggetions for this question ?

**Comment by BrikerMan** [comment]
Just do this. But you cannot use it with the BERT Embedding.
```
train_x=['未名湖', '好', '漂亮']
```

**Comment by ybdesire** [comment]
Thanks @BrikerMan for the update.

My question is, if I provide the word embedding , such as 

```
train_xv = [[0,1,0], [1,2,3], [2,1,3], [1,2,1], [1,1,0]]
train_yv = ['O','B','I','E','O']
```

Then how can I train the BiLSTM_Model by above `train_xv ` and `train_yv` as model input?

**Comment by ybdesire** [comment]
@BrikerMan Would you share more suggetions for this question?

**Comment by BrikerMan** [comment]
You can use custom embedding or WordEmbedding to load your embedding file, then train the model.

**Comment by ybdesire** [comment]
@BrikerMan Great. Is any example for reference?

**Comment by ybdesire** [comment]
@BrikerMan I would appreciate if you could share some examples or related code .
