### ISSUE TITLE
[Question] 如何使用预训练albert_tiny模型

### ISSUE THREAD

**Issue by guoweibo** [BrikerMan/Kashgari#381]
##Environment

- OS [e.g. Mac OS, Linux]: windows
- Python Version:3.6
- requirements.txt:1.14

## Question
我使用的看到[https://github.com/brightmart/albert_zh](https://github.com/brightmart/albert_zh)预训练模型,下载其中的tiny版本,[下载](https://storage.googleapis.com/albert_zh/albert_tiny_489k.zip),能返回文本分类后权重吗?
比如说这段话返回的是体育类型,同时返回在体育类型里面的相似值 ['体育',0.95]这种
这是我用bertApi加载的代码
# 初始化 BERT embedding
from kashgari.embeddings import BERTEmbedding
embedding = BERTEmbedding('tiny/',
                          task=kashgari.CLASSIFICATION,
                          sequence_length=600)

## 错误
provided weight shape ' + str(w.shape))
ValueError: Layer weight shape (21128, 312) not compatible with provided weight shape (21128, 128)
{
"attention_probs_dropout_prob": 0.0,
"directionality": "bidi",
"hidden_act": "gelu",
"hidden_dropout_prob": 0.0,
"hidden_size": 312,
"embedding_size": 128,
"initializer_range": 0.02,
"intermediate_size": 1248 ,
"max_position_embeddings": 512,
"num_attention_heads": 12,
"num_hidden_layers": 4,

"pooler_fc_size": 768,
"pooler_num_attention_heads": 12,
"pooler_num_fc_layers": 3,
"pooler_size_per_head": 128,
"pooler_type": "first_token_transform",
"type_vocab_size": 2,
"vocab_size": 21128,
"ln_type":"postln"

}

**Comment by BrikerMan** [comment]
试试使用 [Transformer Embedding](https://kashgari.readthedocs.io/en/v1.1.5/embeddings/bert-embedding_v2.html) 加载
