### ISSUE TITLE
[Question] 使用GPU进行文本分类模型训练，CPU设备上使用模型可以么？

### ISSUE THREAD

**Issue by Igoslow** [BrikerMan/Kashgari#385]
使用kashgari有这个警告，担心CPU机器上不能用该模型
WARNING:root:CUDA GPU available, you can set `kashgari.config.use_cudnn_cell = True` to use CuDNNCell. This will speed up the training, but will make model incompatible with CPU device.

**Comment by BrikerMan** [comment]
可能警告不清楚，意思是如果使用 cudnn_LSTM/cudnn_GRU 进行训练，将不支持 CPU 推理。
cudnn 会加快 GPU 训练，但是不支持 CPU 推理。默认不开启，可以 GPU 训练，CPU 推理。

**Comment by Igoslow** [comment]
那请问怎样支持CPU推理呢？

**Comment by Igoslow** [comment]
谢谢您了解了
