### ISSUE TITLE
[BUG] AttributeError: module 'kashgari' has no attribute 'LABELING'

### ISSUE THREAD

**Issue by ybdesire** [BrikerMan/Kashgari#394]
code referenced from 

https://eliyar.biz/nlp_chinese_bert_ner/

get error for code part

```

bert_embed = BERTEmbedding('<PRE_TRAINED_BERT_MODEL_FOLDER>',      
                     task=kashgari.LABELING, 
                          sequence_length=100)
```

error output

```
task=kashgari.LABELING,
AttributeError: module 'kashgari' has no attribute 'LABELING'
```

lib versions

```
Python 3.8.3 (default, May 19 2020, 18:47:26)
>>> kashgari.__version__
'2.0.0.alpha'
>>> tensorflow.__version__
'2.2.0'
```

**Comment by BrikerMan** [comment]
https://eliyar.biz/nlp_chinese_bert_ner/ is for the Kashgari 1.x version.
2.0.0 Version is still in the alpha phase, might have bugs.

**Comment by ybdesire** [comment]
Got. Thanks @BrikerMan

**Comment by Jefffish09** [comment]
Hi @BrikerMan ,
Have you fixed this bug? I also met this error using Kashgari 2.X

**Comment by BrikerMan** [comment]
> Hi @BrikerMan ,
> Have you fixed this bug? I also met this error using Kashgari 2.X

There are API breaks on TF2 version. Please checkout the 2.x docs when using 2.x version.
https://kashgari.readthedocs.io/en/v2-trunk/
