### ISSUE TITLE
在NER识别问题中，BERT+BI-LSTM+CRF的预测输出结果里会出现单独的I-ORG标签，前面没有B-ORG便签

### ISSUE THREAD

**Issue by fancyfreeman** [BrikerMan/Kashgari#396]
咨询个问题：在NER识别问题中，BERT+BI-LSTM+CRF的预测输出结果里会出现单独的I-ORG标签，前面没有B-ORG便签。
比如:'O','O','O','I-ORG','O'  这里'I-ORG'是明显不正确的。
请问这是模型问题吗？还是模型的预测结果本来就会有这种结果，需要手工对预测的结果中的这些明显不对的标签进行清洗？

**Comment by BrikerMan** [comment]
请按照 Issue 模板提供版本号，核心代码等信息。

**Comment by fancyfreeman** [comment]
## Environment
- Mac OS,
- Python Version: 3.6

版本：
Kashgari 1.1.5
TensorFlow 1.15

关键代码：
from kashgari.corpus import ChineseDailyNerCorpus
import data_utils as du
from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.labeling import BiLSTM_CRF_Model, BiLSTM_Model
from kashgari.utils import load_model
import kashgari

# 导入数据
train_x, train_y = ChineseDailyNerCorpus.load_data('train')
valid_x, valid_y = ChineseDailyNerCorpus.load_data('validate')
test_x, test_y  = ChineseDailyNerCorpus.load_data('test')

print(f"train data count: {len(train_x)}")
print(f"validate data count: {len(valid_x)}")
print(f"test data count: {len(test_x)}")

# %% 创建 BERT embedding
bert_embed = BERTEmbedding(cp.get('base', 'EMBEDDING_FOLDER'),
                           task=kashgari.LABELING,
                           sequence_length=100)

model = BiLSTM_CRF_Model(bert_embed)
model.fit(train_x,
          train_y,
          x_validate=valid_x,
          y_validate=valid_y,
          epochs=1,
          batch_size=512)

x_list = test_x[:20]
y_list = model.predict(x_list)

问题：在NER识别问题中，BERT+BI-LSTM+CRF的预测输出结果里会出现单独的I-ORG标签，前面没有B-ORG便签。
比如:'O','O','O','I-ORG','O' 这里'I-ORG'是明显不正确的。
请问这是模型问题吗？还是模型的预测结果本来就会有这种结果，需要手工对预测的结果中的这些明显不对的标签进行清洗？

**Comment by fancyfreeman** [comment]
## Environment
- Mac OS,
- Python Version: 3.6

版本：
Kashgari 1.1.5
TensorFlow 1.15

关键代码：
from kashgari.corpus import ChineseDailyNerCorpus
import data_utils as du
from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.labeling import BiLSTM_CRF_Model, BiLSTM_Model
from kashgari.utils import load_model
import kashgari

# 导入数据
train_x, train_y = ChineseDailyNerCorpus.load_data('train')
valid_x, valid_y = ChineseDailyNerCorpus.load_data('validate')
test_x, test_y  = ChineseDailyNerCorpus.load_data('test')

print(f"train data count: {len(train_x)}")
print(f"validate data count: {len(valid_x)}")
print(f"test data count: {len(test_x)}")

# 创建 BERT embedding
bert_embed = BERTEmbedding(cp.get('base', 'EMBEDDING_FOLDER'),
                           task=kashgari.LABELING,
                           sequence_length=100)

model = BiLSTM_CRF_Model(bert_embed)
model.fit(train_x,
          train_y,
          x_validate=valid_x,
          y_validate=valid_y,
          epochs=1,
          batch_size=512)

# 预测
x_list = test_x[:20]
y_list = model.predict(x_list)

问题：在NER识别问题中，BERT+BI-LSTM+CRF的预测输出结果里会出现单独的I-ORG标签，前面没有B-ORG便签。
比如:'O','O','O','I-ORG','O' 这里'I-ORG'是明显不正确的。
请问这是模型问题吗？还是模型的预测结果本来就会有这种结果，需要手工对预测的结果中的这些明显不对的标签进行清洗？

**Comment by BrikerMan** [comment]
请问是只训练了一个 epoch 么？

**Comment by fancyfreeman** [comment]
是的，为了初步验证一下，只训练一个epoch，和这个有关吗？

**Comment by BrikerMan** [comment]
> 是的，为了初步验证一下，只训练一个epoch，和这个有关吗？

en.... 都没有收敛，肯定会各种错误的输出....
