### ISSUE TITLE
请问kashgari-bert+bilstm+crf做命名实体识别在cpu上跑的时候发生的占满全部cpu(90%使用率)问题如何解决？能否限定只使用某几块CPU？[Question] 

### ISSUE THREAD

**Issue by JoeshpCheung** [BrikerMan/Kashgari#397]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:
Ubuntu18.04

```txt
[Paste requirements.txt file here]
```

## Question

[A clear and concise description of what you want to know.]
请问kashgari-bert+bilstm+crf做命名实体识别在cpu上跑的时候发生的占满全部cpu(90%使用率)问题如何解决？能否限定只使用某几块CPU？

**Comment by BrikerMan** [comment]
没太明白，是做批量与测试后占用全部 CPU 还是做训练时候？这个是 TensorFlow 的特性，可以查询一下 TensorFlow 如何指定只是用几个 CPU 核心~
