### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by drxmy** [BrikerMan/Kashgari#401]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [1] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [1] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

您好，我想问一下这里的bert_embed可以由我自己的模型给出吗
`
model = BiLSTM_CRF_Model(bert_embed)
`
就是不用
`
bert_embed = BERTEmbedding('<PRE_TRAINED_BERT_MODEL_FOLDER>',
                           task=kashgari.LABELING,
                           sequence_length=100)
`
谢谢。

**Comment by BrikerMan** [comment]
你可以参照 BertEmbedding/WordEmbedding 来构建自己的 Embedding 类传进去。
