### ISSUE TITLE
[Question]  ImportError: cannot import name 'BertEmbedding' from 'kashgari.embeddings' (/opt/conda/lib/python3.7/site-packages/kashgari/embeddings/__init__.py)

### ISSUE THREAD

**Issue by usmaann** [BrikerMan/Kashgari#403]
Hi....I am using Kashgari for transfer learning...BERT with BiGRU but getting below error... Pls advise

![image](https://user-images.githubusercontent.com/38275359/88756681-981cf680-d1a7-11ea-957c-a35db35490ee.png)

**Comment by BrikerMan** [comment]
If you are using colab, restart colab kernal, then try this.

```
try:
  # Use the %tensorflow_version magic if in colab.
  %tensorflow_version 1.x
except Exception:
  pass

import tensorflow as tf
import kashgari

print(tf.__version__)
print(kashgari.__version__)
from kashgari.embeddings import BERTEmbedding
```

**Comment by usmaann** [comment]
> try:
>   # Use the %tensorflow_version magic if in colab.
>   %tensorflow_version 1.x
> except Exception:
>   pass
> 
> import tensorflow as tf
> from kashgari.embedding import BertEmbedding

Tried and getting below error

![image](https://user-images.githubusercontent.com/38275359/88760155-c0105800-d1af-11ea-9856-7ce301f08e47.png)

**Comment by BrikerMan** [comment]
@usmaann Sorry, here is a typo. Fixed.

**Comment by Youngchou018** [comment]
I have the same problem

**Comment by jiel30** [comment]
same problem here
Kashgari == 2.02
tensorflow == 2.5.0

**Comment by Gowott** [comment]
> I have the same problem

have u solved it? i meet the same one

**Comment by Gowott** [comment]
> same problem here Kashgari == 2.02 tensorflow == 2.5.0

have u solved it? i meet the same one

**Comment by Gowott** [comment]
Hey, i use colab and meet the same problem no module named BertEmbedding

**Comment by zhangjinqu** [comment]
In my case, this error was caused by the name of BertEmbedding, All characters in Bert should be capitalized as BERTEmbedding

import as following:

from kashgari.embeddings import BERTEmbedding
