### ISSUE TITLE
[Question] ModuleNotFoundError: No module named 'kashgari.embeddings.bert_embedding_v2'

### ISSUE THREAD

**Issue by usmaann** [BrikerMan/Kashgari#404]
Getting below error Please advise...

Using >>kashgari-2.0.0a1 and TF > 2.2.0

Following this tutorial>>>>https://kashgari.readthedocs.io/en/v1.1.1/embeddings/bert-embedding_v2.html

![image](https://user-images.githubusercontent.com/38275359/88809318-5320b080-d1f7-11ea-9e46-b49bab673c20.png)

**Comment by BrikerMan** [comment]
There is some API diff between 1.x and 2.x. Please read the version-specific docs from https://kashgari.readthedocs.io/en/latest/.

You can change the version by clinking the latest button.

<img width="434" alt="LWScreenShot 2020-07-30 at 上午9 35 04" src="https://user-images.githubusercontent.com/9368907/88870515-23e65f80-d248-11ea-9870-49c28d34c1a8.png">
