### ISSUE TITLE
英文预测结果问题

### ISSUE THREAD

**Issue by Jiannan28** [BrikerMan/Kashgari#405]
做英语的多class预测（根据这篇文章https://medium.com/@BrikerMan/multi-class-text-classification-with-kashgari-in-15mins-c3e744ce971d), new_model.predict(x)预测的时候会根据每个词预测出一个结果，而不是根据整个句子。是否需要把整个句子不分词，然后放到一个list里边做预测呢？

Mac OS
Python 3.7

**Comment by BrikerMan** [comment]
这里可能有误，model.predict(x) 这里的 x 是一组样本，也就是 n 个被分词过的句子。当只有一个句子的时候，输入应该是 model.predict([sentence])

**Comment by Jiannan28** [comment]
多谢！

**Comment by james-robinhood** [comment]
跟进一下这个问题。在新版本里如何可以输出top k的结果或者直接输出所有的概率而不是argmax？
