### ISSUE TITLE
[Question] 如何修改加载的Bert模型到自定义模型的输出

### ISSUE THREAD

**Issue by Junphy-Jan** [BrikerMan/Kashgari#406]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [Y] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [Y] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: Windows
- Python Version: 3.7
- requirements.txt: 

```txt
[Paste requirements.txt file here]
```

## Question
你好，我是刚接触NLP不久，也是通过您的框架上手了第一个NER的模型。有个问题想请教下，在使用BERT预训练的 embedding之后，再通过搭建具体的模型，如：
```
model = BiLSTM_CRF_Model(bert_embed)
model.fit(train_x,
          train_y,
          x_validate=valid_x,
          y_validate=valid_y,
          epochs=20,
          batch_size=512)

```
具体来说，如果 train_x[0] 是一个句子：['我', '是','中','国','人']。
此时，送入模型的是 每个字符对应的ID向量 还是说 是通过 bert embedding获取到的句子编码向量呢？
这个向量我可以在送入模型训练之前修改它吗，谢谢！

**Comment by BrikerMan** [comment]
input：['我', '是','中','国','人']
预处理模块输入 ['我', '是','中','国','人'] 输出 [1, 2, 3, 4, 5]，也就是预处理时候完成映射到 id。
Bert 输入映射后的 id [1, 2, 3, 4, 5] 输出 对应的 Bert 张量
BiLSTM_CRF 层输入 bert 的结果，输出具体的 NER 结果。

其中 BERT 和 BiLSTM_CRF 我这里将会拼接成一个模型。

如果你想对于 BERT 输出结果进行特殊的处理，可以自己 subclass 一个 BiLSTM_CRF_Model 模型，修改 build_model 函数，在 bert 之后，blstm 之前增加你自己的特定层即可。

**Comment by Junphy-Jan** [comment]
多谢！
我安装的是
"kashgari>=1.1,<2.0"   "tensorflow>=1.14,<2.0"
您是指修改这个 build_model_arc这个函数么。  
这个embed_model.output 就是Bert输出的句向量。我可以修改这个向量是这意思吗
![image](https://user-images.githubusercontent.com/14165820/91284093-0a402580-e7be-11ea-95e3-bc75dba4cdfc.png)

**Comment by BrikerMan** [comment]
对的，是这里。此处的 embed_model.output 是值得 embedding 模型的输出。如果你用了 Bert 则就是 Bert 的输出。

**Comment by Junphy-Jan** [comment]
好的 多谢！ 我试试

**Comment by Junphy-Jan** [comment]
不好意思再请教一下，我可以在训练的过程中看到这个 embed_model.output的具体值么。我想打个断点但是找不到位置。
还是有什么其他的办法吗

**Comment by BrikerMan** [comment]
可以尝试通过 print 语句来看具体的值和 shape

**Comment by Junphy-Jan** [comment]
我理解这个build_model_arc 函数不是只在build模型的时候调用一次么。 通过print只能打印出 output的shape。
好像看不到每个batch喂入数据之后的实际值吧

**Comment by BrikerMan** [comment]
嗯，是的，这个只是构建的时候调用。你完全可以直接通过调用 embedding.embed(x_samples) 来获取具体的输出。这个就是 embedding 的结果。

**Comment by Junphy-Jan** [comment]
好的，还注意到一个不知道是什么原因，在设置了 batch_size = 64 的情况下，控制台打印的好像不太对：
![image](https://user-images.githubusercontent.com/14165820/91297235-880d2c80-e7d0-11ea-9498-585c5681b4eb.png)
在 callback里看到的是64，但是只显示了60

**Comment by BrikerMan** [comment]
显示的是 step 数量，也就是 sample_count // 64 = 60

**Comment by Junphy-Jan** [comment]
好的，请问下 1.1.5版本是不支持多标签分类吗？
在文档中有：`model = BiLSTM_Model(bert_embed, sequence_length=100, multi_label=True)`
我用的是1.1.5版本的，好像不支持这个multi_label参数。

**Comment by shiwl0329** [comment]
> 嗯，是的，这个只是构建的时候调用。你完全可以直接通过调用 embedding.embed(x_samples) 来获取具体的输出。这个就是 embedding 的结果。

大神，跑出来的结果是[1,12,3072]，3072不是中间层的结果么。怎么才能获取768维的句向量呢

**Comment by susu-12** [comment]
你好，我想问下如果我想修改BERT模型的自注意层，然后再加载预训练模型，不知道该怎么操作
