### ISSUE TITLE
[BUG] ['PAD']

### ISSUE THREAD

**Issue by OmarMohammed88** [BrikerMan/Kashgari#407]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [yes ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ yes] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:3.6
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

### What

[i have trained the model and loaded it another time the model. predict produces KeyError: '[PAD]' ]

### Reproduce
![Screenshot from 2020-09-01 18-44-13](https://user-images.githubusercontent.com/45721757/91882551-69e97580-ec83-11ea-932b-7fd9480c0896.png)

[The steps to reproduce this issue. What is the URL you were trying to play, where did you put your code, etc.]

### Other Comment

[Add anything else here]

**Comment by Alymostafa** [comment]
I Meet the same issue using ```bert_embed = BertEmbedding('/content/uncased_L-12_H-768_A-12')``` and pretrained model 
```BiGRU_Model()```

**Comment by OmarMohammed88** [comment]
I figured it out 
```
loaded_model = BiLSTM_Model.load_model('saved_classification_model')
loaded_model.predict(test_x[:10])
```
it solves my problem
