### ISSUE TITLE
[Question] 请问下能给下kashgari输入向量的格式和标签的数据格式么？或者能不能给一些参考文档

### ISSUE THREAD

**Issue by Igoslow** [BrikerMan/Kashgari#410]
我想做文本分类，但是词转为向量，我不想使用kashgari或者bert语言嵌入的代码。我想直接输入向量。我看了您的代码输入向量的数据格式大概是元组下的二维numpy数组，但是输入数据会报错，请问下应该怎么处理呢？

**Comment by BrikerMan** [comment]
你可以先把你的向量保存成 w2v 形式，然后使用 WordEmbedding 去加载。
这里有例子：https://www.kaggle.com/matsuik/convert-embedding-dictionary-to-gensim-w2v-format

只要你最终的 w2v 能够被 gensim 读取即可。

**Comment by Igoslow** [comment]
谢谢您，了解了
