### ISSUE TITLE
How do I add additional features with BERT?[Question] 

### ISSUE THREAD

**Issue by Syauri** [BrikerMan/Kashgari#417]
I want to use a pertained model with additional features for NER task. Lets say I have a sequence of pos tags I want to send in as feature to make prediction.

**Comment by BrikerMan** [comment]
In Kashgari V1, we have a feature called stacked embedding and numeric embedding. Please try it out. This is not implemented on Kashgari V2 yet.
https://kashgari.readthedocs.io/en/v1.1.5/advance-use/handle-numeric-features.html

**Comment by Syauri** [comment]
Thanks!
