### ISSUE TITLE
[Question] unable to install and command mysteriously alters my env

### ISSUE THREAD

**Issue by yuzuhikorunrun** [BrikerMan/Kashgari#418]
## Environment

- OS : windows
- Python Version: 3.6
- tensorflow version: CPU, version 1.5
- pip : updated to latest
- numpy: 1.16
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

hi there, I am unable to install kashgari. my env is as listed above, and I am using anaconda. whenever i run this command: `pip install kashgari>=1.0.0,<2.0.0`, the following msg pops out:

> ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.
> 
> We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.
> 
> tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.

PLUS, such command automatically alters my env to:
- tensorflow version: CPU, version 2.3
- numpy: 1.19

super creepy. please advice, thanks.

**Comment by BrikerMan** [comment]
You need to install kashgari 2+ for tensorflow 2.


| Backend          | pypi version                           | desc                  |
| ---------------- | -------------------------------------- | --------------------- |
| TensorFlow 2.1+  | `pip install 'kashgari>=2.0.0'`        | TF2.10+ with tf.keras |
| TensorFlow 1.14+ | `pip install 'kashgari>=1.0.0,<2.0.0'` | TF1.14+ with tf.keras |

**Comment by yuzuhikorunrun** [comment]
@BrikerMan Hello, thanks for your reply but I am using tensorflow 1.5 version, why do I need to install kashgari 2+ for tensorflow 2?

> tensorflow version: CPU, version 1.5

**Comment by BrikerMan** [comment]
Tensorflow 2 broked many APIs, So we had to have 2 different versions....

**Comment by yuzuhikorunrun** [comment]
> Tensorflow 2 broked many APIs, So we had to have 2 different versions....

I'm sorry, I'm confused. I do not have tensorflow 2, I have tensorflow 1.5. and plus, I've tried `pip install 'kashgari>=2.0.0'`, it still does not work.

**Comment by BrikerMan** [comment]
TF1.5 is not supported by kashgari. The minimal requirements are TF 1.13.
If you use TF 1.13 to TF 1.15, you can install kashgari by `pip install 'kashgari>=1.0.0,<2.0.0'`
