### ISSUE TITLE
How should I format the dataset to pass the document or sentence information?

### ISSUE THREAD

**Issue by Syauri** [BrikerMan/Kashgari#419]
I see that the corpus is represented as array of array of strings. How are document information passed in the corpus? Say X_train= [[],[],[],], is one document equal to X_train[0]? If yes, then how are sentence information passed?

**Comment by BrikerMan** [comment]
Sample for classification

```
x = ["This", "is", "a", "sentence"]
y = ["Class-A"]

train_x = [x, x, x]
train_y = [y, y, y]
```

Sample for labeling

```
x = ["This", "is", "a", "sentence"]
y = ["O", "O", "O", "B-TYPE"]

train_x = [x, x, x]
train_y = [y, y, y]
```
