### ISSUE TITLE
[Question] How to access the embeddings? of my dataset that model have been trained on it ? 

### ISSUE THREAD

**Issue by Alymostafa** [BrikerMan/Kashgari#421]
## Environment

- OS [Ubuntu-18.04-bionic]:
- Python Version: 3.6

## Question
How to access the embedding of my dataset that the model has been trained on it?

**Comment by BrikerMan** [comment]
I didn't understand the question, maybe you can provide more information.

**Comment by Alymostafa** [comment]
OK, i will try to explain it. when I train the model (ex.Bi-LSTM), i give the dataset to the model in characters or words. The model change them to numbers (embeddings), so how can I access these embeddings to do some work with it (ex.visualization)

**Comment by BrikerMan** [comment]
You can access the embedding via `model. embedding`, then you can embed your sentence by `model.embedding.embed([sentence])`.  Here is the [embed API](https://kashgari.readthedocs.io/en/v2.0.0/embeddings/)

**Comment by Alymostafa** [comment]
Ok thanks, that solved my issue.
