### ISSUE TITLE
kashgari2.0.0 部署版本如何保存模型

### ISSUE THREAD

**Issue by wxy521131418** [BrikerMan/Kashgari#423]
kashgari1.5版本的
kashgari.utils.convert_to_saved_model

但是在 kashgari==2.0.0 版本中没有这个方法
module 'kashgari.utils' has no attribute 'convert_to_saved_model'

**Comment by BrikerMan** [comment]
发现新方案不好用，还是按照以前增加了 `convert_to_saved_model` 方法

**Comment by BrikerMan** [comment]
已经在 2.0.1 版本中添加，已更新文档 [Kashgari with TF Serving](https://kashgari.readthedocs.io/en/v2.0.1/advance-use/tensorflow-serving/)
