### ISSUE TITLE
[Question] 请问下您使用GPU训练可以指定某块GPU么

### ISSUE THREAD

**Issue by Igoslow** [BrikerMan/Kashgari#424]
## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]: windows10
- Python Version: 3.6.3
- requirements.txt:kashgari，tensorflow，pandas，etc...

```txt
[Paste requirements.txt file here]
```

## Question
单gpu训练时一般使用GPU 0 和cpu 0，占用GPU 0 过多时，出现以下bug:
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas GEMM launch failed : a.shape=(5632, 768), b.shape=(768, 768), m=5632, n=768, k=768
	 [[{{node Encoder-1-MultiHeadSelfAttention/MatMul_2}}]]
	 [[loss/mul/_1709]]
  (1) Internal: Blas GEMM launch failed : a.shape=(5632, 768), b.shape=(768, 768), m=5632, n=768, k=768
	 [[{{node Encoder-1-MultiHeadSelfAttention/MatMul_2}}]]
请您帮助我一下，谢谢您

[A clear and concise description of what you want to know.]

**Comment by BrikerMan** [comment]
在你跑代码之前，先设定，更多见 https://stackoverflow.com/questions/40069883/how-to-set-specific-gpu-in-tensorflow
```
import tensorflow as tf
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  # Restrict TensorFlow to only use the first GPU
  try:
    tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
  except RuntimeError as e:
    # Visible devices must be set at program startup
    print(e)
``

**Comment by Igoslow** [comment]
> 在你跑代码之前，先设定，更多见 https://stackoverflow.com/questions/40069883/how-to-set-specific-gpu-in-tensorflow
> 
> ```
> import tensorflow as tf
> gpus = tf.config.experimental.list_physical_devices('GPU')
> if gpus:
>   # Restrict TensorFlow to only use the first GPU
>   try:
>     tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
>   except RuntimeError as e:
>     # Visible devices must be set at program startup
>     print(e)
> ``
> ```

谢谢
