### ISSUE TITLE
can i get word embedding from kashgari,like w2v[word] in gensim

### ISSUE THREAD

**Issue by mashagua** [BrikerMan/Kashgari#426]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
how to get only one word embedding like gensim w2v[word]
**Additional context**

**Comment by BrikerMan** [comment]
Please clear up the issue description....

**Comment by BrikerMan** [comment]
Duplicated with https://github.com/BrikerMan/Kashgari/issues/421#event-3917938228
