### ISSUE TITLE
[Question] 无法开始epoch 训练：提示F tensorflow/core/kernels/cudnn_rnn_ops.cc:1643] Check failed: stream->parent()->GetRnnAlgorithms(&algorithms)

### ISSUE THREAD

**Issue by learnpythontheew** [BrikerMan/Kashgari#430]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:Linux
- Python Version: 3,7
- requirements.txt:

```txt
kashgari>=1.0.0,<2.0.0
```

## Question

无法开始epoch 训练：
出现错误：F tensorflow/core/kernels/cudnn_rnn_ops.cc:1643] Check failed: stream->parent()->GetRnnAlgorithms(&algorithms)
训练中断

跑别的没有用这个框架的项目gpu是能用的

tensorflow 版本1.15.2
libcudnn7_7.5.1.10-1+cuda10.0
请问是什么问题呢？

![image](https://user-images.githubusercontent.com/29298489/98215649-029db980-1f83-11eb-919a-d188c2fc04b8.png)

**Comment by BrikerMan** [comment]
请问 Kashgari 版本是多少？

**Comment by learnpythontheew** [comment]
kashgari>=1.0.0,<2.0.0

**Comment by BrikerMan** [comment]
直接跑 keras 模型没有这个问题么?
