### ISSUE TITLE
[Question] 关于使用kashgari微调bert的一些困惑

### ISSUE THREAD

**Issue by yuelianggongzi** [BrikerMan/Kashgari#432]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[A clear and concise description of what you want to know.]
你好，kashgari是一个非常棒的快速实验框架，我很喜欢，但是有一点疑惑的，当我选择使用BERT时，如果我选择微调，也就是Trainable=True，经常会出现不收敛或者过拟合的现象，作者遇到过这种现象吗？当我使用BERT的时候，怎么进行warmup？或者分层设置学习率呢，作者默认设置的参数可以说一下吗

**Comment by BrikerMan** [comment]
应该是 lr 过大的问题，可以按照这个自定义 optimizer 方法来设定自己的 optimizer 和 lr https://kashgari.readthedocs.io/en/v2.0.1/tutorial/text-labeling/#use-custom-optimizer

**Comment by Fourha** [comment]
> 应该是 lr 过大的问题，可以按照这个自定义 optimizer 方法来设定自己的 optimizer 和 lr https://kashgari.readthedocs.io/en/v2.0.1/tutorial/text-labeling/#use-custom-optimizer

请问设置Trainable=True是在加载bert预训练模型的命令里吗，我查阅了最新版本的文档，只在word_embedding里看到了trianable，之前的一些issue里提到的关于bert embedding设置trainable = True的参考文档链接全部404了，所以想问一下在哪里设置trainable，是否有相关文档呢~谢谢~
