### ISSUE TITLE
[Question] Is there any chance to use more pre-train embedding like RoBERTa or ALBERT?

### ISSUE THREAD

**Issue by wuling31715** [BrikerMan/Kashgari#439]

**Comment by BrikerMan** [comment]
https://kashgari.readthedocs.io/en/v2.0.1/embeddings/transformer-embedding/

**Comment by wuling31715** [comment]
> https://kashgari.readthedocs.io/en/v2.0.1/embeddings/transformer-embedding/

Thanks a lot! Kashgari is real a convenient and powerful framework!

**Comment by OmarMohammed88** [comment]
@BrikerMan 
is there any way to load pre-trained model with (.h5 OR bin)  extension instead of (.ckpt) because I got this error 
![image](https://user-images.githubusercontent.com/45721757/103440833-8f968380-4c51-11eb-8f56-ae0cacf242e0.png)

**Comment by BrikerMan** [comment]
> @BrikerMan
> is there any way to load pre-trained model with (.h5 OR bin) extension instead of (.ckpt) because I got this error
> ![image](https://user-images.githubusercontent.com/45721757/103440833-8f968380-4c51-11eb-8f56-ae0cacf242e0.png)

Yes, the simplest way might be to load the h5 file using tf.keras, then save it save saved-model.

```python
model = tf.keras.models.load_model('my_model.h5')
model.save('saved_model/albert') 
```

**Comment by OmarMohammed88** [comment]
```model = tf.keras.models.load_model("/content/ARBERT/tf_model.h5")```
i got this error 
```
OSError: SavedModel file does not exist at: /content/ARBERT/tf_model.h5/{saved_model.pbtxt|saved_model.pb}
```
