### ISSUE TITLE
 TypeError: unhashable type: 'list'[BUG] 

### ISSUE THREAD

**Issue by 584251395** [BrikerMan/Kashgari#444]
在使用bert embedding
from kashgari.tasks.classification import CNN_LSTM_Model
bert_embedding=BertEmbedding("bertmodel")
model = CNN_LSTM_Model(bert_embedding)
model.fit(
    train_x, train_y,
    test_x, test_y,
    epochs=3,
    batch_size=64
)
<ipython-input-14-883d2bd156af> in <module>
      6     test_x, test_y,
      7     epochs=3,
----> 8     batch_size=64
      9 )

D:\anaconda\lib\site-packages\kashgari\tasks\classification\abc_model.py in fit(self, x_train, y_train, x_validate, y_validate, batch_size, epochs, callbacks, fit_kwargs)
    206                                   epochs=epochs,
    207                                   callbacks=callbacks,
--> 208                                   fit_kwargs=fit_kwargs)
    209 
    210     def fit_generator(self,

D:\anaconda\lib\site-packages\kashgari\tasks\classification\abc_model.py in fit_generator(self, train_sample_gen, valid_sample_gen, batch_size, epochs, callbacks, fit_kwargs)
    238             and validation metrics values (if applicable).
    239         """
--> 240         self.build_model_generator([g for g in [train_sample_gen, valid_sample_gen] if g])
    241 
    242         model_summary = []

D:\anaconda\lib\site-packages\kashgari\tasks\classification\abc_model.py in build_model_generator(self, generators)
    111         if not self.text_processor.vocab2idx:
    112             self.text_processor.build_vocab_generator(generators)
--> 113         self.label_processor.build_vocab_generator(generators)
    114         self.embedding.setup_text_processor(self.text_processor)
    115 

D:\anaconda\lib\site-packages\kashgari\processors\class_processor.py in build_vocab_generator(self, generators)
     51                         token2count[token] = count + 1
     52             else:
---> 53                 for _, label in tqdm.tqdm(generator, desc="Preparing classification label vocab dict"):
     54                     print(label)
     55                     count = token2count.get(label, 0)

TypeError: unhashable type: 'list'

**Comment by 584251395** [comment]
系统：win10
python:3.7+3.8
版本：2.0.0

**Comment by 584251395** [comment]
absl-py                   0.11.0                   pypi_0    pypi
argon2-cffi               20.1.0           py38h294d835_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
attrs                     20.3.0             pyhd3deb0d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backports                 1.0                        py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
backports.functools_lru_cache 1.6.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
bert4keras                0.9.6                    pypi_0    pypi
bleach                    3.2.1              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ca-certificates           2020.12.5            h5b45459_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cachetools                4.2.0                    pypi_0    pypi
certifi                   2020.12.5        py38haa244fe_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cffi                      1.14.4           py38hd8c33c5_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
chardet                   3.0.4                    pypi_0    pypi
colorama                  0.4.4              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.14                  pypi_0    pypi
decorator                 4.4.2                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
defusedxml                0.6.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
flatbuffers               1.12                     pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
gensim                    3.8.3                    pypi_0    pypi
google-auth               1.24.0                   pypi_0    pypi
google-auth-oauthlib      0.4.2                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.32.0                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
idna                      2.10                     pypi_0    pypi
importlib-metadata        3.3.0            py38haa244fe_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
importlib_metadata        3.3.0                hd8ed1ab_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipykernel                 5.4.2            py38h7b7c402_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipython                   7.19.0           py38hc5df569_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
ipython_genutils          0.2.0                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jedi                      0.17.2           py38haa244fe_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
joblib                    1.0.0                    pypi_0    pypi
jsonschema                3.2.0                      py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_client            6.1.7                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyter_core              4.7.0            py38haa244fe_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
kashgari                  2.0.0                    pypi_0    pypi
keras                     2.3.1                    pypi_0    pypi
keras-applications        1.0.8                    pypi_0    pypi
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
libsodium                 1.0.18               h8d14728_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gcc-libs            5.3.0                         7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gcc-libs-core       5.3.0                         7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-gmp                 6.1.0                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38hab1e662_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
matplotlib                3.3.3                    pypi_0    pypi
mistune                   0.8.4           py38h294d835_1002    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
msys2-conda-epoch         20160418                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2
nb_conda                  2.2.1            py38h32f6830_4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nb_conda_kernels          2.3.1            py38haa244fe_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbclient                  0.5.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbconvert                 6.0.7            py38haa244fe_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nbformat                  5.0.8                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
nest-asyncio              1.4.3              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
notebook                  6.1.5            py38haa244fe_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
numpy                     1.19.4                   pypi_0    pypi
oauthlib                  3.1.0                    pypi_0    pypi
openssl                   1.1.1i               h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.8               pyhd3deb0d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pandas                    1.1.5                    pypi_0    pypi
pandoc                    2.11.2               h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pandocfilters             1.4.2                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
parso                     0.7.1              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pickleshare               0.7.5                   py_1003    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pillow                    8.0.1                    pypi_0    pypi
pip                       20.3.3             pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
prompt-toolkit            3.0.8              pyha770c72_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
protobuf                  3.14.0                   pypi_0    pypi
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyrsistent                0.17.3           py38h294d835_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python                    3.8.6           h7840368_1_cpython    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python-dateutil           2.8.1                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
python_abi                3.8                      1_cp38    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytz                      2020.4                   pypi_0    pypi
pywin32                   228              py38h1e8a9f7_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pywinpty                  0.5.7            py38h32f6830_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pyyaml                    5.3.1                    pypi_0    pypi
pyzmq                     20.0.0           py38h7a0e47e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
requests                  2.25.0                   pypi_0    pypi
requests-oauthlib         1.3.0                    pypi_0    pypi
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.23.2                   pypi_0    pypi
scipy                     1.5.4                    pypi_0    pypi
send2trash                1.5.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
setuptools                49.6.0           py38h9bdc248_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
six                       1.15.0             pyh9f0ad1d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
smart-open                4.0.1                    pypi_0    pypi
sqlite                    3.34.0               h8ffe710_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tensorboard               2.4.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.4.0                    pypi_0    pypi
tensorflow-addons         0.11.2                   pypi_0    pypi
tensorflow-estimator      2.4.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1            py38haa244fe_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
testpath                  0.4.4                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
threadpoolctl             2.1.0                    pypi_0    pypi
tornado                   6.1              py38h294d835_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
tqdm                      4.32.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
typeguard                 2.10.0                   pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.2                   pypi_0    pypi
vc                        14.1                 h869be7e_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
vs2015_runtime            14.16.27012          h30e32a0_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
webencodings              0.5.1                      py_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3deb0d_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wincertstore              0.2             py38h32f6830_1005    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
winpty                    0.4.3                         4    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wrapt                     1.12.1                   pypi_0    pypi
zeromq                    4.3.3                h0e60522_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
zipp                      3.4.0                      py_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

(nlp) C:\Users\Administrator>

**Comment by BrikerMan** [comment]
麻烦格式化一下问题，看着像是你的数据格式问题。
