### ISSUE TITLE
[Question] 文本分类预测能否输出top k预测结果及概率值？

### ISSUE THREAD

**Issue by moulai** [BrikerMan/Kashgari#445]
## Check List
- [x] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [x] I have read the [documents](https://kashgari.bmio.net)

## Question
请问文本分类预测能否输出top k预测结果及概率值？我看了issue #146 中的解决方案，但是好像并不适用于>=2.0.0版本？也没有在kpi文档中找到相关说明。
谢谢！

**Comment by james-robinhood** [comment]
同问这个问题，predict_top_k好像在新版本里没有了

**Comment by who0sy** [comment]
同问
