### ISSUE TITLE
[Question] How do I specify layer regularization?

### ISSUE THREAD

**Issue by Syauri** [BrikerMan/Kashgari#446]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [X] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [X] I have read the [documents](https://kashgari.bmio.net)

## Question
I was playing with hyperparameter but don't see a way to specify regularization parameters.

**Comment by BrikerMan** [comment]
You can just add key value to the hyper params, which will pass to layers as **kwargs
