### ISSUE TITLE
[Question] v2版本为什么模型分了3个文件，体积翻倍？

### ISSUE THREAD

**Issue by yaleimeng** [BrikerMan/Kashgari#449]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [+ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ + ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:  Ubuntu 18.04
- Python Version: 3.6
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[在kashgari 1.x版本时，保存的模型只有一个model_info.json文件和一个模型权重.h5文件。
升级到2.0之后，保存的模型多了一个embed_model_weights.h5文件，体积跟模型权重差不多一样大。这样部署时模型体积就翻了一倍。这是什么原因？
有什么办法改变吗？]

**Comment by BrikerMan** [comment]
这个设定是因为 Embedding 和 Model 是从架构上分开，保存也分开保存了，导致有了两个权重文件。我考虑一下如何优化，有什么意见建议也可以提出来。

**Comment by yaleimeng** [comment]
Embedding的权重比较大能够理解，层数多也比较复杂。但是BERT后面接的部分网络相对简单，权重应该是比较小的。
拆开之后，应该两者的体积之和跟原来的权重大致相当（或略大）才符合预期。翻倍有点过了

**Comment by BrikerMan** [comment]
表达有误，是保存了一次 Embedding，保存了一次全量模型。确实太浪费了，我想想如何修改比较方便。

**Comment by yaleimeng** [comment]
@BrikerMan  这个问题对作者应该不是很难解决的。如果我自己来改，可能要把整个项目读一遍来定位问题。原来读过1.x版本，现在2.x没读过。
希望问题早日得到解决。如果他人解决了还希望早日合并。多谢项目参与者的辛苦工作。

**Comment by BrikerMan** [comment]
这个问题暂时忽略了～ 不好意思带来麻烦。可能未来某一天考虑变更～

**Comment by yaleimeng** [comment]
@BrikerMan 感谢关注，不过我已经解决了。目前在使用中没发现什么异常。
在kashgari/tasks/abs_task_model.py 里面，在save()函数、load_model()函数里面，分别注释掉存取  embed_model_weights.h5 的那一条语句即可。

**Comment by BrikerMan** [comment]
因为考虑了太多场景的兼容，所以妥协了这个做法来着～
