### ISSUE TITLE
[BUG] BERT embedding

### ISSUE THREAD

**Issue by ahmad-alismail** [BrikerMan/Kashgari#451]
Hello,
I am trying to build a sequence labeling classifier as in tutorials, but I have the following problem with BERT embedding step:
![image](https://user-images.githubusercontent.com/46696930/106373430-b0014d00-6379-11eb-84ce-e8759bdf9d1f.png)

## Environment

- Mac OS
- Python Version: 3.6
- Google-Colab

### Other Comment

Did I make anything wrong in this step? Maybe it is stupid question but I am a little bit beginner.
Thanks in Advance!

**Comment by BrikerMan** [comment]
You are using the legacy API with Kashgari V2 version. please check out the latest docs https://kashgari.readthedocs.io/
