### ISSUE TITLE
[Question] 模型保存出错

### ISSUE THREAD

**Issue by ppvv6688** [BrikerMan/Kashgari#455]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:win10
- Python Version:python3.7
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

model.save()
小白做这个，出现以下错误，请问怎么解决？感谢！

 File "D:\ProgramData\Anaconda3\lib\site-packages\kashgari\tasks\abs_task_model.py", line 84, in save
    f.write(json.dumps(self.to_dict(), indent=2, ensure_ascii=False))

UnicodeEncodeError: 'gbk' codec can't encode character '\xa1' in position 98690: illegal multibyte sequence

**Comment by Allen-dududu** [comment]
f.write() 试着用encoding='utf8'，如果你的文件是用utf8格式读的，写的时候因为默认是gbk，所以可能会出错

**Comment by ppvv6688** [comment]
> f.write（）试着用encoding ='utf8'，如果你的文件是用utf8格式读的，写的时候因为只是是gbk，所以可能会出错

去包里源文件修改么？我不太会啊

**Comment by Allen-dududu** [comment]
> > f.write（）试着用encoding ='utf8'，如果你的文件是用utf8格式读的，写的时候因为只是是gbk，所以可能会出错
> 
> 去包里源文件修改么？我不太会啊

f.write(json.dumps(self.to_dict(), indent=2, ensure_ascii=False), encoding ='utf8' )

**Comment by ppvv6688** [comment]
谢谢

**Comment by BrikerMan** [comment]
新版本应该已修复，在测试看看～
