### ISSUE TITLE
[Question] Errors of Bi_LSTM classification model when using TF 2.4.1 and kashgari 2.0.1

### ISSUE THREAD

**Issue by Harrypeas** [BrikerMan/Kashgari#459]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [✅ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ✅] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [Linux]:
- Python Version:3.8.5
- requirements.txt:tensorflow 2.4.1, kashgari 2.0.1

```txt
[Paste requirements.txt file here]
```

## Question

I'm trying to create a Chinese text classification model (BiLSTM) by following the tutorial. I have two environments, one is tensorflow1.5 on my MacBook, and the other one is tensorflow2.4.1 and kashgari2.0.1 on my linux server. On my MacBook, the model works well and the accuracy achieves 99% in the first epoch. However, the model on the server performs bad, its loss is decreasing at the first (the minimum is about 0.5), then it starts to grow (the maximum is about 3.0), and finally it decreases slowly. Besides, there has some other errors in my model, for example, I set the sequence length to 512 but the message in the figure shows that it is None. I know that tutorial is more applicable for tensorflow1.X, so I would like to if there any problems in my code.
<img width="650" alt="截屏2021-03-02 上午10 55 10" src="https://user-images.githubusercontent.com/17609739/109592133-bab22c00-7b49-11eb-9913-a4de8136af9e.png">
<img width="1004" alt="截屏2021-03-02 上午10 56 20" src="https://user-images.githubusercontent.com/17609739/109592162-c998de80-7b49-11eb-8bd3-0f6ada829760.png">

**Comment by BrikerMan** [comment]
Please retry it with the latest version.
