### ISSUE TITLE
您好！序列标注中，想预测很多句子，一个一个去预测时间好慢，可以实现批量的运算吗？[Question] 

### ISSUE THREAD

**Issue by baketbek** [BrikerMan/Kashgari#477]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [e.g. Mac OS, Linux]:
- Python Version:
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[A clear and concise description of what you want to know.]

**Comment by BrikerMan** [comment]
predict 接口就可以传多个 sentence，本来就是个`[sample]`

**Comment by baketbek** [comment]
> predict 接口就可以传多个 sentence，本来就是个`[sample]`

感恩 刚尝试了一下，可以的。效率也提上来了。幸亏遇到这个项目，简直太棒了，上来就解决业务需求！！！必须打 call。能方便加上大佬微信，私下请教沟通吗？
