### ISSUE TITLE
[Question] How to adjust learning rate when I use Bi-LSTM model on classification task?

### ISSUE THREAD

**Issue by honeysuckcle** [BrikerMan/Kashgari#484]
## Environment

- OS : Linux
- Python Version: 3.8.10

## Question

How to adjust learning rate when I use Bi-LSTM model on classification task?
如何调整BiLSTM在分类任务上的学习率？

**Comment by BrikerMan** [comment]
You can use a custom optimizer by using https://kashgari.readthedocs.io/en/latest/tutorial/text-labeling/#use-custom-optimizer.
