### ISSUE TITLE
[Question] 关于继续学习添加新的实体

### ISSUE THREAD

**Issue by SkyHunterC** [BrikerMan/Kashgari#485]
**You must follow the issue template and provide as much information as possible. otherwise, this issue will be closed.
请按照 issue 模板要求填写信息。如果没有按照 issue 模板填写，将会忽略并关闭这个 issue**

## Check List
Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.

**You can post pictures, but if specific text or code is required to reproduce the issue, please provide the text in a plain text format for easy copy/paste.**

- [ ] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.
- [ ] I have read the [documents](https://kashgari.bmio.net)

## Environment

- OS [Linux]:
- Python Version: 3.6
- requirements.txt:

```txt
[Paste requirements.txt file here]
```

## Question

[我是个小白，关于继续学习，如果数据集添加了新的实体，比如 GAME，BOOK，能在原模型的基础上compile_model后继续学习吗？我这里回报一个KeyError的错误]

**Comment by BrikerMan** [comment]
由于增加实体会导致模型最后一个层输出大小变化，目前不支持持续训练。只能从头重新训练。
