### ISSUE TITLE
导入BERTEmbedding失败

### ISSUE THREAD

**Issue by Robinaoko** [BrikerMan/Kashgari#487]
您好，我使用Anaconda安装环境如下：

python 3.6
tensorflow ==2.5.0
tensorflow_addons==0.13.0
kashgari 2.0.2

得到的错误是：ImportError: cannot import name 'Bertembedding'
尝试了很多办法，新建了很多环境也没有解决，求助！

**Comment by hwq458362228** [comment]
是不是因为E要大写，应该是“BertEmbedding”，你的报错里写的是“Bertembedding”

**Comment by Robinaoko** [comment]
> 是不是因为E要大写，应该是“BertEmbedding”，你的报错里写的是“Bertembedding”
是的是的！解决了，非常感谢！
