### ISSUE TITLE
怎么让模型对一篇文章打上多个分类而不是只能有一种分类？

### ISSUE THREAD

**Issue by lvouran** [BrikerMan/Kashgari#49]
A clear and concise description of what you want to know.

**Comment by BrikerMan** [comment]
下载最新版本，然后
1. 初始化模型时候 multi_label = True。如 model = CNNModel(multi_label=True)
2. 传入 y 为一个二维数组例如 y= [[a, b], [a]]
就可以了。

lvouran <notifications@github.com>于2019年3月12日 周二11:23写道：

**Comment by BrikerMan** [comment]
请问有解决您的问题么？

**Comment by lvouran** [comment]
暂时还没有试这个，，因为之前问的，想在文化一个大方向下面分出来5个小类（数据量不太平衡，分别是3000，8000，2000， 600， 600）然后统一选择了两千，结果不管怎么训练结果都不理想.....

**Comment by BrikerMan** [comment]
是不是数据本身特征就不是很明显？词向量，分词这些都没有帮助是么？

**Comment by lvouran** [comment]
数据本身特征确实不明显，我不知道是不是我数据集分的问题，很多次训练完，，用评估集或者训练集，效果挺好的，一用别的数据，总是只能一直被分到一种或者两种类别里面。

**Comment by BrikerMan** [comment]
如果没有新的问题，我就关闭这个 issue 了。

**Comment by lvouran** [comment]
没有了，，关了吧，，感谢
