### ISSUE TITLE
[Bug]x_data ,y_data =SMP2017ECDTClassificationCorpus.get_classification_data()

### ISSUE THREAD

**Issue by szq261299** [BrikerMan/Kashgari#51]
RuntimeError: Error while fetching file http://storage.eliyar.biz/corpus/smp2017ecdt-data-task1.tar.gz. Dataset fetching aborted.
Error: HTTP Error 301: The HTTP server returned a redirect error that would lead to an infinite loop.
The last 30x error message was:
Moved Permanently

看起来好像是无法访问数据存放的网站，怎么修复~

**Comment by szq261299** [comment]
如果直接访问 http://storage.eliyar.biz/corpus/smp2017ecdt-data-task1.tar.gz  会报

该网页无法正常运作
storage.eliyar.biz 将您重定向的次数过多。

手动清除cookie 仍出现该问题

**Comment by BrikerMan** [comment]
fixed~
