### ISSUE TITLE
wordembedding trainable=True 后报OOM[Question] 

### ISSUE THREAD

**Issue by melansediao** [BrikerMan/Kashgari#52]
把你的Word embedding里面的trainable=False 改成trainable=True，for循环batchsize和epoch，循环到中间就会报OOM，请问是什么原因呢？

同样情况下的trainable=False以及custom embedding不会报OOM。

**Comment by BrikerMan** [comment]
没尝试过把 WordEmbedding 改成 trainable。一般加载训练好的词向量就不会再 Train，你是想加载一个预训练的词向量作为 Embedding 层，然后训练过程中再继续更新这个 Embedding 层么？

**Comment by melansediao** [comment]
对的

**Comment by melansediao** [comment]
还有我下载了sgns的搜狗news不知道怎么使用，在你的代码里找了好久没找到文件路径？
sgns.sogounews.bigram-char.bz2

**Comment by BrikerMan** [comment]
你可以使用任何预训练的 W2V，下载的某个目录，然后用这个目录初始化 WordEmbedding 即可。比如下载到了 `/download/sgns.sogounews.bigram-char.bz2` 那就初始化
```
embedding = WordEmbedding('/download/sgns.sogounews.bigram-char.bz2')
```

**Comment by melansediao** [comment]
好的，谢谢

**Comment by melansediao** [comment]
Invalid data stream
直接这样不行，我自己的embedding.txt是可以用的，
用embedding = WordEmbedding('/download/sgns.sogounews.bigram-char.bz2')，报错：Invalid data stream

**Comment by BrikerMan** [comment]
`.bz2` 是压缩格式，解压后试试。
