### ISSUE TITLE
[Question] 离线安装kashgari

### ISSUE THREAD

**Issue by woshipig123** [BrikerMan/Kashgari#53]
因为特殊情况没有网，离线安装kashgari显示没有安装tensorflow，但是我已经安装了tensorflow_gpu=1.12.0，并且tensorflow任务可以正常跑。之后，我尝试安装了cpu版本的tensorflow,
kashgari可以正常使用。请问这应该是什么问题？？？

**Comment by BrikerMan** [comment]
离线安装还真没尝试过，可以尝试创建一个新的虚拟环境，安装 kashgari，再安装 tensorflow-gpu。

**Comment by BrikerMan** [comment]
请问解决了吗？

**Comment by BrikerMan** [comment]
由于长期没有反馈，先关闭了~
