### ISSUE TITLE
[Question] 调用bert之后是不是只能直接用 不能进行fine tune呢

### ISSUE THREAD

**Issue by niurouli** [BrikerMan/Kashgari#56]
如题

**Comment by BrikerMan** [comment]
Kashgari 是使用 feature extract 方式迁移学习，并没有对 BERT 直接进行修改。这样也一样能利用 BERT 做迁移学习，使用上没有任何问题。

**Comment by niurouli** [comment]
而且在bertembedding.embembed函数中添加了print 大大降低了运行速度

**Comment by BrikerMan** [comment]
没有明白，麻烦更详细一些。

**Comment by BrikerMan** [comment]
这个确实是个 bug，但是模型训练时候不会走 embed 方法，不影响模型训练。

**Comment by niurouli** [comment]
对 是这样 我在加载bert的时候就看到窗口内的打印信息 就感觉慢了好多

**Comment by BrikerMan** [comment]
BERT 模型本身很大，打印出来的是 BERT 的模型结构层。BERT 现阶段就是很慢，这个暂时没有解决办法。

**Comment by niurouli** [comment]
谢谢解答
