### ISSUE TITLE
[BUG] Listcomp on Line 133 for multi_label classification in base_model.py may have a bug

### ISSUE THREAD

**Issue by alexwwang** [BrikerMan/Kashgari#57]
## Check List

Thanks for considering to open an issue. Before you submit your issue, please confirm these boxes are checked.
- [ *] I have searched in [existing issues](https://github.com/BrikerMan/Kashgari/issues?utf8=%E2%9C%93&q=is%3Aissue+) but did not find the same one.

## Environment

* OS [e.g. Mac OS, Linux]:
* requirements.txt:
```
None business of OS.
```

### What

unhashable type: 'list' when dealing with multi label y data.

### Reproduce

For multi_label classification tasks, if label data (y) have a data structure like `[ list[str] ]`, 
e.g. `[ ['a'], ['b', 'c'], ['a', 'c']]`, this error occur.

### Other Comment

I will revision the method related, say `ClassificationModel.convert_idx_to_label`.

Would you please check if the test part works well under current circumstance? I suspect for that.

**Comment by BrikerMan** [comment]
Ok, I will try to reproduce and fix this.

**Comment by alexwwang** [comment]
And the `class_weight` dealing under `multi_label` circumstance seems not been considered yet.

**Comment by alexwwang** [comment]
I will make a PR later.
And please help to check if it is mathematical correct of my way to fix that.
Thanks in advance.

**Comment by BrikerMan** [comment]
Merged~
