### ISSUE TITLE
[Question] alueError: Tensor Tensor("non_masking_layer_1/Identity:0", shape=(?, 50, 768), dtype=float32) is not an element of this graph.

### ISSUE THREAD

**Issue by niurouli** [BrikerMan/Kashgari#58]
A clear and concise description of what you want to know.
在将bert预训练词向量导入自己搭建的模型之后，参数没问题之后，结果这个报个这个错误，可是我的模型中没有用到non_masking_layer_1啊？

**Comment by niurouli** [comment]
经检查 是bertEmbedding.embed()函数出现的问题

**Comment by dancinghui** [comment]
我也遇到了同样的问题，是在模型训练好以后做预测的时候

**Comment by BrikerMan** [comment]
@dancinghui 是什么版本呢？
