### ISSUE TITLE
使用bert作为嵌入时，input层是两层？和使用w2v嵌入调用方式不一样吧[Question] 

### ISSUE THREAD

**Issue by wqw123** [BrikerMan/Kashgari#62]
A clear and concise description of what you want to know.

**Comment by BrikerMan** [comment]
是的，目前框架会用一个全 0 的数组作为第二个输入。

**Comment by wqw123** [comment]
> 是的，目前框架会用一个全 0 的数组作为第二个输入。

所以比方说我使用您提供的bert作为自己网络的嵌入，那么我的keras model在 fit时候的数据应该是x=[train_x,[全0]]对吧？无论是序列标注问题还是分类问题

**Comment by BrikerMan** [comment]
是的～

吴琦炜 <notifications@github.com>于2019年4月8日 周一17:18写道：

**Comment by wqw123** [comment]
非常感谢您的回答
