### ISSUE TITLE
[BUG] embedding = BERTEmbedding('bert-base-chinese', sequence_length=600)

### ISSUE THREAD

**Issue by Owenscu** [BrikerMan/Kashgari#63]
设置成６００报错，说只能５１２
![image](https://user-images.githubusercontent.com/23129979/55720411-5eb0fc80-5a33-11e9-9bb6-d6fedb4e1f07.png)

**Comment by ljsun** [comment]
请问这个问题解决了吗？另外想问下可不可以不设置长度呀，因为在预测时根本不知道长度是多少？

**Comment by BrikerMan** [comment]
@Owenscu BERT 预训练模型序列最大长度只能是 512，这个没办法修改。

**Comment by BrikerMan** [comment]
@ljsun 不可以的，你可以设定个能满足绝大部分数据的序列长度。如果不足的会做 Padding，超出就截断。
