### ISSUE TITLE
[Question] BLSTMModel文本分类，做预测很慢

### ISSUE THREAD

**Issue by SilenceWinter** [BrikerMan/Kashgari#66]
您好
    预测的数据量100M，2块1080ti GPU，CPU i7 12核
    从加载已训练好的模型到预测结果输出，整个过程26分钟。
   而CNNModel 10秒就完成了

**Comment by BrikerMan** [comment]
这个时间明显有问题，请问用了什么 embedding？可以提供加载代码么？

**Comment by BrikerMan** [comment]
请问能提供更详细的信息么？

**Comment by BrikerMan** [comment]
最新的 tf-keras 版本支持了 TPU/多 GPU，可以试试看。
