### ISSUE TITLE
保存的模型可以进行量化吗？ 或者是生成PB文件，这样可以提升效率

### ISSUE THREAD

**Issue by huyi1989** [BrikerMan/Kashgari#67]
A clear and concise description of what you want to know.

**Comment by BrikerMan** [comment]
没太看明白，请问这个能解决你的问题么？ #17

**Comment by BrikerMan** [comment]
请问问题解决了么？

**Comment by huyi1989** [comment]
解决了，我通过生成h5文件，再将h5转成pb文件进行量化模型，但是量化后的模型大小没有改变太多（按理来说应该会减小一半以上才是），不知道是不是因为用了bert的结构才这样的。

**Comment by BrikerMan** [comment]
> 解决了，我通过生成h5文件，再将h5转成pb文件进行量化模型，但是量化后的模型大小没有改变太多（按理来说应该会减小一半以上才是），不知道是不是因为用了bert的结构才这样的。

可能是～ 解决了就好。后期可能会把 keras 替换成 tf.keras，到时候应该就省去了很多问题。更方便的导出和用 serving 部署。
