### ISSUE TITLE
[Question] how to fine tune BERT-base model with multi-GPUs

### ISSUE THREAD

**Issue by HaoyuHu** [BrikerMan/Kashgari#68]
Currently I try to fine tune models on GPUs with the huge BERT-Large model (batch_size>=128), Does Kashgari support for training on a large number of GPUs?
Thanks for this awesome project! :P

**Comment by BrikerMan** [comment]
I haven't tried to try with multi GPU, I think you can just do it like this.
https://keras.io/getting-started/faq/#how-can-i-run-a-keras-model-on-multiple-gpus

```python
model = CNNModel(embedding)
# build basic model and labels, etc.
model.fit(x, y, epoch=1)

# get keras-model from kashgari model
keras_model = model.model

# build multi gpu model
from keras.utils import multi_gpu_model

# Replicates `model` on 4 GPUs.
# This assumes that your machine has 4 available GPUs.
parallel_model = multi_gpu_model(keras_model, gpus=4)
# compile again
parallel_model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

# Then run again
model.model = parallel_model
model.fit(x, y, epochs=1000)
```

**Comment by HaoyuHu** [comment]
Everything looks good. If I have any problems, I will reopen this issue. Thank you very much!
