### ISSUE TITLE
[Question] 怎么保存和加载最优模型？

### ISSUE THREAD

**Issue by chizhu** [BrikerMan/Kashgari#70]
想要加载最优的模型文件而不是最后一个epoch的模型文件，ModelCheckpoint在这里不起作用

我在class ClassificationModel(BaseModel)里面，加了个函数：
```python
def load_weights(self, model_path):
        return self.model.load_weights(model_path)
```
然后调用
```python
early_stopping = EarlyStopping(monitor='val_loss',min_delta=0.01, patience=5, mode='min', verbose=1)
reduce_lr = ReduceLROnPlateau(
        monitor='val_loss', factor=0.5, patience=5, min_lr=0.0001, verbose=2)
bst_model_path = 'weight_%d.h5' % count
checkpoint = ModelCheckpoint(bst_model_path, monitor='val_loss', mode='min',
                                       save_best_only=True, verbose=1, save_weights_only=True)
callbacks = [checkpoint,reduce_lr,early_stopping]
hist = model.fit(x_train,y_train,
                     validation_data=(x_val, y_val),
                     epochs=4, batch_size=512,
#                      class_weight="auto",
#                      callbacks=callbacks,
                     fit_kwargs={"callbacks":callbacks,"verbose":1}
                     
                     )
model.load_weights(bst_model_path)
```
但是显示不存在weight_0.h5文件，说明 ModelCheckpoin并未被调用

**Comment by BrikerMan** [comment]
看着代码没问题啊，你在这里再加个 Tensoboard 的回调看看能不能写 Tensoboard 日志。

**Comment by chizhu** [comment]
callbacks 是可以正常调用early_stop 和Tensoboard 以及自定义auc_eval。。。。但就是不能用ModelCheckpoint

**Comment by BrikerMan** [comment]
那么可以尝试换换 ModelCheckpoint 的参数，如果别的能正常用说明传参到 keras 没有问题... 估计就是 ModelCheckpoint 参数的问题。

**Comment by chizhu** [comment]
感谢你的回复！ModelCheckpoint 这个参数是最普通的参数，我看到你model的fit函数封装的是fit_generator ，我在想可能是它引起的，我改一波。

**Comment by alexwwang** [comment]
Since Kashgari defines the save and load method in its abstracted base model class, I recommend you to load model weights file by the load method of kashgari class itself.

However, the default model weights file is named 'model.model', and if you use `ModelCheckpoint`, you should designate a different name for the weights file, say 'best_checkpoint.h5' to avoid it being overwritten by the saving procedure at the end of training.

Then you could rename the 'best_checkpoint.h5' file back to 'model.model' to overwrite the original one and then load them back to memory for further use.

Refer to the usage of `ModelCheckpoint` method in kashgari's callbacks, you should first initial an instance of `ModelCheckpoint`, e.g.
```
checkpointer = ModelCheckpoint(filepath=f"{your_path_to_save_model_weights}/best_cp.h5",
                                                        monitor='val_acc',
                                                        save_best_only=True,
                                                        save_weights_only=False)
```
and then when you would like to train your model, you should call `fit` method like below:
```
# call model fit method
model.fit(x_train, y_train, epochs, batch_size, fit_kwargs={'call_backs': [checkpointer]})
```
please be notices the usage of `fit_kwargs` and the dict form of its value.

**Comment by chizhu** [comment]
thank you for detailed reply, I  will try it.

**Comment by alexwwang** [comment]
Maybe we should add supports for users to load model weights files of custom-defined names. @BrikerMan

**Comment by chizhu** [comment]
解决了 。是我的问题,我那个实现方式是可行的。
```python
hist = model.fit(x_train,y_train,
                     validation_data=(x_val, y_val),
                     epochs=4, batch_size=512,
#                      class_weight="auto",
#                      callbacks=callbacks,
                     fit_kwargs={"callbacks":callbacks,"verbose":1}
                     
                     )
```
中的
```python
  validation_data=(x_val, y_val),
```
改为
```python
x_val, y_val
```
和fit函数参数对齐即可。

**Comment by kangbrilliant** [comment]
@chizhu  您好，我按照您的方法可以成功保存模型，
但是我在加载的时候，报错`  File "C:\ProgramData\Anaconda3\envs\python3\lib\site-packages\kashgari\tasks\seq_labeling\blstm_crf_model.py", line 50, in load_weights
    return self.model.load_weights(model_path)
AttributeError: 'NoneType' object has no attribute 'load_weights'`

**Comment by BrikerMan** [comment]
> @chizhu 您好，我按照您的方法可以成功保存模型，
> 但是我在加载的时候，报错
> ` File "C:\ProgramData\Anaconda3\envs\python3\lib\sitepackages\kashgari\tasks\seq_labeling\blstm_crf_model.py", line 50, in load_weights return self.model.load_weights(model_path) AttributeError: 'NoneType' object has no attribute 'load_weights'`

这个是因为只保存了权重，没有保存模型的别的参数导致。建议训练模型后先用 `model.save('target_folder')` 保存一下模型全部设定，然后再保存最优权重。等训练结束，把 `target_folder` 目录下的 h5 文件替换为最优权重，然后加载。

**Comment by kangbrilliant** [comment]
@BrikerMan  您好，感谢您的回复。我试过了把最优的*.h5替换到
模型训练完毕后的文件夹里，即把*.h5重命名为model.model。
然后用Kashgari原生的调用方式，
`model = model.load_model('ber/')`
还是不行，报错
`  File "C:\ProgramData\Anaconda3\envs\python3\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__      raise ValueError('Cannot create group in read only mode.')
ValueError: Cannot create group in read only mode.`
---------------------------
顺便说下，全部用原生的保存模型及加载是正常的

**Comment by chizhu** [comment]
我是把他封装的build_model抽离出来 ，加载模型的时候要先model.build_model()

**Comment by BrikerMan** [comment]
> ## @BrikerMan 您好，感谢您的回复。我试过了把最优的*.h5替换到
> 模型训练完毕后的文件夹里，即把*.h5重命名为model.model。
> 然后用Kashgari原生的调用方式，
> `model = model.load_model('ber/')`
> 还是不行，报错
> ` File "C:\ProgramData\Anaconda3\envs\python3\lib\site-packages\keras\utils\io_utils.py", line 302, in __getitem__ raise ValueError('Cannot create group in read only mode.') ValueError: Cannot create group in read only mode.`
> 值得提一下的是，全部用原生的保存模型及加载是正常的

请问保存的时候使用什么代码保存的？

**Comment by kangbrilliant** [comment]
@BrikerMan
是用@build_model上面的方法

**Comment by kangbrilliant** [comment]
@chizhu  您好，请问您是否方便展示一下如何加载的demo，感谢~

**Comment by chizhu** [comment]
```python
class ClassificationModel(BaseModel):
    def load_weights(self, model_path):
        return self.model.load_weights(model_path)
```

调用
```python
model = ATTModel(bert_embedding)
model.build_model()
model.load_weights(bst_model_path)
```

**Comment by kangbrilliant** [comment]
> ```python
> class ClassificationModel(BaseModel):
>     def load_weights(self, model_path):
>         return self.model.load_weights(model_path)
> ```
> 
> 调用
> 
> ```python
> model = ATTModel(bert_embedding)
> model.build_model()
> model.load_weights(bst_model_path)
> ```

感谢，我也是这样调用的。但是error：显示函数build_model()，需要传参'x_train' and 'y_train'

**Comment by BrikerMan** [comment]
@kangbrilliant 这个是版本不同导致问题，请问你是在用那个版本，我给你一个 demo.

**Comment by kangbrilliant** [comment]
> @kangbrilliant 这个是版本不同导致问题，请问你是在用那个版本，我给你一个 demo.

感谢，我的requirements：
tensorflow-gpu==1.12.0
keras==2.2.4
Kashgar==0.2.4

**Comment by chizhu** [comment]
最新版的也行 ，你只要把参数按照要求传进build_model()

**Comment by BrikerMan** [comment]
训练模型

```python
from kashgari.corpus import ChinaPeoplesDailyNerCorpus
from kashgari.tasks.seq_labeling import BLSTMModel

from keras.callbacks import ModelCheckpoint
checkpointer = ModelCheckpoint(filepath=f"best_cp.h5", 
                               monitor='val_acc', 
                               save_best_only=True,
                               save_weights_only=False)


x, y = ChinaPeoplesDailyNerCorpus.get_sequence_tagging_data('test')
valid_x, valid_y = ChinaPeoplesDailyNerCorpus.get_sequence_tagging_data('valid')

model = BLSTMModel()
model.fit(x, y, fit_kwargs={"callbacks":[checkpointer], "verbose":1}, batch_size=256)
# 完整保存下来，这样后续不需要 build
model.save('fully_saved_model')
```

```python
# 完整加载老模型
new_model = BLSTMModel.load_model('fully_saved_model')
# 加载新的权重
new_model.model.load_weights('best_cp.h5')
```

后续的 tf.keras 版本，我们加上只构建模型，不加载权重的方法，这样就不需要加载之前的权重就能构建模型，然后再加载指定的权重。

**Comment by kangbrilliant** [comment]
> 训练模型
> 
> ```python
> from kashgari.corpus import ChinaPeoplesDailyNerCorpus
> from kashgari.tasks.seq_labeling import BLSTMModel
> 
> from keras.callbacks import ModelCheckpoint
> checkpointer = ModelCheckpoint(filepath=f"best_cp.h5", 
>                                monitor='val_acc', 
>                                save_best_only=True,
>                                save_weights_only=False)
> 
> 
> x, y = ChinaPeoplesDailyNerCorpus.get_sequence_tagging_data('test')
> valid_x, valid_y = ChinaPeoplesDailyNerCorpus.get_sequence_tagging_data('valid')
> 
> model = BLSTMModel()
> model.fit(x, y, fit_kwargs={"callbacks":[checkpointer], "verbose":1}, batch_size=256)
> # 完整保存下来，这样后续不需要 build
> model.save('fully_saved_model')
> ```
> 
> ```python
> # 完整加载老模型
> new_model = BLSTMModel.load_model('fully_saved_model')
> # 加载新的权重
> new_model.model.load_weights('best_cp.h5')
> ```
> 
> 后续的 tf.keras 版本，我们加上只构建模型，不加载权重的方法，这样就不需要加载之前的权重就能构建模型，然后再加载指定的权重。

感谢，测试通过了。
不过这里 save_weights_only=False 需要改为  save_weights_only=True
