### ISSUE TITLE
[Question] 再次打扰了，我用这个在其他的数据集做命名实体识别，请问训练过程中loss在降，但是acc在波动，这个正常吗，我到底看哪个指标会好一点

### ISSUE THREAD

**Issue by Owenscu** [BrikerMan/Kashgari#80]
A clear and concise description of what you want to know.
![image](https://user-images.githubusercontent.com/23129979/57179519-4658c400-6eb1-11e9-89be-812ff7ac7ec4.png)

**Comment by BrikerMan** [comment]
loss 持续下降就好，最终结果使用 `evaluate` 函数查看

**Comment by wjjwsl** [comment]
你好，请问evaluate函数是kashgari自带的么？为什么我找不到呢？

**Comment by BrikerMan** [comment]
> 你好，请问evaluate函数是kashgari自带的么？为什么我找不到呢？

是 kashgari 的 Model 对象的函数。

**Comment by wjjwsl** [comment]
谢谢！找到了。
