### ISSUE TITLE
[Feature request] Support for multi-input

### ISSUE THREAD

**Issue by chizhu** [BrikerMan/Kashgari#83]
Your team really did  great work , but I suggest that allow multi-input is better for classify task.

**Comment by BrikerMan** [comment]
Please try out the TwoHeadEmbedding, we recently added this embedding class.

https://github.com/BrikerMan/Kashgari/blob/a287ee9ef01185dcd2ae9676c39b02b686a13c88/tests/test_embeddings.py#L106

**Comment by chizhu** [comment]
Thank you for pointing this. In addition ,if I want to use two-input for bert-emb , how can I do?

**Comment by alexwwang** [comment]
Actually the model part has been multiple input ready.

The only work you need to do is defining your own embedding layers to pass
those inputs in.

**Comment by alexwwang** [comment]
As far as I know, Bert has its own inputs regime, which means you could use
the features extracted from it as one input and mix it up with other inputs.

However you have to write your own embedding layer to make this purpose by
now. Wish the two-heads layer would inspire you in a certain way.

**Comment by chizhu** [comment]
Thank you for reply,I will try it soon.
