### ISSUE TITLE
做ner时，为什么输出内容会少，比如输入是15个字，输出只到11个字为止，缺了后面的内容

### ISSUE THREAD

**Issue by huyi1989** [BrikerMan/Kashgari#84]
A clear and concise description of what you want to know.

**Comment by BrikerMan** [comment]
请问是用的那个版本？

**Comment by huyi1989** [comment]
是0.2.1的

**Comment by BrikerMan** [comment]
可以提供一下具体的输入输出和模型参数，相关代码么？

**Comment by huyi1989** [comment]
模型是用BLSTMCRFModel，没有进行BERT embedding，训练参数是默认的，没添加什么其他设置

**Comment by pmp55** [comment]
这种情况我遇到过，仔细一查，发现是序列长度超过512了，因此，导入数据前，要检查下标注的序列长度

**Comment by huyi1989** [comment]
@pmp55 那怎么设置序列的最大长度，我的情况是不能超过11吗？ 那也太短了

**Comment by BrikerMan** [comment]
麻烦打印模型参数看看。
```python
model.model.summary()
```

**Comment by huyi1989** [comment]
@BrikerMan 问题好像是在对句子进行embedding时长度的设置，我将base.model.py中的self.embedding.sequence_length = sorted([len(x) for x in x_train])[int(0.95 * len(x_train))]该变为self.embedding.sequence_length = max([len(x) for x in x_train])或是规定一个最大长度，就输出完整了

**Comment by BrikerMan** [comment]
初始化model 后，再设定一下序列长度~ 这一块后期会做修改。
