### ISSUE TITLE
multiple output [Question] 

### ISSUE THREAD

**Issue by w5688414** [BrikerMan/Kashgari#86]
how can I use multiple output model?

**Comment by BrikerMan** [comment]
Please provide more details.

**Comment by w5688414** [comment]
My model takes one input and produces multiple outputs.

**Comment by BrikerMan** [comment]
Multi-label classification?

**Comment by habolivier** [comment]
Yes.

**Comment by BrikerMan** [comment]
https://github.com/BrikerMan/Kashgari/issues/27#issuecomment-473169833

Next time, please check the issue list and follow the issue template.
