### ISSUE TITLE
做ner时，使用提供的案例代码，结果与文中相差较大

### ISSUE THREAD

**Issue by hanyuzhao** [BrikerMan/Kashgari#87]
我在使用https://eliyar.biz/nlp_chinese_bert_ner/这篇文章里的代码进行测试时(使用的模型为B-LSTM-CRF)，发现f1并非文中所说的0.9220，只有不到0.8。而且我不太明白，batch_size应该设置为示例代码中的500，还是文中基础参数所说的2317?

**Comment by BrikerMan** [comment]
batch-size 小也没关系，请问循环了多少次？

**Comment by hanyuzhao** [comment]
跟您的样例代码一致也是200代。

**Comment by BrikerMan** [comment]
这几天测试发现 0.2.1 版本效果非常好，可以使用 0.2.1 版本复现一下。具体为什么原因导致之后效果下降还没搞清楚，还在排查。

**Comment by BrikerMan** [comment]
@hanyuzhao 可以用这个 notebook 测试一下，我已经复现了结果。https://gist.github.com/BrikerMan/efd8c95b0450fc73f387e0fc85ad7408
