### ISSUE TITLE
Usage of multi-label classification 

### ISSUE THREAD

**Issue by habolivier** [BrikerMan/Kashgari#88]
Hello Dear BrikerMan, 
I am trying to do multi-label classification using Kashgari. 

The last layer of my model is like this: 

self.model = Model(base_model.inputs, [dense_2_layer,dense_3_layer])

I am having my X like this  
x=['a','b','c','d','e']

My labels=
y1=[1,0,1,1,1]
y2=[1,1,0,1,0]

I converted them to the format required (i followed the test_classifier_models.py on line 41), i convert my labels

y=[[1,1],[0,1],[1,0],[1,1],[1,0]]

fitting

model.fit(x, y, epochs=2)

However, i get the following error:
-----------------------
ValueError: Error when checking model target: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
 

Thank your hard work.

**Comment by BrikerMan** [comment]
Maybe change your data to this,

```python
x1 = ['a', 'b', 'c']
y1 = ['class1', 'class3']  # keep the final result, don't pre-process your labels.
x2 = ['a', 'a', 'c']
y1 = ['class2', 'class4']
x_data = [x1, x2, .....]
y_data = [y1, y2, .....]
```

**Comment by habolivier** [comment]
Hello Dear @BrikerMan . I  tried to follow your suggestion, unfortunately i did succeed!!!
Let's take example of  your  existing data and model, and then copy each into two inputs and two labels lists.  
However, the base models raises an error.

base_model.py", line 257, in fit
    assert len(x_part) == len(y_train)
AssertionError
---------------------------------------------------------------

from kashgari.embeddings import BERTEmbedding
from kashgari.tasks.classification import CNNLSTMModel
from kashgari.corpus import SMP2017ECDTClassificationCorpus

bert_embedding = BERTEmbedding('bert-base-chinese', sequence_length=30)                                   
model = CNNLSTMModel(bert_embedding)

train_x, train_y = SMP2017ECDTClassificationCorpus.get_classification_data()

#Data is copied into two inputs and two outputs.
x_data=[train_x,train_x]
y_data=[train_y,train_y]

model.fit(x_data, y_data,epochs=1,multi_label=True)

Am wrongly using it?  Thank you.

**Comment by BrikerMan** [comment]
```python
# Here is your error
x_data=[train_x,train_x]
y_data=[train_y,train_y]
```

Your data should like this.

```python
x_data[0] = ['a', 'b', 'c']
y_data[0] = ['class1', 'class3']
```

Could you please provide a sample data?

**Comment by habolivier** [comment]
@BrikerMan  Thank you  for your help.  

model.fit(X_data[0], y_data[0], epochs=1) . It working perfectly.

**Comment by ahmednasserswe** [comment]
@BrikerMan 
I am a bit confused by your answer 
```x_data[0] = ['a', 'b', 'c']
y_data[0] = ['class1', 'class3']```
Isn't list unhashable? so the model should expect a tuple instead?

**Comment by BrikerMan** [comment]
> x_data[0] = ['a', 'b', 'c']

We have pre-processing logic that will handle the labeling issue, you could use list or tuple, pre-processing will take care of the rest.

**Comment by vagrantvv** [comment]
> 
> 
> Maybe change your data to this,
> 
> ```python
> x1 = ['a', 'b', 'c']
> y1 = ['class1', 'class3']  # keep the final result, don't pre-process your labels.
> x2 = ['a', 'a', 'c']
> y1 = ['class2', 'class4']
> x_data = [x1, x2, .....]
> y_data = [y1, y2, .....]
> ```
> 
> Then use the original classification model
> 
> ```python
> model = BLSTMMoldel()
> model.fit(x_data, y_data, multi_label=True)
> ```

multi_label=True写在函数里报错“unhashable”，如果在model = BLSTMModel()后面加一个model.multi_label=True然后再fit（不用再加multi_label=True）可以

**Comment by BrikerMan** [comment]
Here is the multi-label classification tutorial, check it out. [link](https://kashgari.rtfd.io/en/latest/md/text_classification_model.html#multi-label-classification)
