### ISSUE TITLE
非常棒的框架，节省了很多时间，能否把tensorflow的dashboard功能集成进来？

### ISSUE THREAD

**Issue by KantKatze** [BrikerMan/Kashgari#9]

**Comment by BrikerMan** [comment]
是指的 tensorboard 么？

**Comment by BrikerMan** [comment]
可以看看 https://github.com/BrikerMan/Kashgari/blob/master/docs/Tutorial_2_Classification.md#use-callbacks 能不能解决你的问题。

**Comment by BrikerMan** [comment]
请问问题解决了么？
