### ISSUE TITLE
[Feature request] CRF support for multi-gpu

### ISSUE THREAD

**Issue by chizhu** [BrikerMan/Kashgari#91]
use CRF layer with multiple GPU meet this error:
```python
/usr/local/lib/python3.5/dist-packages/keras_contrib-2.0.8-py3.5.egg/keras_contri
b/losses/crf_losses.py in crf_loss(y_true, y_pred)
     53     """
     54     crf, idx = y_pred._keras_history[:2]
---> 55     if crf.learn_mode == 'join':
     56         return crf_nll(y_true, y_pred)
     57     else:

AttributeError: 'Concatenate' object has no attribute 'learn_mode'
```
 But I have solve it now .
### refereance 
[CRF layer loss with multi_gpu_model](https://github.com/keras-team/keras-contrib/issues/453) 

> openning this issue is just for people who also meet it in the future.

**Comment by BrikerMan** [comment]
Is this problem solved?

**Comment by chizhu** [comment]
yep! see keras_contrib issue about crf




------------------ 原始邮件 ------------------
发件人: "Eliyar Eziz"<notifications@github.com>; 
发送时间: 2019年5月22日(星期三) 晚上10:04
收件人: "BrikerMan/Kashgari"<Kashgari@noreply.github.com>; 
抄送: "林智敏"<214416523@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [BrikerMan/Kashgari] [Feature request] CRF support for multi-gpu(#91)




Is this problem solved?

**Comment by BrikerMan** [comment]
@chizhu Hi, we are working on a tf.keras version. Could you help me test its multi-gpu capability? Install tf.keras branch then

```python
import kashgari
model = kashgari.tasks.labeling.BLSTMModel()
# Build model
model.build_model(train_x, train_y)

model = kashgari.utils.convert_to_multi_gpu_model(model, gpus=2)
model.fit(train_x, train_y)
```
