### ISSUE TITLE
[Question] Multi-output model

### ISSUE THREAD

**Issue by Qian16** [BrikerMan/Kashgari#92]
Hello Dear @BrikerMan.  Thanks for creating this good library. However, I want to perform multi-outputs classification(This is different to multi-label). 
My input is sentence and the outputs are two full-connected networks where each one has its own labels (One input-->Two branch networks).

I want to know if Kashgari supports multi-outputs classification.

input_text=[['This','news',are',very','well','organized'],
['What','extremely','usefull','tv','show'],
['The','tv','presenter','were','very','well','dress']]

label_list1=[1,0,1]
label_list2=[1,1,0]

xdata=input_text
ydata=[label_list1,label_list2]  #In Keras, for multi-output we make a list of both labels.
model.fit(xdata,ydata,epochs=1)

Thank you.

**Comment by BrikerMan** [comment]
Yes, kashgari support multi-label classifacation. 

```python
input_text = [
   ['This','news',are',very','well','organized'],
   ['What','extremely','usefull','tv','show'],
   ['The','tv','presenter','were','very','well','dress']
]

labels = [
   ['class1', 'class3'],
   ['class1', 'class2'],
   ['class1', 'class2', 'class3'],
]

model.fit(input_text, labels, multi_label=True)
```

**Comment by Qian16** [comment]
Dear @BrikerMan, thank you for your answer. I am little confused about how you transform the labels.

Actually, they  dataset with tokenized text input  looks like this:

      input_text                                                             |  label1  | label2
1.  ['This','news',are',very','well','organized']               |    1       |    1
2.  ['What','extremely','usefull','tv','show']                  |    0       |    1
3.  ['The','tv','presenter','were','very','well','dress']      |    1       |    0

So, i figure out how those 'class1','class2' and 'class3' are mapped. 
Thank you.

**Comment by alexwwang** [comment]
First, according to what you discribed, you actually want to train two
classifiers coordinately. This is possible because Kash is based on keras
which support multi-output form of deep models. All you need is to define
the model structure you want by heritaging it from the base classification
class of kash.

But there may be a bug existed in the `fit` method of dealing with multiple
output and need to be fixed. This potentia flaw was induced when I
implement the multiple input feature, when I just considered the simplest
scenario, without supporting multi-output.

So here are the alternatives:
1. we are working on refactoring the project and the base model class part
would be redesigned to be more flexible and you may keep an eye on the
process.

2. You may consider using multi-label to get over it or you may modify
those parts of code in current version and make a PR then.

It's up to you now and feel free to let us know. 😀

**Comment by BrikerMan** [comment]
Just keep the label that should be output as 1.

```
x: ['This','news',are',very','well','organized'] y:  [lavel1 , label2]
x: ['What','extremely','usefull','tv','show'] y:  [label2]
x: ['The','tv','presenter','were','very','well','dress'] y:  [label1]
```

**Comment by Qian16** [comment]
@alexwwang @BrikerMan Thank you. It will be nice to have Kash that supports all features. Big up guys.

**Comment by BrikerMan** [comment]
@Qian16 I got it wrong, Kashgari support multi-label classification. Not support the multi-output classification.

**Comment by alexwwang** [comment]
@BrikerMan By modifying method `get_data_generator` in classification base class, we could support multi-output classification. Users could define or assemble models themselves simply under Kash structure.

**Comment by Qian16** [comment]
@alexwwang Thank you. Can you show me the test you did(or tel me the exact line to change)? To define a model and assemble it to Kash i did. Thank you.

**Comment by BrikerMan** [comment]
> get_data_generator

I am working on it. I will submit the demo later today.

**Comment by Qian16** [comment]
@alexwwang Wow!  Thank you for saving my life!!!

**Comment by alexwwang** [comment]
@BrikerMan @Qian16 The main change need to be done is the processing of label or y data. Just like what have been done with x data in multi-input scenario, the y part also need an automatic de-nest from input list and re-nest when assemble to batch later.

It's not too hard, I think.

**Comment by alexwwang** [comment]
> @alexwwang Wow! Thank you for saving my life!!!

It's an honor of @BrikerMan. He'll implement the last mile. :)

**Comment by BrikerMan** [comment]
@alexwwang @Qian16 I have added an [example of a multi-output model](https://kashgari.readthedocs.io/en/tf.keras-version/tutorial/customize_multi_output_model.html). Check it out. Remember u need to run the `tf.keras-version` branch, and it is an early stage of development, may have lots of bugs.

**Comment by Qian16** [comment]
@BrikerMan @alexwwang Thank you for great job.  It working correctly.

**Comment by Qian16** [comment]
@BrikerMan Did you try to use BERTEmbedding ?

**Comment by BrikerMan** [comment]
Not yet, but it should work fine. Remember to pull the latest code.

**Comment by Qian16** [comment]
@BrikerMan . Thx.  By using BERT it raises any in **fit** function

bert_path='tests/test-data/bert'
embedding = BERTEmbedding(bert_path=bert_path,processor=processor,sequence_length=30)   
m = MultiOutputModel(embedding=embedding)

AttributeError: 'tuple' object has no attribute 'shape'

Thankx.

**Comment by Qian16** [comment]
@BrikerMan to run BERT, we need to change in keras fit() function
#Build batch logs
if isinstance(x,tuple):
batch_size=x[0].shape[0]

Thanks.

**Comment by BrikerMan** [comment]
> @BrikerMan to run BERT, we need to change in keras fit() function
> #Build batch logs
> if isinstance(x,tuple):
> batch_size=x[0].shape[0]
> 
> Thanks.

Fixed, Added new test case at https://github.com/BrikerMan/Kashgari/commit/b27dea0cc8354b927ee13c42ccd040a745d89576 .

**Comment by Qian16** [comment]
The accuracy achieved by multi-output model is not poor!  The performance of individual models is very good compared to multi-output.  May be we need to check it again. Thx
